### ISSUE TITLE
Issue With Linking - /usr/bin/ld: CMakeFiles/zdoom.dir/asm_ia32/a.o: 

### ISSUE THREAD

**Issue by typhoidcoma** [mwydmuch/ViZDoom#112]
I am trying to compile on pocket C.H.I.P. And everything seems fine.  I know I have some sort of compile mismatch but can't really figure it out.  Any thoughts?

Builds everything to 100% then this...

[100%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/viz_depth.cpp.o
Linking CXX executable ../../../bin/vizdoom
/usr/bin/ld: CMakeFiles/zdoom.dir/asm_ia32/a.o: Relocations in generic ELF (EM: 3)
/usr/bin/ld: CMakeFiles/zdoom.dir/asm_ia32/a.o: Relocations in generic ELF (EM: 3)
CMakeFiles/zdoom.dir/asm_ia32/a.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:8556: recipe for target 'bin/vizdoom' failed
make[2]: **\* [bin/vizdoom] Error 1
CMakeFiles/Makefile2:821: recipe for target 'src/vizdoom/src/CMakeFiles/vizdoom.dir/all' failed
make[1]: **\* [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: **\* [all] Error 2
chip@chip:~/ViZDoom$

**Comment by mwydmuch** [comment]
Old issue, closing
