### ISSUE TITLE
I have problem installing in mac os 

### ISSUE THREAD

**Issue by spk921** [mwydmuch/ViZDoom#115]
Is this gcc problem ? I am using gcc-4.9 (Homebrew gcc49 4.9.3) 4.9.3

[ 34%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/posix/sdl/i_system.cpp.o
In file included from /usr/include/Availability.h:172:0,
                 from /usr/include/stdlib.h:61,
                 from /Users/sangpil_kim/git/ViZDoom/src/vizdoom/src/posix/sdl/i_system.cpp:24:
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:1242:34: error: expected '}' before '**attribute**'
   kLSHandlerOptionsDefault       __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_4, __MAC_10_11, __IPHONE_4_0, __IPHONE_9_0, "Creator codes are deprecated on OS X.") = 0,
                                  ^
In file included from /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfo.h:529:0,
                 from /System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:27,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23,
                 from /Users/sangpil_kim/git/ViZDoom/src/vizdoom/src/posix/sdl/i_system.cpp:75:
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:1242:163: error: expected unqualified-id before '=' token
   kLSHandlerOptionsDefault       __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_4, __MAC_10_11, __IPHONE_4_0, __IPHONE_9_0, "Creator codes are deprecated on OS X.") = 0,
                                                                                                                                                                   ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:1294:1: error: expected declaration before '}' token
 }
 ^
make[2]: **\* [src/vizdoom/src/CMakeFiles/vizdoom.dir/posix/sdl/i_system.cpp.o] Error 1
make[1]: **\* [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
make: **\* [all] Error 2

**Comment by desimone** [comment]
Try with built in gcc that comes with xcode.

```
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by mwydmuch** [comment]
Old issue, closing.
