### ISSUE TITLE
How to use the reward mechanism?

### ISSUE THREAD

**Issue by tabsun** [mwydmuch/ViZDoom#127]
I can find living_reward and death_penalty settings in python examples. And Now I'd like to give reward to the moving distance, the question comes: How to make it in python bingding?
I mean the player's position on the map is (x,y), and after make_action his positon is changed to (x',y'), and reward =  distance( (x,y), (x',y' )*5.0. But How to implement this?
Expectation for anyone's advice, REALLY MUCH THANKS!

**Comment by ebonyclock** [comment]
This is out of scope of the binding or ViZDoom on the side of bindings/api. You should change how the reward is calculated in the scenario (wad file). To do so you need some map editor/compiler e.g. Doom Builder 2 or Slade3 (http://www.doombuilder.com/, http://slade.mancubus.net/).

deadly_corridor.wad achieves similar behavior so you can look there. In case of any trouble ask, I'll be happy to help.

**Comment by tabsun** [comment]
Thanks for @ebonyclock 's help and this question seems opening another world. IF ONLY the project can add actor's position or some other properties into the game_variables. And thank you again!

**Comment by ebonyclock** [comment]
@tabsun  We are considering adding support for extracting more information so it most likely be implemented some day.

**Comment by njustesen** [comment]
I added the actors position as a GameVariable in my fork https://github.com/njustesen/vizdoom-ai.
It was super easy.

**Comment by jerrybai1995** [comment]
I'm trying to do something similar. In take_cover.wad, for instance, how do I add a reward when the "player" successfully avoided taking a hit? I'm not familiar with the ACS... is there any function that can detect this? Thanks : )

**Comment by ebonyclock** [comment]
No, it would require lots of tinkering. It could be maybe done in acs but it would be quite tiresome (tracking all the missiles).

**Comment by Marqt** [comment]
@jerrybai1995 As I know ACS allows to attach event to a missile actor that is executed when it hits something, so this shouldn't be super complicated.

It seems that there is need for player position variable, so we've decided to add the.
