### ISSUE TITLE
learning example using theano and lasagne eats up 32 GB of memory in first training epoch

### ISSUE THREAD

**Issue by imrodriguezro** [mwydmuch/ViZDoom#133]
Hi!

I'm running the example learning.py in windows 10 x64 but it ends all my memory,32 GB, around the 70% of training in the first epoch even when lowering the resolution to 320x240. I have a gpu but I couldn't make it work with theano, so it's using only cpu. You know what could go wrong there?

Thanks!

**Comment by wjaskowski** [comment]
What theano and lasagne version do you use?

**Comment by imrodriguezro** [comment]
Thanks for your quick answer.

Theano                    0.9.0.dev4
Lasagne                   0.2.dev1

**Comment by wjaskowski** [comment]
Try maybe less bleeding-edge versions. I doubt this is related do ViZDoom.

**Comment by ebonyclock** [comment]
Which release of ViZDoom are you using?

**Comment by imrodriguezro** [comment]
I'm using the last win binaries
[1.1.0pre](https://github.com/Marqt/ViZDoom/releases/download/1.1.0pre-CIG2016-warm-up-fixed/ViZDoom-1.1.0pre-CIG2016-Win-x86_64.zip)

**Comment by imrodriguezro** [comment]
I'll check then with other lasagne/theano versions, and I'll let you know about results.
Thanks!
