### ISSUE TITLE
no more than 255 labels

### ISSUE THREAD

**Issue by glample** [mwydmuch/ViZDoom#134]
Hi,

I just had a look at the labels feature, with labels_buffer and the associated labels, but it looks like there can't be more than 255 labelled objects at the same time. Is it a bug, or a constraint of the engine?

**Comment by glample** [comment]
Also, if I understood correctly, there are 3 objects associated to a label:
'object_id', 'object_name', 'value'

The value is the ID of a specific object in the buffer, the name is what it is, but what does object_id correspond to? It's not a relevant value is it?

**Comment by Marqt** [comment]
Design decision, 255 seems enough for me - that number of objects will definitely fill the entire screen and in the case of more visible objects, what is unlikely, the nearest objects will be selected.
Can be easily extended if really needed. 

`object_id` - identifies an instance of an object. Between frames same objects may have different labels, but this id is constant and unique for each object on the current map.

**Comment by glample** [comment]
I see, thanks. Yes 255 should be enough. So the object_id is initialized when an object is created and remains constant and unique until it's destroyed?

**Comment by Marqt** [comment]
Something like that, ID is assigned when object is seen for the first time (so object with lower id was seen before object with higher - this may also be useful in some way).
