### ISSUE TITLE
incorrect labels

### ISSUE THREAD

**Issue by glample** [mwydmuch/ViZDoom#135]
I noticed that on some maps (not on all of them, but on some like the deathmatch.wad one, or map2 in cig.wad like on the screenshot below) some walls are defined as labels, like this:

![image](https://cloud.githubusercontent.com/assets/8885556/20229467/db8ed88a-a856-11e6-90d9-02ca57908c9c.png)

It seems to happen when an object is behind a wall, and the entire wall becomes labeled as the object. This seems to be coming from a bad construction of the map, typically on map01 the problem is never there. Any idea of what in the .wad file and the wall properties can generate these issues? I tried to modify some wall properties, but without success.

Thank you

**Comment by Marqt** [comment]
I have no idea. I tested labels buffer on few Doom's singleplayer levels and I haven't seen this kind of bug.

**Comment by int3ll3ct** [comment]
I have this same issue where I set up to play cig.wad for 2-player using a derivative of multiple_instances.py.  Sometimes the stationary opponent is "visible" through 2 walls, as his label shows up if I gaze in his general direction.  See attached.  I reproduce the issue readily with this.
[mi_xrayvision.py.txt](https://github.com/Marqt/ViZDoom/files/630256/mi_xrayvision.py.txt)

**Comment by mwydmuch** [comment]
The latest improvements in the labels buffer should prevent this type of errors.
