### ISSUE TITLE
Cmake doesn't find libboost_python when boost is installed from sources

### ISSUE THREAD

**Issue by mihahauke** [mwydmuch/ViZDoom#142]
default boost's path: /usr/lib/x86_64-linux-gnu/libboost_python-py35.so.1.58.0
path for boost when installed from source: libboost_python3.so.1.62.0 => /usr/local/lib/libboost_python3.so.1.62.0 

After successful nstallation it can have some problems anyway: 
 ImportError: /usr/local/lib/libboost_python.so.1.62.0: undefined symbol: PyUnicode_AsUTF8String

**Comment by hzheng2015** [comment]
Hi ebonyclock,

I got this error when I try to import caffe in Python. How do you solve it?

**Comment by ebonyclock** [comment]
As you can see the issue is still hanging so don't have a nice solution but setting paths by hand in cmake should help. Uninstalling and installing again could also help - perhaps your caffe installation was compiled against old boost?

**Comment by nadiagit** [comment]
Hi hzheng2015,

I have the same error when I am trying to import caffe in Python. Have you found something that works? 
Thank you.

**Comment by mwydmuch** [comment]
Boost.Python is no longer needed.
