### ISSUE TITLE
fullscreen mode

### ISSUE THREAD

**Issue by jesc2** [mwydmuch/ViZDoom#148]
Is it possible to run in fullscreen rather than window mode?

**Comment by Marqt** [comment]
Yes, `add_game_args("+fullscreen 1")` will force fullscreen mode.

**Comment by jesc2** [comment]
Great thanks! How about for multiple screens for multiplayer games? Would there be a way to have each player fullscreen on a separate monitor? i.e. can the screen coordinates for each player be set?

**Comment by wjaskowski** [comment]
You might want to try https://zdoom.org/wiki/CVARs:Display#vid_adapter.
This is a ZDoom question.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski
