### ISSUE TITLE
spawning monsters

### ISSUE THREAD

**Issue by jesc2** [mwydmuch/ViZDoom#162]
Is there a way to spawn monsters on the fly, or to control when monsters enter the game?

**Comment by Marqt** [comment]
It is possible to call ACS script that is available on current map using `send_command("puke ACS_script_id <optional_arg1> <optional_arg2> <optional_arg3>")` or `send_command("pukename ACS_script_name ...")`.

So first you need to prepare a script for the scenario that will spawn monsters.
