### ISSUE TITLE
X Window System error using Ubuntu 14.04

### ISSUE THREAD

**Issue by zihao-fan** [mwydmuch/ViZDoom#164]
Hi, I'm using ssh -X to a Ubuntu 14.04 server from my Mac OS 10.12 client, when I tried to run /examples/python/basic.py on my server, it gives me this error:

The program 'vizdoom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 76 error_code 2 request_code 149 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Traceback (most recent call last):
  File "basic.py", line 90, in <module>
    game.init()
vizdoom.vizdoom.ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.

any idea how to fix this? Thx a lot!

**Comment by Marqt** [comment]
No idea at the moment. I can't replicate the problem.
Could you add `game.set_console_enabled(True)` before `game.init()`? This will give additional information to what is happening during the initialization.

**Comment by mwydmuch** [comment]
Old issue. Closing.
