### ISSUE TITLE
Randomness in ACS scripts

### ISSUE THREAD

**Issue by imrodriguezro** [mwydmuch/ViZDoom#170]
I've noticed that the function 'random' in acs scripts works poorly, since the numbers obtained have kind of a scheme and generally one number repeats many times more than the others.

Do you guys know if there's a way to use a 'better' random number generator?

Coming from ZDOOM I don't see any hope. No C++ functions can be imported or so.
I could imagine however, that somehow one can set a variable in the acs script, directly from vizdoom. Something like, game.set_game_variable(USER1). Would it be possible? Do you see any workaround?

Thanks in advance!

**Comment by Marqt** [comment]
ZDoom uses Mersenne Twister rng, so it should be 'random' enough for most cases. However you can replace it by editing `src/vizdoom/src/m_random.cpp`.

And possibility to set GameVariables seems like a good idea, I will add it. Thanks!

**Comment by imrodriguezro** [comment]
Oh, now I see what it's being used. However, I do have a very bad distribution. Is there any other way of using the rng in the script? 

Let's take for example the deathmatch.wad scenario. Without any change, there I get a start position for the player which keeps repeating many more times than other "random" ones (let's say for 200 times I call the function, I get 130 times this position).

Does it happen for you as well? could be that it only happens in the ENTER script?

Thanks again!

**Comment by wjaskowski** [comment]
We had a similar problem a while ago. It was due to a bug in a scenario.
Michal (CC) known better what has been wrong there.

**Comment by imrodriguezro** [comment]
So, how did you solve the problem? I've been trying many things but none of them successful.
And the only info I found [http://forums.zdaemon.org/viewtopic.php?t=15775](url)  is also not encouraging.
Thanks!

**Comment by ebonyclock** [comment]
@imrodriguezro Sorry for the delay. I have tested this on deathmatch.wad and I get  uniform randomness except for point (40,980) which is the default start point and all unsuccessful player teleports end up there. I corrected the file ( a6dc46c68f2866c2a22fa0231d0335046dd2b5ac )  so now all spawns should be uniformly random.

**Comment by imrodriguezro** [comment]
I keep getting that point which repeats many times. It might be that I'm not using the latest version of vizdoom (since I just took the latest python binaries).

Anyway, I've come up with a workaround: This point doesn't change unless the map changes, so after I start an episode I just query from vizdoom what point it generated and if it is that point, I restart a game (game.new_episode) until another point is selected. In that way, all other spots will be assigned uniformly.

**Comment by ebonyclock** [comment]
The newest version of deathmatch.wad should work ok. Could you check if it works for you without the workaround?

**Comment by imrodriguezro** [comment]
Yes, it doesn't work.

**Comment by ebonyclock** [comment]
Could you provide a script that reproduces it?

**Comment by imrodriguezro** [comment]
I just saw that you guys did a recent change related to the rng seed. Could it be related to this problem?

**Comment by imrodriguezro** [comment]
Sure:
[repro.zip](https://github.com/Marqt/ViZDoom/files/736827/repro.zip)

That's another scenario, but the behaviour is the same.
Thanks!

**Comment by ebonyclock** [comment]
I still cannot reproduce it even after checking out before this commit (using your test.py) ebc29a82d1c9daedd0f96b2d960eb7b72f6a446a. 
![rng_histograms](https://cloud.githubusercontent.com/assets/2771069/22396088/d5dc8040-e550-11e6-834b-0da6ac85ba12.png)

**Comment by imrodriguezro** [comment]
Could you please check with the last released binaries? I get specifically for this scenario most of the time the number 94.

**Comment by ebonyclock** [comment]
Released binaries you say ... are you using Windows then?

**Comment by imrodriguezro** [comment]
yes, I'm using windows

**Comment by Miffyli** [comment]
I am getting following on Windows 10 with the current pre-compiled binaries (tested python 2.7 and 3.5 with same results) using the provided test.py (only modified to gather samples and plot them):

![0218154959](https://cloud.githubusercontent.com/assets/1633800/23093656/016cae0e-f5f2-11e6-911a-52ae628e1beb.png)

**Comment by wjaskowski** [comment]
https://github.com/mwydmuch/ViZDoom/commit/ebc29a82d1c9daedd0f96b2d960eb7b72f6a446a

**Comment by ebonyclock** [comment]
It doesn't look like this issue is connected to this commit. @Miffyli and I tried to replicate it on Linux without these changes and it works ok. It seems more like a windows specific issue after all.

**Comment by imrodriguezro** [comment]
@Miffyli Could you please share what number is the one standing out in the plot?

**Comment by wjaskowski** [comment]
My commit also fixed an issue that happened only on Windows (or at least it
was found on Windows).

**Comment by Miffyli** [comment]
@imrodriguezro It was 94 

@wjaskowski Ah yes, good to hear. I don't have build environment set up so I haven't been able to try that one out.
