### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by coderking7** [mwydmuch/ViZDoom#178]
```
Command "/home/sharath/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-EHp_Kc-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-WLQSL8-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-EHp_Kc-build/
```
I am using python2.7 and all dependencies are installed.
The command was "pip install -e ."

**Comment by ebonyclock** [comment]
Does it also fail without without "-e".
Could you share more verbose error log?

**Comment by coderking7** [comment]
`/tmp/pip-g5vGbN-build/src/vizdoom/src/viz_main.cpp: In function ‘void VIZ_PrintFuncMsg(const char*, const char*)’:
    /tmp/pip-g5vGbN-build/src/vizdoom/src/viz_main.cpp:443:23: warning: NULL used in arithmetic [-Wpointer-arith]
         while (func[s] != NULL && func[s] != ' ') ++s;
                           ^
    /tmp/pip-g5vGbN-build/src/vizdoom/src/viz_main.cpp:445:23: warning: NULL used in arithmetic [-Wpointer-arith]
         while (func[e] != NULL && func[e] != '(') ++e;
                           ^
    [100%] Linking CXX executable ../../../bin/vizdoom
    CMakeFiles/vizdoom.dir/tempfiles.cpp.o: In function `FTempFileName::FTempFileName(char const*)':
    tempfiles.cpp:(.text+0x7): warning: the use of `tempnam' is dangerous, better use `mkstemp'
    [100%] Built target vizdoom
    Makefile:83: recipe for target 'all' failed
    make: *** [all] Error 2
    
    Installation failed, you may be missing some dependencies.
    Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-g5vGbN-build/setup.py", line 92, in <module>
        keywords=['vizdoom', 'doom', 'ai', 'deep learning', 'reinforcement learning', 'research']
      File "/home/sharath/anaconda2/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/sharath/anaconda2/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/sharath/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/sharath/anaconda2/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/sharath/anaconda2/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/home/sharath/anaconda2/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/sharath/anaconda2/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/tmp/pip-g5vGbN-build/setup.py", line 47, in run
        subprocess.check_call(['make', '-j', str(cpu_cores)])
      File "/home/sharath/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j', '3']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/home/sharath/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/I/pip-g5vGbN-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Q5kejk-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-g5vGbN-build/`

It shows that I might have missed some dependencies but I ran all the commands mentioned sucessfully.

**Comment by mwydmuch** [comment]
Hello @coderking7
You may want to try to build ViZDoom manually using CMake command similar to this:

```
cmake -DCMAKE_BUILD_TYPE=Release \
-DBUILD_PYTHON=ON \
-DPYTHON_INCLUDE_DIR=/home/sharath/anaconda2/include/python2.7 \
-DPYTHON_LIBRARY=/home/sharath/anaconda2/lib/libpython2.7.so \
-DPYTHON_EXECUTABLE=/home/sharath/anaconda2//bin/python2 \
-DNUMPY_INCLUDES=/home/sharath/anaconda2/lib/python2.7/site-packages/numpy/core/include
```
 And then copy `vizdoom_root_dir/bin/python2/pip_package` to `/home/sharath/anaconda2/lib/python2.7/site-packages/vizdoom`.

**Comment by coderking7** [comment]
`-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   date_time
--   chrono
--   regex
--   iostreams
--   atomic
-- Could NOT find GME (missing:  GME_INCLUDE_DIR) 
-- Using system zlib
-- Using system jpeg library
-- Using system bzip2 library
-- Using internal gme library
-- /home/sharath/anaconda2/include
-- /usr/include
-- /home/sharath/ViZDoom/src/vizdoom/lzma/C
-- Could not find FMOD include files
-- Selected assembler: /usr/bin/as
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   date_time
--   chrono
--   atomic
-- Fluid synth libs: /usr/lib/x86_64-linux-gnu/libfluidsynth.so
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   python
-- Found components for NumPy
-- NUMPY_ROOT_DIR    = /usr/local
-- NUMPY_INCLUDES    = /home/sharath/anaconda2/lib/python2.7/site-packages/numpy/core/include
-- NUMPY_LIBRARIES   = 
-- NUMPY_API_VERSION = 1.11.3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sharath/ViZDoom
`
Above is the ouput of first command. The /home/sharath/ViZDoom/bin/python2/ directory was empty.

**Comment by mwydmuch** [comment]
It looks like you forgot to eventually build it. The whole process should consist these commands:

```
rm CMakeCache.txt
cmake (with mentioned arguments)
make -j 4
cp /home/sharath/ViZDoom/bin/python2/pip_package /home/sharath/anaconda2/lib/python2.7/site-packages/vizdoom
```

**Comment by coderking7** [comment]
Thank you so much it works . cp command must be run with -r option.

**Comment by mwydmuch** [comment]
Oh, definitely! I'm glad it works.
