### ISSUE TITLE
"vizdoom.vizdoom.ViZDoomErrorException: Buffers size mismatch" 

### ISSUE THREAD

**Issue by Kingseso** [mwydmuch/ViZDoom#179]
Hello,

I have been working with Vizdoom 1.1.0 (compiled Windows binary) on my Intel i7 core laptop running Windows 7 64-bit with Python 3.5.3 64-bit.  I had no issues running the examples.  I wanted to try a faster machine, so installed the Python 3.5.3 64-bit, along with Vizdoom 1.1.0 (compiled Windows binary) on my Windows 7-64 bit machine with a Intel Xeon CPU E5-2620 v3 @ 2.40GHz with 64GB of RAM.

I tried the basic.py example along with the other examples and I keep getting the following error:

D:\Users\Cecil\Programs\Python\Python35\python.exe D:/Users/Cecil/PycharmProjects/experiment_vizdoom/code/basic.py
Traceback (most recent call last):
  File "D:/Users/Cecil/PycharmProjects/experiment_vizdoom/code/basic.py", line 91, in <module>
    game.init()
vizdoom.vizdoom.ViZDoomErrorException: Buffers size mismatch.

Has anyone come across this issue? 

Regards,

Cecil

**Comment by ebonyclock** [comment]
Does the Xeon machine run with gui (I don't even know if windows can run without it...)?

**Comment by Kingseso** [comment]
Yes.  A Xeon machine running Windows is no different than any other Intel Windows based machine in terms of the graphical interface.

**Comment by mwydmuch** [comment]
Hello @Kingseso,
dose vizdoom.exe itself run correctly?
When running vizdoom.exe under library control, the console window (which shows up before the game start) should print something like this: 
```
VIZ_ScreenInit: width: 640, height: 480, pitch: 640, format: CRCGCB
Resolution: 640 x 480
```
Are the values match in your case?

**Comment by Kingseso** [comment]
Hello,

The vizdoom.exe does run correctly by itself.  Under library control, both my computers (the Intel i7 and Xeon machine) shows the following:

![image](https://cloud.githubusercontent.com/assets/8533605/24427040/9f7f6f52-13d7-11e7-8767-8d6176f9c82b.png)

There is nothing showing the message you stated above.

Regards,

Cecil

**Comment by Kingseso** [comment]
Hello mwydmuch,

I solved the problem.  The one note I did not mention because I didn't believe it was relevant (I was wrong) was I was doing a remote desktop into the Xeon machine from my laptop.  I believe the remote desktop connection interferes with the screen buffer generated by Vizdoom.  Everything runs fine now when I run basic.py or any other example on the Xeon machine without remote desktop.

Thanks for your help.

Regards.

Cecil

**Comment by mwydmuch** [comment]
I'm glad you solved the problem, forgive that we weren't very helpful (we have little knowledge about things related to Windows, like this one).

**Comment by dabana** [comment]
I get the same problem running VizDoom remotely on a headless (no screen) computer over Jupyter Notebook. At first I thought it was the remote Desktop instance that was interfering with VizDoom like Kingseso proposed, but I am pretty sure it has to do with the fact that I don't have a screen plug on the computer. Investigations going on ...

**Comment by dabana** [comment]
Okai I have set up my Jupyter Notebook Server to automatically start when Windows boots up and I rebooted my computer and now it works. So Kingseso was write. I believe it has to do with the remote desktop changing some stuff in the screen buffer settings. These changes seem to be reverted back to normal when the computed is rebooted.

**Comment by wingless75** [comment]
You can run vizdoom with the remote desktop.
Just check all available resolutions.
I can run vizdoom with RES_1280X800, RES_640X400.
[resolutions](https://github.com/Farama-Foundation/ViZDoom/blob/master/doc/Types.md#screenresolution)
