### ISSUE TITLE
Message Queue Exception

### ISSUE THREAD

**Issue by jbwebb8** [mwydmuch/ViZDoom#180]
Newbie here, so this may be a silly beginner's mistake on my part. I've installed and compiled vizdoom on my mac (OS X 10.11). I can run vizdoom.app without any problems, but when I try to run any of the python examples (e.g. basic.py), I get the following error:

```
Traceback (most recent call last):
  File "basic.py", line 91, in <module>
    game.init()
vizdoom.vizdoom.MessageQueueException: Failed to create message queues.
```

Any ideas what may be causing this? Thanks!

**Comment by ebonyclock** [comment]
Could you give exact commands which you executed to reach this result?

**Comment by jbwebb8** [comment]
james-webbs-macbook-pro:ViZDoom jameswebb$ cd examples/python
james-webbs-macbook-pro:python jameswebb$ python basic.py
Traceback (most recent call last):
  File "basic.py", line 91, in <module>
    game.init()
vizdoom.vizdoom.MessageQueueException: Failed to create message queues.

**Comment by mwydmuch** [comment]
Hello @jbwebb8,
I've expanded the messages for MessageQueueExceptions. Could you please pull, rebuild and check new error message?

**Comment by jbwebb8** [comment]
Sure thing! After doing that I get the same message:

james-webbs-macbook-pro:python jameswebb$ python basic.py
Traceback (most recent call last):
  File "basic.py", line 91, in <module>
    game.init()
vizdoom.vizdoom.MessageQueueException: Failed to create message queues.

**Comment by mwydmuch** [comment]
Hmm, it looks like you are still using an older version. In the current master version the message should look like this:
`Failed to create message queues: <some more details from lower level exceptions>.` or in worst case scenerio `Failed to create message queues for unknown reason`.

**Comment by jbwebb8** [comment]
Ah sorry, I did not pip uninstall and reinstall. Now I get this:

james-webbs-macbook-pro:python jameswebb$ python basic.py
Traceback (most recent call last):
  File "basic.py", line 91, in <module>
    game.init()
vizdoom.vizdoom.MessageQueueException: Failed to create message queues: Permission denied

**Comment by jbwebb8** [comment]
Fixed it! Thanks to your modified error message. I changed the permissions of the shared directory (/private/tmp/boost_interprocess) that boost interprocess was attempting to access with `sudo chmod 777 /private/tmp/boost_interprocess`. Thanks for your help!

**Comment by mwydmuch** [comment]
Nice, I'm glad that you managed to solve this.
