### ISSUE TITLE
Fail to install on Mac OS with anaconda python3 environment

### ISSUE THREAD

**Issue by zihao-fan** [mwydmuch/ViZDoom#181]
Hi, I've already done some developing on my linux desktop using ViZDoom. Thanks for your awesome project. I'm trying to switch to Mac OS to continue, however, I failed to install it. I am using a anaconda python3 environment. The error info is as follows. Seems like it cannot find some dependencies when using anaconda python.

`[ 99%] Built target pk3
    Scanning dependencies of target libvizdoom_python3
    make[2]: *** No rule to make target `/Users/zihao/anaconda/lib/python3.6/config-3.6m-darwin/libpython3.6.dylib', needed by `bin/python3/vizdoom.so'.  Stop.
    make[2]: *** Waiting for unfinished jobs....
    [100%] Building CXX object CMakeFiles/libvizdoom_python3.dir/src/lib_python/ViZDoomGamePython.cpp.o
    [100%] Building CXX object CMakeFiles/libvizdoom_python3.dir/src/lib_python/ViZDoomPythonModule.cpp.o
    /private/var/folders/9s/0l__tvbs2zn4gxtkdk8szfz00000gn/T/pip-70pj1u5u-build/src/lib_python/ViZDoomPythonModule.cpp:99:1: warning: control may reach end of non-void function [-Wreturn-type]
    }
    ^
    /private/var/folders/9s/0l__tvbs2zn4gxtkdk8szfz00000gn/T/pip-70pj1u5u-build/src/lib_python/ViZDoomGamePython.cpp:38:5: warning: control may reach end of non-void function [-Wreturn-type]
        }
        ^
    1 warning generated.
    1 warning generated.
    make[1]: *** [CMakeFiles/libvizdoom_python3.dir/all] Error 2
    make: *** [all] Error 2`

Thanks.

**Comment by ebonyclock** [comment]
Did you use anaconda on linux too?

**Comment by zihao-fan** [comment]
No. I used Python that comes with Ubuntu 16.04 system before. Never tried install ViZDoom in anaconda environment.

**Comment by ebonyclock** [comment]
I tried to install it on anaconda (ubuntu) and I think I had the exact same error message so it might be a problem with installing specifically on anaconda not on mac. Until we handle this if you want a workaround - it should work on python installed via homebrew.

**Comment by zihao-fan** [comment]
Thanks for your response. I got a working environment for ViZDoom for now so it's not a big problem. Good luck on making it working on anaconda.

**Comment by mwydmuch** [comment]
I believe cmake needs little guidance in this case:

```
cmake -DCMAKE_BUILD_TYPE=Release \
-DBUILD_PYTHON3=ON \
-DPYTHON_INCLUDE_DIR=/.../anaconda3/include/python3.6m \
-DPYTHON_LIBRARY=/.../anaconda3/lib/libpython3.6m.dylib \
-DPYTHON_EXECUTABLE=/.../anaconda3/bin/python3 \
-DBOOST_PYTHON3_LIBRARY=/.../libboost_python-py36.dylib \
-DNUMPY_INCLUDES=/.../anaconda3/lib/python3.6/site-packages/numpy/core/include
```

A similar command allowed me to build against anaconda 2.7 and anaconda 3.5 on Ubuntu and Windows some time ago. Should also work on osx.

**Comment by ebonyclock** [comment]
It should be handled by pip so I guess setup.py requires an upgrade.

**Comment by zihao-fan** [comment]
@mwydmuch Hi, thanks for your suggestions. I have successfully build the libraries adding the parameters you mentioned. Hope it could be handled by pip soon.

**Comment by desimone** [comment]
For future readers... #193

**Comment by AayushGrover** [comment]
I tried using pip to get Vizddom:

Collecting vizdoom
  Downloading https://files.pythonhosted.org/packages/5f/da/9f60fad9c4f77d86e7f38cf16fa63c28d814c3d9ff80028a8bd3ca19f564/vizdoom-1.1.6.tar.gz (10.0MB)
    100% |████████████████████████████████| 10.0MB 156kB/s 
Requirement already satisfied (use --upgrade to upgrade): numpy in /home/aayush/.local/lib/python3.5/site-packages (from vizdoom)
Installing collected packages: vizdoom
  Running setup.py install for vizdoom ... done
Successfully installed vizdoom-1.1.6


Even after this, I'm getting the following error:
Traceback (most recent call last):
  File "a3c_main.py", line 1, in <module>
    import vizdoom
ModuleNotFoundError: No module named 'vizdoom'
