### ISSUE TITLE
 X Window System error in linux

### ISSUE THREAD

**Issue by shujon** [mwydmuch/ViZDoom#185]
Hi
I am getting following error after running ../../bin/vizdoom -nomusic -iwad ../../scenarios/freedoom2.wad

ViZDoom 1.1.1 (ZDOOM 2.8.1) - SDL version
Compiled on Apr  3 2017

M_LoadDefaults: Load system defaults.
Gameinfo scan took 0 ms
W_Init: Init WADfiles.
 adding /share/jproject/fg508/naha/ViZDoom/bin/vizdoom.pk3, 583 lumps
 adding freedoom2.wad, 3595 lumps
I_Init: Setting up machine state.
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
  Family 6, Model 63, Stepping 2
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
V_Init: allocate screen.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
Adding dehacked patch freedoom2.wad:DEHACKED
Patch installed
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading default status bar definition.
ParseSBarInfo: Loading custom status bar definition.
===========================================================================
This is Freedoom, the free content first person shooter.

Freedoom is freely redistributable under the terms of the modified BSD
license. Check out the Freedoom website for more information:

    https://freedoom.github.io/
============================================================================
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)

(vizdoom:4892): Gdk-ERROR **: The program 'vizdoom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 78 error_code 2 request_code 154 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap

Also basic.py is giving segmentation fault at game.init(). Can you please help me to fix the problem?

**Comment by wjaskowski** [comment]
ViZDoom is based on ZDoom. This error seems to concern ZDoom. So check first whether ZDoom works. If not ask for help on forum.zdoom.org.
