### ISSUE TITLE
game.init() giving segmentation fault for pip install

### ISSUE THREAD

**Issue by shujon** [mwydmuch/ViZDoom#186]
I installed vizdoom using pip but for all the example files, the game.init() is giving segmentation fault.

**Comment by wjaskowski** [comment]
Provide us more details. OS. Python version etc.

**Comment by shujon** [comment]
Hi
It is a linux (CentOS) system and I am using python 2.7.

**Comment by wjaskowski** [comment]
Could you find "vizdoom" file on your system, go to its directory and try
to execute it?

**Comment by shujon** [comment]
This is the output I got

 cd  /N/u/shujon/.local/lib/python2.7/site-packages/vizdoom/
 ls
bots.cfg  freedoom2.wad  __init__.py  __init__.pyc  scenarios  vizdoom  vizdoom.pk3  vizdoom.so
 ./vizdoom
ViZDoom 1.1.1 (ZDOOM 2.8.1) - SDL version
Compiled on Apr  3 2017

M_LoadDefaults: Load system defaults.
Gameinfo scan took 0 ms
W_Init: Init WADfiles.
 adding /N/u/shujon/.local/lib/python2.7/site-packages/vizdoom/vizdoom.pk3, 583 lumps
 adding ./freedoom2.wad, 3329 lumps
I_Init: Setting up machine state.
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
  Family 6, Model 63, Stepping 2
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
V_Init: allocate screen.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
Adding dehacked patch freedoom2.wad:DEHACKED
Patch installed
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading default status bar definition.
ParseSBarInfo: Loading custom status bar definition.
===========================================================================
This is Freedoom, the free content first person shooter.

Freedoom is freely redistributable under the terms of the modified BSD
license. Check out the Freedoom website for more information:

    https://freedoom.github.io/
============================================================================
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)

(vizdoom:15071): Gdk-ERROR **: The program 'vizdoom' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 78 error_code 2 request_code 154 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap

**Comment by wjaskowski** [comment]
Thus, this is a problem with ZDoom on which ViZDoom is based. Therefore,
you should first check the vanilla ZDoom (zdoom.org) and then if it still
does not work ask for help at https://forum.zdoom.org/

**Comment by shujon** [comment]
Thanks, let me try ZDoom first then.

**Comment by mwydmuch** [comment]
Old issue, probably ZDoom related problem. Closing.
