### ISSUE TITLE
during training, how to always pick up items (medikit, ammo, armo) when inventory is full? 

### ISSUE THREAD

**Issue by pengsun** [mwydmuch/ViZDoom#187]
Hi,
As this video shows, the player can always pick up meditkits and ammos
https://www.youtube.com/watch?v=W0mI_c2LjJM

But I found the player cannot pick up any item when the inventory (hp or ammo) is full. Could you suggest on how to manage this? (In health_gather.wad the player periodically loses health by setting the floor's callback function, but how to do similar things for ammo? or even armor?)

**Comment by mwydmuch** [comment]
Hello @pengsun,
CVARs implemented in ZDoom engine are very helpful in quickly modifying some aspects of the game:
https://zdoom.org/wiki/CVARs:Configuration

In this case game.add_game_args("+sv_unlimited_pickup 1") should do the trick.

**Comment by pengsun** [comment]
Wow, thanks for pointing out this! Will try it out!
