### ISSUE TITLE
Adding teams capability and altering rewards for killing

### ISSUE THREAD

**Issue by IanQS** [mwydmuch/ViZDoom#188]
1) Has anyone implemented teams? Was thinking of training 2 teams of 2 RL agents to battle. Or even just a team of 2 agents fighting against a single bot

2) Setting rewards for killing. In the README for the scenarios (basic.cfg), it mentions that you get 101 points for killing a monster but it doesn't set it anywhere in basic.cfg. Opening up game= Doomgame() I don't see any option to set it even though it's possible to set living rewards and death penalties there

This is in Python btw

**Comment by wjaskowski** [comment]
The rewards are defined in wad files. You need to open them with Slade or
Doom Builder (http://vizdoom.cs.put.edu.pl/#scenarios)


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by IanQS** [comment]
Ahh okay. I must have missed them in the documentation. I'm gonna submit a pull request some time tomorrow updating the documentation for examples (the .md is messed up) and I'll include that in the scenario docs so you don't get this question again (assuming you don't mind)

**Comment by mwydmuch** [comment]
All contributions are welcome :)
