### ISSUE TITLE
How to use binaries for Windows

### ISSUE THREAD

**Issue by zappybiby** [mwydmuch/ViZDoom#190]
OK guys, I have spent a couple days going over things and trying to figure this out. But I have to ask the dumb question: What do I do with the precompiled binaries for Windows? I cant run basic.py because module vizdoom is missing (obviously). And the only way to get it to compile with that is if I either use pip, which isn't on Windows, or build on Windows which would actually really suck.

I must really be lost, because it seems no one else has asked this before. I feel like I'm missing something really obvious but none of the documentation is helping me here.

**Comment by mwydmuch** [comment]
Hello @zappybiby,
you are right that it isn't directly written anywhere, but `vizdoom` dir inside zip with Windows binaries is just ready Python package, so you can simply copy it into `python_root\Lib\site-packges` or directly into your project dir.

**Comment by zappybiby** [comment]
Thank you so much! Got it working great now.

**Comment by mwydmuch** [comment]
That's good to hear!
