### ISSUE TITLE
[Question] User Variables

### ISSUE THREAD

**Issue by zappybiby** [mwydmuch/ViZDoom#191]
Hello, 

I can't find any documentation on the user variables like the one used in the example on your website:

"It is also possible to access user variables (USER1, USER2 ... USER32), which correspond to ACS scripts' global variables 1-32." 
Such as when used in `game.get_game_variable(GameVariable.USER1)`

I've tried looking at ACS documentation on ZDoom and Doom wikis, but I cannot find and reference to these global variables. Is there a list somewhere of these variables?

I am asking because I want to make the agent lose reward whenever it uses ammo so it learns to conserve it.

**Comment by zappybiby** [comment]
Oh sorry, I found information in https://github.com/mwydmuch/ViZDoom/blob/master/doc/Types.md

But I'm not sure what variable goes with each user variable (E.g. USER1 is related to health)...

**Comment by wjaskowski** [comment]
You want to use those variables only if you create a new scenario (a wad
file) and wan't to put there some special values (like x,y of the bot). If
you don't modify scenarios then simply ignore them.


--
Wojciech Jaśkowski, Ph.D.
Laboratory of Intelligent Decision Support Systems
Institute of Computing Science
Poznan University of Technology, Poland
http://www.cs.put.poznan.pl/wjaskowski

**Comment by zappybiby** [comment]
Ok, I figured out what I need to use!

get_game_variable will allow me to do shaping to help the agent learn.

**Comment by biggzlar** [comment]
This issue is not exactly solved. There is still no documentation on which variable does what and "You won't need this if you don't want to create scenarios (...)" is not helpful at all.

**Comment by mihahauke** [comment]
@biggzlar 
Is [this](https://github.com/mwydmuch/ViZDoom/blob/master/doc/Types.md#gamevariable) satisfactory?

**Comment by mihahauke** [comment]
Weeeelll.... USERX normally gives nothing (zeros or random perhaps?) but if you create acs script in the wad and set global variable 0 then USERX will give what is in global variable X

**Comment by biggzlar** [comment]
I'm not sure I understand this. Say I put `USER1` into my game variables (in the .cfg) - this will return nothing if I haven't specified it in the .wad? Why would anyone use this instead of the named variables if they are passing only game related variables?

**Comment by mihahauke** [comment]
Cause you can put something custom there like some kind of auxiliary reward or something that needs computation inside the scenario itself - e.g. number of collected items of specific kind.

**Comment by biggzlar** [comment]
I see. Thanks for the patient Q&A. Without some knowledge of ACS, this is kind of opaque and not well drawn out in the docs I feel.

**Comment by Miffyli** [comment]
Let me pitch in here and tell you a short story.

Once upon a time I wished to get the position and velocity of the player so I can teach my young agent to travel as fast as possible. Alas, ViZDoom did not have capability to provide these (`POSITION_X` and `POSITION_Y` did not exist back then). Thankfully ViZDoom did know of `USER#` variables!

Thus I directed my adventures towards .wad files and their ACS scripts. Brief tinkering later I had the following in the map's `SCRIPT` entry:

```
global int 1:x_pos;
global int 2:y_pos;

script 2 ENTER
{
    while(1)
    {
        delay(1);
        x_pos = GetActorX(0);
        y_pos = GetActorY(0);
    } 
}
```

I compiled the ACS code, saved the scenario and returned back to my cozy, albeit messy, Python code using ViZDoom:

```python

x = doom_fixed_to_double(doomgame.get_game_variable(GameVariable.USER1))
y = doom_fixed_to_double(doomgame.get_game_variable(GameVariable.USER2))
```

And there was I, `x` and `y` containing exactly what I wanted: The X and Y coordinate of the player, originally fetched in the ACS code with the call `GetActorX(0)`. 

Of course this specific workaround is not required anymore with the existence of `POSITION_X` and similar GameVariables. However somebody somewhere could someday require something that is only accessible through ACS functions, and using `USER#` variables is only way to obtain them as far I am aware.

**Comment by biggzlar** [comment]
One more thing: why can't I pull `USER0` like this:

```
game.get_game_variable(vzd.GameVariable.USER0)
```

The docs say it's reserved for reward. But if for example in the `basic.wad` I add a +300 reward when the monster is killed, this reward does not seem to be incorporated in the `game.make_action(action)`. Is this a known issue or somehow related to the fact that the game closes in the same ACS function call?

**Comment by Miffyli** [comment]
@biggzlar 

Can you share the ACS code and the Python code? Hard to say what could be wrong. The +300 reward should be visible in `reward = game.make_action(action)`, even if it is the terminal/final state.

**Comment by biggzlar** [comment]
Thanks for the quick reply. First the relevant ACS code:

```acs
script 4 (void)
{
    reward = reward + 300.0;
    Exit_Normal(0);

}

function void SpawnTarget(void)
{

    int y = Random(-161.0,224.0);
    Spawn("Cacodemon", 0.0, y,0.0,target_id,128);
    //disables movement
    SetActorProperty(target_id, APROP_Speed, 0);
    //makes it die on one hit
    SetActorProperty(target_id, APROP_Health, 1);
    //makes it ignore the player and attack actor with tid 100
    Thing_Hate (target_id, 100, 6);
    SetThingSpecial(target_id, ACS_ExecuteAlways, 4);
   
}
```
And the Python section:
```python
game.new_episode()

while not game.is_episode_finished():
	full_state = game.get_state()
	state = self.resize(full_state.screen_buffer)
	
	# Run State Through Policy & Calculate Action
	feed = {self.X: state.reshape(1, 84, 84, 1)}
	action = sess.run(self.action, feed_dict=feed)
	action = action[0][0]

	reward = game.make_action(env_actions[action])
	
	# Store Results
	states.append(state)
	rewards.append(reward)
	actions.append(action)
```

**Comment by mihahauke** [comment]
@biggzlar Have you compiled the script?

**Comment by biggzlar** [comment]
That did it, thanks again for the support. Is it possible that doom builder 2 handles compilation automatically while Slade doesn't?

**Comment by mihahauke** [comment]
@biggzlar Quite possibly. Haven't used doom builder for a while but slade doesn't compile automatically for sure (at least not by default)
