### ISSUE TITLE
Encoding method of the depth buffer

### ISSUE THREAD

**Issue by XinkeAE** [mwydmuch/ViZDoom#192]
Hi,

Thanks for sharing the great platform. I have a question related to the "depth buffer".

I noticed that the depth buffer is encoded as an uint8 image. I'm wondering how to convert the values in the depth buffer to the metric that "game_variable/position" has? (Converting the depth image to real depth value)

Thanks again!

**Comment by mwydmuch** [comment]
Hi again @XinkeAE,
depth buffer is obtained based on how the textures are scaled during rendering and right now i can tell you that 100 in game units is approximately 14 depth buffer.
So distance to object in game world: 100, in depth buffer: ~14,
distance to object in game world: 200, in depth buffer: ~28,
distance to object in game world: 300, in depth buffer: ~42,
and so on...

We probably should scaled it to better match the game unit...

**Comment by mwydmuch** [comment]
Because the way we obtain it and image rendered by Doom engine is a bit out of perspective, I think that values in depth buffer for objects in corners of the screen and distance in game logic may mismatch a bit.

**Comment by XinkeAE** [comment]
Thanks @mwydmuch ! The information is helpful!
