### ISSUE TITLE
How install after compiling from sources?

### ISSUE THREAD

**Issue by IvanKush** [mwydmuch/ViZDoom#194]
I compiled in Linux according to this instruction (pip install doesn't work)
```
cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON3=ON -DBUILD_JAVA=ON -DBUILD_LUA=ON
make
```
What command should I type in order to install binaries to system directories?

Because when I run 1st example from tutorial
```
./basic.py
Traceback (most recent call last):
  File "./basic.py", line 15, in <module>
    from vizdoom import *
ImportError: No module named 'vizdoom'

```

**Comment by ebonyclock** [comment]
Well, cmake and make only compile it and place it in bin/python2/pip_package so if you want to compile by hand you need to link to the package or copy it.


But ... why isn't pip install working? Could you copy the output?

**Comment by IvanKush** [comment]
don't know =/

`sudo pip install git+https://github.com/mwydmuch/ViZDoom`


` 
 [ 99%] Building CXX object CMakeFiles/libvizdoom_python3.dir/src/lib_python/ViZDoomPythonModule.cpp.o
    make[2]: *** No rule to make target '/usr/lib/python3.5/config-3.5m/libpython3.5.so', needed by 'bin/python3/vizdoom.so'.  Stop.
    make[2]: *** Waiting for unfinished jobs....
    /tmp/pip-z2opl_vy-build/src/lib_python/ViZDoomPythonModule.cpp: In function 'int init_numpy()':
    /tmp/pip-z2opl_vy-build/src/lib_python/ViZDoomPythonModule.cpp:98:5: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
         import_array();
         ^~~~~~~~~~~~
    /tmp/pip-z2opl_vy-build/src/lib_python/ViZDoomGamePython.cpp: In function 'int vizdoom::init_numpy()':
    /tmp/pip-z2opl_vy-build/src/lib_python/ViZDoomGamePython.cpp:37:9: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
             import_array();
             ^~~~~~~~~~~~
    make[1]: *** [CMakeFiles/Makefile2:182: CMakeFiles/libvizdoom_python3.dir/all] Error 2
    make: *** [Makefile:84: all] Error 2
    
    Installation failed, you may be missing some dependencies.
    Please check https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md for details
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-z2opl_vy-build/setup.py", line 92, in <module>
        keywords=['vizdoom', 'doom', 'ai', 'deep learning', 'reinforcement learning', 'research']
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-z2opl_vy-build/setup.py", line 47, in run
        subprocess.check_call(['make', '-j', str(cpu_cores)])
      File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-j', '3']' returned non-zero exit status 2
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-z2opl_vy-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wd21nxw_-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-z2opl_vy-build/

`

**Comment by ebonyclock** [comment]
Hm, it cannot see libpython3 when installing by pip. I wonder if it worked with --user option.

**Comment by pisanid** [comment]
In setup.py the library directory is retrieved through,
`sysconfig.get_config_var('LIBPL')`

On Fedora this returns the wrong directory.

Calling 
`sysconfig.get_config_var('LIBDIR')`
returns the correct directory of libpython.

While this gave me the correct directory, the way the libpython's name is resolved still didn't work. In Fedora libpython for Python3 has "m" in the versioning, for example libpython3.6m.so. I am unsure how to resolve that.

**Comment by mwydmuch** [comment]
New Python binding solves that problem, `pip install .` should work without the problem with current master.
