### ISSUE TITLE
Multiple instances in one process

### ISSUE THREAD

**Issue by imrodriguezro** [mwydmuch/ViZDoom#195]
Hi,

I'm trying to train a network with experiences from multiple agents which run in a single process. However, I observed that game.make_action() is extreme slow in this setting (which is in any case entirely sequential).

Attached is a repro script (using Windows 10, Python 3.4 or 3.5, ViZDoom 1.1.0 binaries). Change the number of agents in line 70 from 1 to 4 and you'll see the difference.

Could you guys reproduce it as well? Do you know what's the cause of that behavior? Could you think of any solution/workaround?

Thanks in advance!

Ivan

[test_several_processes.zip](https://github.com/mwydmuch/ViZDoom/files/966135/test_several_processes.zip)

**Comment by mwydmuch** [comment]
Hello @imrodriguezro,
forgive the long answer time, we have a holidays right now. Unfortunately I don't see any problem in your example, regardless of the number of agents running it takes the same amount of time to perform a single action by one agent.

**Comment by ivrodr-msft** [comment]
Thanks for your reply @mwydmuch ,
could you please tell me what time is printed in the code? In my pc, for 1 agent it prints 0.0000, but for 4 agents it prints 0.01592. Also, what kind of hardware configuration are you using?

Hope you're having nice holidays.

Ivan

**Comment by mwydmuch** [comment]
I don't have access to my working machine right now, so I checked it on 2 laptops: 
First one has Intel i3 and is running Ubuntu 16.04, action time: ~0.0006.
Second one is quite old, has Intel Core 2 Duo and is running Windows 8.1, action time: ~0.001.

**Comment by imrodriguezro** [comment]
Thanks for your help! I'll try then to continue with the investigation on my side. It's very odd since I'm using a good pc. If I find anything, I'll come back to you.

**Comment by mwydmuch** [comment]
I will install Windows 10 in next week and I will definitely check on it. ViZDoom is really lightweight so I'm 100% sure that it isn't hardware problem. I suspect the case is related to boost::interprocess.

**Comment by imrodriguezro** [comment]
I also tried in two ubuntus and one windows 8.1, and I cannot observe the decrease in speed.

**Comment by Miffyli** [comment]
On Windows 10, Vizdoom 1.1.0, i7-3770k:
1 process:    <0.0005s - 0.002s (seems to reach 0.002s periodically)
4 processes: 0.002s - 0.004s
8 processes: 0.002s - 0.004s

On a sidenote: I have noticed that training models with VizDoom is ~2x faster on my Ubuntu machine than my Windows 10 (Same hardware). However training other deep learning models (e.g. speech and image processing) does not have significant difference between these platforms. 
Maybe some libraries used by VizDoom are being clumsy on Windows?

**Comment by wjaskowski** [comment]
And what fps.py example shows on windows and Linux?

**Comment by Miffyli** [comment]
@wjaskowski 

Windows 10: 368fps (i7-3770k)
Ubuntu:  1500fps (i7-3770, machine was doing model training at around 50% CPU usage)

So I guess that explains it then. Wonder if this would change with multiple vizdooms per process (or one vizdoom per one python multiprocess).

**Comment by imrodriguezro** [comment]
Thanks for sharing your findings!
Just to add something, I have another approach in which I use one vizdoom instance per python process with 16 processes, and the speed doesn't decrease.

Ivan

**Comment by mwydmuch** [comment]
Old discussion, improved GIL management introduced in 1.1.3 boosts performance when using multiple ViZDoom instances with Python threads. Closing.
