### ISSUE TITLE
Configurable port?

### ISSUE THREAD

**Issue by desimone** [mwydmuch/ViZDoom#199]
I believe the default port is 666 which is reserved on OSX and *nix.

```sh
Starting vizdoom CIG 2017 host for 1 player.
   WAD:        ../cig2017.wad
   TIMELIMIT:  10 min.
   MAP:        map01
   PLAYERS:    1
   BOTS:       0
   CONSOLE:    False
()
BindToPort: Address already in use
Traceback (most recent call last):
  File "host.py", line 127, in <module>
    game.init()
vizdoom.vizdoom.ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.
```

Ugh disregard. I was using outdated information. The vizdoom port is actually 5029 in most cases.

https://github.com/mwydmuch/ViZDoom/blob/ae3ada3fe40d560202b7cd933dbf4124c7f4d00d/src/vizdoom/src/i_net.cpp#L88

`sudo lsof -i :5029`
```
COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
vizdoom 72200  bdd    8u  IPv4 0x32c6b9a9e0db8abb      0t0  UDP *:5029
```

**Comment by mwydmuch** [comment]
Hello @desimone,
default multiplayer port is 5029, why do you think it is 666, except that this number fits Doom very nicely? :)

**Comment by desimone** [comment]
Sorry about that @mwydmuch ... I was a little quick to pull the trigger on this one... I was experiencing a hung processes and the first result on google 

I had a good chuckle about it as well. It looks like doom is actually the [officially registered](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.txt) user of the reserved port 666.
