### ISSUE TITLE
libGL and gtk error when "./run.sh host -w"

### ISSUE THREAD

**Issue by sproblvem** [mwydmuch/ViZDoom#201]
Hi, I followed the [submission instructions](http://vizdoom.cs.put.edu.pl/competition-cig-2017/submission) to prepare my submission. I have installed the docker and nvidia-docker successfully, follow your instructions exactlly, but I got those error.

My os and cuda info:

> NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.51  Wed Mar 22 10:26:12 PDT 2017
> GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

Error message

> [122029]yama@yama-engine:~/rl/vizdoom_cig2017$ sudo ./run.sh host -w
> Starting vizdoom CIG 2017 host for 1 player.
>    WAD:        cig2017.wad
>    TIMELIMIT:  10 min.
>    MAP:        map01
>    PLAYERS:    1
>    BOTS:       0
>    CONSOLE:    False
> 
> Gtk-Message: Failed to load module "canberra-gtk-module"
> AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
> Press 'Q' to abort network game synchronization.
> Got connect from node 1.                
> Waiting for players: .. [ 2/ 2]
> Sending all here.                       
> 
> Done waiting.
> Go                                      
> Total players: 2                        
> 
> Found SampleRandomAgent (node 1, player 2)
> 
> 
> libGL error: No matching fbConfigs or visuals found
> libGL error: failed to load driver: swrast

and this 

> [122735]yama@yama-engine:~/rl/vizdoom_cig2017$ sudo ./run.sh random
> Gtk-Message: Failed to load module "canberra-gtk-module"
> AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
> Press 'Q' to abort network game synchronization.
> Total players: 2                        
> 
> Waiting for other players: .. [ 2/ 2]
> Console player number: 1                
> Received All Here, sending ACK.         
> Console player number: 1                
> Received All Here, sending ACK.         
> Received "Go."                          
> 
> Total players: 2                        
> 
> Found ghost (node 1, player 1)          
> Found SampleRandomAgent (node 0, player 2)

Does this error message indicates that something are missing in the docker file?
Looking for your response!

**Comment by ebonyclock** [comment]
It looks that everything works apart from the gui forwarding part (and sound which is expected and irrelevant) but I guess you have mentioned it [here](https://github.com/ebonyclock/vizdoom_cig2017/issues/2#issuecomment-305090946)

**Comment by sproblvem** [comment]
Thank you! Hi Michał, I have send you an email. @ebonyclock Can you reply to me?
