### ISSUE TITLE
Player immediately dead after respawn. Health -999900

### ISSUE THREAD

**Issue by Islandman93** [mwydmuch/ViZDoom#202]
I'm running into an issue where after I call game.respawn_player() and make any action the player is instantly dead (with respawn protect on). Additionally, the player is only dead after making an action, IE: the player is not dead after calling respawn_player (I'm assuming we need to make an action after respawn to move the game forward?). The weird thing is that health is always -999900 without fail. Unfortunately this occurs randomly without much explanation. I'm using cig.cfg with only health as the available game variable. Let me know what else I can to do help troubleshoot.

What really worries me is when the agent takes a couple steps (less than 5) then is dead with health at -999900. How is it that I'm allowed to take a couple actions then this error occurs? Is there anything that causes health to be -999900? When dying normally (hit by rocket) health is at least > -100ish.

Code:
```python
from vizdoom import *


config = './cig.cfg'
# setup game
game = DoomGame()
game.load_config(config)
game.set_doom_map("map01")  # Limited deathmatch.

# add CIG args
game.add_game_args("-deathmatch +sv_noautoaim 1 +sv_forcerespawn 1 +sv_respawnprotect 1"
                   "+sv_spawnfarthest 1 +sv_nocrouch 1 "
                   "+viz_respawn_delay 0")

# add player
game.add_game_args("+name {} +colorset 0".format('player{}'.format(0)))

game.set_mode(Mode.PLAYER)
game.set_console_enabled(False)
game.set_window_visible(False)
game.init()

# add bots
game.send_game_command("removebots")
for i in range(16):
    game.send_game_command("addbot")

# loop
respawn_error = 0
for episode in range(1000):
    steps = 0
    while not game.is_player_dead():
        game.make_action([])  # no op
        steps += 1

        # get game variables
        s = game.get_state()
        if s is not None:  # this should never happen there is no time limit
            # only print if player is dead
            if (game.is_player_dead() or s.game_variables[0] < 0) and steps < 5:
                print('Episode', episode, 'Steps', steps, s.game_variables, game.is_player_dead())
                respawn_error += 1
        else:
            raise AssertionError('Game should always return state when no time limit')
    game.respawn_player()
    if game.is_player_dead():
        print("Still dead", s.game_variables, game.is_player_dead())

print('Respawn errors out of {}/1000'.format(respawn_error))
```

Sample Output:
```
Episode 122 Steps 1 [-999900.] True
Episode 261 Steps 1 [-999900.] True
Episode 353 Steps 1 [-999900.] True
Episode 856 Steps 4 [-999900.] True
Respawn errors out of 4/1000
```
```
Episode 0 Steps 4 [-999900.] True
Episode 146 Steps 2 [-999900.] True
Episode 157 Steps 1 [-999900.] True
Episode 282 Steps 1 [-999900.] True
Episode 313 Steps 2 [-999900.] True
Episode 386 Steps 1 [-999900.] True
Episode 411 Steps 1 [-999900.] True
Episode 676 Steps 4 [-999900.] True
Episode 828 Steps 1 [-999900.] True
Episode 831 Steps 1 [-999900.] True
Episode 971 Steps 3 [-999900.] True
Episode 986 Steps 1 [-999900.] True
Respawn errors out of 12/1000
```

System:
Ubuntu 14.04 & Ubuntu 16.04
Anaconda3 Python 3.5.2
Built from latest GitHub

**Comment by Islandman93** [comment]
I've found the issue, if you respawn and the game spawns another player on top of you health goes to -999900. I could see how this is intended behavior, nonetheless it's still pretty annoying that it can happen on longer time steps even with the **agent moving forward**. I guess if it's documented then it wouldn't be much of an issue. This is with 16 bots, maybe there aren't enough respawn points?

Attached are some gifs I made of being killed by respawn over longer time steps (5+ frames) and a set of images being killed at the start of the game by a bot spawning on the player.

Gifs, killed by respawning bot after at least 5 steps alive:
![animation3](https://cloud.githubusercontent.com/assets/6538645/26638788/0bb2ef96-45f1-11e7-81e9-a62aee8d0292.gif)
![animation2](https://cloud.githubusercontent.com/assets/6538645/26638790/0bbdd366-45f1-11e7-9d9c-23cddf35d87b.gif)
![animation](https://cloud.githubusercontent.com/assets/6538645/26638789/0bb44210-45f1-11e7-8350-87da83ae0c93.gif)

Image 1, alive at start of game (time 0). Image 2, dead by respawn (time 1).
![thingy0](https://cloud.githubusercontent.com/assets/6538645/26638851/2e9e2de0-45f1-11e7-8f2b-19d84952d48a.png)
![thingy1](https://cloud.githubusercontent.com/assets/6538645/26638850/2e9a5cce-45f1-11e7-9111-7b736aa1fd07.png)

**Comment by mwydmuch** [comment]
Hello @Islandman93
it is Doom's original mechanics -> spawn kill and `sv_respawnprotect` doesn't protect against it. This map is definitely too small for 16 players, if I recall correctly there are a little over 8 spawn points so with 8 players and `sv_spawnfarthest` flag it shouldn't happen. We rise the limit from 8 to 16 in last release but in our competition 8 will remain as the max number of the players per single match.

**Comment by mwydmuch** [comment]
Well, this is already known behavior and was already described and discussed here and on the google group, so I will close this one.

But anyway, thank you @Islandman93 for instigating the issue.

In general, we rather try to changing as little as possible in engine itself, so I think I will simply add a warning if number of players is greater then number of spawn points.
