### ISSUE TITLE
How to get a 200x150 screen buffer from a 640x40 one, as if it was set originally with 200x150.

### ISSUE THREAD

**Issue by imrodriguezro** [mwydmuch/ViZDoom#203]
During training I use a screen buffer with resolution 200x150 pixels. When I want to check how the agent behaves during evaluation (with set_visible True) I use a resolution of 640x480 and then resize it to 200x150 to feed the neural network. However, I see a degradation in performance when doing evaluation because the image is not the same.

Do you know if there's a method to get consistent 200x150 images?
Currently I'm using python opencv function 'resize'.

Thanks in advance!

Ivan

**Comment by wjaskowski** [comment]
On 31 May 2017 at 18:36, imrodriguezro <notifications@github.com> wrote:

> During training I use a screen buffer with resolution 200x150 pixels. When
> I want to check how the agent behaves during evaluation (with set_visible
> True) I use a resolution of 640x480 and then resize it to 200x150 to feed
> the neural network. However, I see a degradation in performance when doing
> evaluation because the image is not the same.
>
> Do you know if there's a method to get consistent 200x150 images?
> Currently I'm using python opencv function 'resize'.
>
If this is just for visualization purposes, consider recording the game and
them replaying it (e.g., using
https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/record_episodes.py.
Altought, I am not sure whether this will work well with the built-in bots).

**Comment by mwydmuch** [comment]
Unfortunately the bug in build-in bots cause recordings to desynchronize. If you don't use them, recording functionality will work perfectly and it requires only changing one line of your code.

The second option is to use 2 instances of DoomGame with same seed but different rendering settings and pass the same actions to both.

And I think that the third option is to scale down in integer terms (for example from 800x600 or 1600x1200), it should help a bit.

**Comment by imrodriguezro** [comment]
Thanks a lot for your quick response!

The second option sounds very good. I'm going to try it out and tell you how it works.

**Comment by imrodriguezro** [comment]
It works effectively well :).  At first, I tried to get seed from one instance and set it to the other instance, but the games were different . When I manually set the seed for both games are the same.

Thanks!
