### ISSUE TITLE
Need help for the meaning of some game variables

### ISSUE THREAD

**Issue by NoobFang** [mwydmuch/ViZDoom#210]
Hi, maybe that's a silly question, but after reading the tutorial, I am still confused about some game variables.
Could anyone explain the exact meaning of these game variables:
KILLCOUNT, FRAGCOUNT and SECRETCOUNT 
for me?

I guess the KILLCOUNT is the number of enemies killed by my agent, however in the 'defend_the_center' task, the KILLCOUNT increases 1 when I kill a Demon but remains when I kill a MarineChainsaw. This makes me totally confused about this game variable.

**Comment by Miffyli** [comment]
I have not coded these so I can't give definite answer, however in case of NPC enemies (e.g. defend_the_center, deathmatch) you should define kill rewards in the map's ACS code. Open up one of these scenarios in SLADE, open the ACS code and check how the "int reward" is updated. 

By quick peek at code, this is what I gather:
- FRAGCOUNT is mostly for multiplayer, e.g. against other players or bots. Does not update from killing NPC(?)
- KILLCOUNT reads "level.killed_monsters", so I would guess it updates on killing monsters. However as you pointed out, this does not seem to be the case.
- SECRETCOUNT seems to count the number of "secret objects" collected (level.found_secrets), possibly for some "locate and collect" task for collecting certain type of pickups.

**Comment by adil25** [comment]
@Miffyli ....Thanks for your valuable reply..........

**Comment by mwydmuch** [comment]
Hi, all out scenarios already have programmed rewards (see https://github.com/mwydmuch/ViZDoom/blob/master/scenarios/README.md).

Variables behave exactly as described by @Miffyli. It looks like that no incrementation of KILLCOUNT after killing MarineChainsaw is probably a bug in the engine or scenario. Can you check scenario @ebonyclock?

**Comment by NoobFang** [comment]
@Miffyli I have changed reward settings in ACS scripts and that seems just affect the returned reward not the game variables. Anyway, your reply helps a lot, thank you!

**Comment by NoobFang** [comment]
@mwydmuch OK, thanks for your reply.

**Comment by ebonyclock** [comment]
@NoobFang It turns out that it's zdoom's fault though not a bug. Scripted marine (superclass of MarineChainsaw) just doesn't count towards killcount, I have added MarineChainsawVzd which works the same but increases the killcount.
