### ISSUE TITLE
How to get the direction the agent is facing?

### ISSUE THREAD

**Issue by GoingMyWay** [mwydmuch/ViZDoom#213]
Hi, as far as I know, we can see the direction the agent is facing  with `automap_buffer`

```
automap = state.automap_buffer
if automap is not None:
    plt.imshow(automap)  # import matplotlib.pyplt as plt
    plt.show()
```

However, are there any methods that can be used to get the direction the agent is facing? The direction can be a vector.

And a method that can be used to calculate the direction is the position, for example

```
pre_x, pre_y, pre_z = get_x_y_z()

while in game_loop():
    x, y, z = get_x_y_z()
    direction = (x-pre_x, y-pre_y, z-pre_z)
    pre_x, pre_y, pre_z = x, y, z
```

But there is a problem in it, if the agent doesn't move but turn the direction to some degree, I can't update the direction since the position doesn't change.

**Comment by Miffyli** [comment]
I do not know of a method for this, but you can define ACS script that stores angle of the player in one of the USERXX variables:

```
global int 0:angle;

script 2 ENTER
{
    while(1)
    {
         angle = GetActorAngle(0);
    }
}
```

You can now read the angle of the player via `vzd.doom_fixed_to_double(doom.get_game_variable(GameVariable.USER1))`.

**Comment by mwydmuch** [comment]
`ANGLE`, `PITCH`, `ROLL`, `VELOCITY_X/Y/Z` GameVariables added.

**Comment by GoingMyWay** [comment]
Thank you @mwydmuch for adding this feature!
