### ISSUE TITLE
SELECT_WEAPONX seems not working?

### ISSUE THREAD

**Issue by whluo** [mwydmuch/ViZDoom#217]
Hi there, I encountered a problem of setting button SELECT_WEAPONX. 
When the agent pickup a new weapon, it auto switches to the newly picked-up weapon and uses this weapon even after I set SELECT_WEAPONX (X means the weapon I want to choose) to be true. So, the SELECT_WEAPONX button seems not working? How could I switch back to the weapon I want? Thanks a lot in advance.

**Comment by mwydmuch** [comment]
Hello @whluo, 
You can disable weapon autoswitching by adding `game.add_game_args("+neverswitchonpickup 1")`. Or by changing this in `_vizdoom.ini` file.
And when it comes to the buttons, some of them (including SELECT buttons) makes action at the moment of "pressing" and then they must be released and "pressed" again to repeat action.

**Comment by mwydmuch** [comment]
I've just check and looks like we changed this, you could be able to keep SELECT_WEAPONX button pressed to change to this weapon.

**Comment by whluo** [comment]
Hi @mwydmuch 
Thanks a lot for the quick reply. I would check this later. But, even it is related to the automatic switch in case of pickup, it should be able to change back to the weapon I want. But my case is that, the agent picked, and switched weapon but never changed back even I set the SELECT_WEAPONX ...

**Comment by whluo** [comment]
Hi @mwydmuch 
I have checked that and found that does solve my problem. Thanks very much for your help!

**Comment by GoingMyWay** [comment]
@whluo , when training the agent, what if there are no corresponding weapons in hand when the agent press `SELECT_WEAPONX`  button. Will it raise an error since the agent has not weapon `X`.
