### ISSUE TITLE
In Health gathering scenario, how can I set the reward of gathering a health pack?

### ISSUE THREAD

**Issue by GoingMyWay** [mwydmuch/ViZDoom#220]
Since in `health_gathering.cfg` I can set the `living_reward = 0`, `death_penalty = 0` and `episode_timeout = 1000`. But how can I set the reward of gethering a health pack?

**Comment by ebonyclock** [comment]
You cannot. You'd need to change and recompile the wad file (in slade, doom builder or other software l
that can modify wads). Alternatively you can use USER1 which stores kind of cumulated shaping reward which is 100 per gathered health pack.

**Comment by GoingMyWay** [comment]
@ebonyclock , Hi, How can I use USER1 to get the reward of 100 per gathered health pack?

**Comment by mwydmuch** [comment]
Hi @GoingMyWay 
shaping.py exactly shows you how to do this :)

`USER1` variable in this example **accumulates** all rewards for health packs.

**Comment by GoingMyWay** [comment]
@mwydmuch , thank you, to do this here is my code

```
game.make_action(action, 4)  # skip frame value is 4
shaping_reward = doom_fixed_to_double(game.get_game_variable(GameVariable.USER1)) / 100.
r = (shaping_reward - last_total_shaping_reward)
last_total_shaping_reward += r
```

The `r` is the reward(1 if a pack is gathered else 0) since skip frame is applied here, how can I take rewards into consideration during skip frame period?

**Comment by ebonyclock** [comment]
You do, the shaping reward implemented in HG is cummulative so when making an action with frameskip 4 you just get the reward from all from steps. If you gathered a health pack each action (which is highly unprobable btw) youd get r = 4. If you want to know when exactly the agent gets the rewards don't use frameskip.

**Comment by GoingMyWay** [comment]
@ebonyclock , thanks for you reply, it takes about 5 hours to train 450 episodes in health pack gathering scenario without frame skipping. So slow. 

And I found that `game.make_action` always return 0.0 even when the agent gathered a health pack. Looks strange, since in health pack gathering scenario, to create a decent reward function, on should take the health value and `game.get_game_variable(GameVariable.USER1) ` into consideration.

**Comment by ebonyclock** [comment]
@GoingMyWay Well, with shaping (rewards for picking up the medikits) the problem is easy and there is not much to improve there. A situation when you basically get no reward and a penalty for dying is much more challenging.
