### ISSUE TITLE
How can I set the reward of killing a daemon in deadly corridor

### ISSUE THREAD

**Issue by GoingMyWay** [mwydmuch/ViZDoom#227]
Hi, I'm trying to implement an agent on the deadly scenario, and how can I set the reward after killing a daemon?

**Comment by ebonyclock** [comment]
You need to modify and recompile  the wad.

**Comment by GoingMyWay** [comment]
@ebonyclock , if I only want to count how many demons the agent has killed in every action, should I recompile the corresponding wad file?

**Comment by ebonyclock** [comment]
use GameVariable.KILLCOUNT

**Comment by GoingMyWay** [comment]
@ebonyclock , thanks!
