### ISSUE TITLE
In death match scenario how can I get the type of daemon after killing it?

### ISSUE THREAD

**Issue by GoingMyWay** [mwydmuch/ViZDoom#232]
Hi, sorry to bother you all, in the death match scenario, since there are different daemons and they have different strength. How can I get the type or the name of the daemon after killing it?

In the APIs of ViZDoom there is a function `get_total_reward()`, but it returns the overall reward including killing a daemon, gathering health-packs, ammo or armors.

**Comment by mwydmuch** [comment]
Hi @GoingMyWay, as you might have already guessed it'll require to be implemented in scenario's ACS script. This is the function you will need: https://zdoom.org/wiki/CheckActorClass
Right now it's only possible to pass single numerical variables from game to controller, so it's hard to do it in elegant way. 

I would do it this way:
```c
//user defined variables
global int 1:zombieman_killcount 
global int 2:shotgunguy_killcount
...

// other scenario's scripts

script 3 (int id, int r)
{
    for (int i=0; i<6; i++)
        if (CheckActorClass(tid, monsters[i])){
            if(i==0) zombieman_killcount++
            else if(i==1) shotgunguy_killcount++
            ...
        }
    
    // rest of this script
    Thing_Remove(id);
    reward = reward + r;
}
```

**Comment by GoingMyWay** [comment]
@mwydmuch thank you for your advice
