### ISSUE TITLE
Apparent bug in Basic.java

### ISSUE THREAD

**Issue by edwbarker** [mwydmuch/ViZDoom#235]
Hi.  Firstly, thanks very much for all your work on this project.

I'm on Ubuntu 16.04.  Have installed with the intention of using Java.

When I load Basic.java into Eclipse, line 117 contains an error:  
>"The method makeAction(double[]) in the type DoomGame is not applicable for the arguments (int[])"

Could you please check the latest java files are all working as they should?  (Perhaps related to this error, despite much wrangling I've been unable to integrate my java program and the vizdoom files from the latest github version.)

Thanks!

**Comment by mwydmuch** [comment]
Hello @edwbarker,
the examples were slightly outdated, they should work now. Thank you for reporting this.

**Comment by edwbarker** [comment]
Thanks, all working.

It's possible the pre-compiled Windows files may also need updating.  The makeAction method embedded in the vizdoom.jar file seems to still require an int[] argument, and this is reflected in the examples (i.e. the files in the Windows download are internally consistent, but there could potentially be an issue when moving code between operating systems).  

Thanks ... and again, great project you guys have set up.

**Comment by mwydmuch** [comment]
Yeah, you are right, Windows prebuild binaries is also missing few recent updates, we should really take care of this in the near future.
