### ISSUE TITLE
Installation failed, on Python 3.6, macOS 10.12.6 X64

### ISSUE THREAD

**Issue by woxing920821** [mwydmuch/ViZDoom#236]
Hi,

I have a trouble when I installed the vizdoom with python3.6. And I don't know what's wrong with it.

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-00t2SR-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-HbgiTu-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-00t2SR-build/

**Comment by mwydmuch** [comment]
Hello @woxing920821,
what command exactly you used to install ViZDoom? `pip3 install` should work without the problem on macOS Sierra.

**Comment by woxing920821** [comment]
Hi @mwydmuch 

Thank you very much. I got it. I had installed the boost-python with python2.7 and I forgot uninstall it when I install the boost-python with python3.6.

And I have a new problem is that when I making vizdoom the header "Python.h" cannot be found.

In file included from /Users/xiechuan/Downloads/ViZDoom-master/src/lib_python/ViZDoomGamePython.cpp:23:
/Users/xiechuan/Downloads/ViZDoom-master/src/lib_python/ViZDoomGamePython.h:31:10: fatal error: 
      'Python.h' file not found
#include <Python.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/libvizdoom_python3.dir/src/lib_python/ViZDoomGamePython.cpp.o] Error 1
make[1]: *** [CMakeFiles/libvizdoom_python3.dir/all] Error 2
make: *** [all] Error 2

The command of cmake is "sudo cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON3=ON -DPYTHON_EXECUTABLE=/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/include/python3.6 -DPYTHON_LIBRARY=/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/libpython3.6.dylib -DNUMPY_INCLUDES=/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/core/include
"
