### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by AnEgg** [mwydmuch/ViZDoom#239]
python` version 3.5, running in jupyter notebook, ubuntu 16.04.2

```
from vizdoom import *
import tracemalloc 
import random

tracemalloc.start()

env = DoomGame()
env.load_config("scenarios/deathmatch.cfg")
env.set_window_visible(False)
env.set_screen_resolution(ScreenResolution.RES_160X120)
env.set_screen_format(ScreenFormat.RGB24)
env.set_render_hud(False)
env.set_render_crosshair(False)
env.set_render_weapon(False)
env.set_render_decals(False)
env.set_render_particles(False)
env.set_episode_start_time(10)
env.init()


games_played = 0
episodes = 10000

for i in range(episodes):
    while not env.is_episode_finished():
        action = [random.choice([True, False]) for i in range (17)]
        reward = env.make_action(action)
        state = env.get_state()
    env.new_episode()
    games_played += 1

    if games_played % 100 ==0:
        print(games_played)
        snapshot = tracemalloc.take_snapshot()
        top_stats = snapshot.statistics('lineno')

        print("[ Top 10 ]")
        for stat in top_stats[:10]:
            print(stat)
    
```
no memory leak without the state = env.get_state() line

**Comment by Miffyli** [comment]
Seems related to #137. Which version of VizDoom are you running?

@ebonyclock 
#137 is included in 1.1.2, correct? I too still leak memory but slower than when I originally reported #137. Ubuntu 16.04 + Python 3.5 + VizDoom 1.1.2.

**Comment by AnEgg** [comment]
Sorry for the late reply

Updated to most recent version. However, now on the env.init() line, it's giving me ViZDoomUnexpectedExitException

**Comment by AnEgg** [comment]
just an update, now have the latest version working with no memory leak

**Comment by mihahauke** [comment]
@AnEgg So we might safely assume that it's the memory leak we previously had that is already corrected?
