### ISSUE TITLE
I need the code for skipping frames during training the agent.

### ISSUE THREAD

**Issue by adil25** [mwydmuch/ViZDoom#241]
Hello every one. I am training my agent using deep learning and i want to skip each 4th frame during training but i do not know how to do it in python. please someone tell me the python code for skipping frames  so that i can apply that code in my program for skipping the frames....Thanks

**Comment by Miffyli** [comment]
You define number of frames "skipped" while doing an action with `game.make_action(action, **frame_repeat**)`. **frame_repeat** defines for how many frames the given action will be executed. 

E.g. [In Tensorflow learning example make_action](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/learning_tensorflow.py#L174) the code executes given action for frame_repeat = 12 frames, and the next read state will be after those 12 frames have been executed.

**Comment by adil25** [comment]
@Miffyli ...Thank you very much......................
