### ISSUE TITLE
How to change the speed of built-in bots

### ISSUE THREAD

**Issue by flyers** [mwydmuch/ViZDoom#242]
Hello,
I want to change the speed of built-in bots in scenarios/cig.wad since the default speed seems to be high. I found that there is no such definition in the bot configuration file bots.cfg. Now the solution I got is to create a custom player class in DECORATE file and change the speed value to be smaller than 1.
```
ACTOR DoomPlayer : PlayerPawn
{
  Speed 0.2 // change the value here
  Health 100
  Radius 16
  Height 56
  Mass 100
  ...
}
```
However there are some issues for this. Since I change the default DoomPlayer class, the agent I want to train is also moving very slowly.
Is there a simple way to decrease the speed of the built-in bot without affecting the default behavior of the learned agent?
Thanks.

**Comment by mwydmuch** [comment]
My approach would be to change the speed of the player at respawn using ACS script if it isn't agent's player (has number other than 1). This unfortunately needs to be added to each map separately.

**Comment by flyers** [comment]
@mwydmuch Thanks for your reply. It's OK that the ACS script needs to be modified for each map.
I tried to use the following script to change the speed of the agent's player but it did not work. Could you please tell me what's the problem?
```
#include "zcommon.acs"

script 1 OPEN
{

}

script 2 ENTER
{
	SetActorProperty(0, APROP_SPEED, 0.1);
	ClearInventory();
	GiveInventory("RocketLauncher",1);
	GiveInventory("RocketAmmo",10);
	
}

script 3 RESPAWN
{
	SetActorProperty(0, APROP_SPEED, 0.1);
	ClearInventory();
	GiveInventory("RocketLauncher",1);
	GiveInventory("RocketAmmo",10);
}                                  
```
I don't quite understand what's the tid argument in function SetActorProperty. What's the tid for the agent player actor and what's the tid for added bot player?

**Comment by Miffyli** [comment]
SetActorProperty takes TID as a first parameter which specifies the target actor you want to modify (I think 0 is for player always?). In ENTER and RESPAWN blocks you can use `ActivatorTID()` to get the TID of activating actor (each player and bot, in case of cig.wad). I used the following the slow down bots but keep the player fast in cig.wad map01:

```
script 2 ENTER
{
	ClearInventory();
	GiveInventory("RocketLauncher",1);
	GiveInventory("RocketAmmo",10);
	if (ClassifyActor(ActivatorTID()) & ACTOR_BOT ) {
		SetActorProperty(ActivatorTID(), APROP_Speed , 0.4);
	}
}

script 3 RESPAWN
{
	ClearInventory();
	GiveInventory("RocketLauncher",1);
	GiveInventory("RocketAmmo",10);
	if (ClassifyActor(ActivatorTID()) & ACTOR_BOT ) {
		SetActorProperty(ActivatorTID(), APROP_Speed , 0.4);
	}
}
```

**Comment by mwydmuch** [comment]
@Miffyli very elegant, I didn't know this function. You are a big help, as always, thank you :)

**Comment by flyers** [comment]
@Miffyli Thanks very much! This is exactly what I wanted.

**Comment by Jeeeeeiel** [comment]
@Miffyli why i can't get bot's id by ActivatorTID()?

**Comment by acrushdjn** [comment]
I used SLADE to modify my .WAD file, used your script, but the bots speed remains the same
[deathmatch_shotgun.zip](https://github.com/mwydmuch/ViZDoom/files/2777434/deathmatch_shotgun.zip)
