### ISSUE TITLE
X/Y/angle player acceleration - is it possible to obtain them from vizdoom?

### ISSUE THREAD

**Issue by nsavinov** [mwydmuch/ViZDoom#244]

**Comment by GoingMyWay** [comment]
@nsavinov  Do you mean position and angle? I think they are available in the APIs.

**Comment by nsavinov** [comment]
@GoingMyWay No, I mean the second derivatives of position and angle.

**Comment by nsavinov** [comment]
Just to clarify, I would like to obtain measurements similar to what https://en.wikipedia.org/wiki/Inertial_measurement_unit provides.

**Comment by wjaskowski** [comment]
Doom is discrete. To compute velocities substract the last position from
the current one.

**Comment by ebonyclock** [comment]
@nsavinov You can access velocity for x, y, and z (GameVariable.VELOCITY_X Y and Z) which is better for computing acceleration I guess. Anyway I am not sure but it seems that there is no straightforward way to get it from the engine. 
However I have a feeling that doom's physics is not so much aligned with our world's physics. Here, force causes acceleration which causes motion and in doom ... well ... motion seems to create motion so deriving acceleration  seems like a proper option.
