### ISSUE TITLE
Minor issues with the "Configuration files" documentation

### ISSUE THREAD

**Issue by maximecb** [mwydmuch/ViZDoom#245]
I found 3 minor issues with the `doc/ConfigFiles.md` document.

This comment seems out of sync:

```
# make episodes start after 20 tics (after unholstering the gun)
episode_start_time = 14
```

These two options need comments. For instance, is skill level 5 easiest or hardest:

```
mode = PLAYER
doom_skill = 5
```

And lastly, the "other examples can be found here" link is broken. I recommend switching to a relative link (`/examples/config`) instead of an absolute one.

**Comment by ebonyclock** [comment]
Thanks for vigilance. Btw pull requests are welcome.

If you by any chance get to scenarios and their descriptions, don't get scared, we know they need an overhaul.

**Comment by maximecb** [comment]
@ebonyclock I can make a PR, but can you tell me what the numbers map to for difficulty levels?

**Comment by ebonyclock** [comment]
1 - I'm too young to die
2 - Hey, not too rough
3 - Hurt me plenty
4 - Ultra-Violence
5 - Nightmare!

**Comment by ebonyclock** [comment]
@maximecb And I hope that options that are not so straightforward are described in [DoomGame doc](https://github.com/mwydmuch/ViZDoom/blob/master/doc/DoomGame.md)

**Comment by maximecb** [comment]
Looks like you fixed it already. Props on responding rapidly!
