### ISSUE TITLE
Is it possible to remove decals?

### ISSUE THREAD

**Issue by paulobruno** [mwydmuch/ViZDoom#249]
I want to remove/disable decals (blood and bullet marks in walls, specifically), is it possible to do it in code?
And, in general, it is possible to set a CVAR value in code? If yes, how?

**Comment by ebonyclock** [comment]
Removing decals:
https://github.com/mwydmuch/ViZDoom/blob/master/doc/DoomGame.md#setRenderDecals

For cvars you need use add_game_args e.g. add_game_args("+sv_cheats 1")

You can set both things in config files.

**Comment by paulobruno** [comment]
Ok, thanks :smile:
