### ISSUE TITLE
Windows install from binary

### ISSUE THREAD

**Issue by MartinBrazdil** [mwydmuch/ViZDoom#250]
Hello, I have tried to install ViZDoom using [ViZDoom-1.1.0-Win-Python35-x86_64.zip](https://github.com/mwydmuch/ViZDoom/releases/download/1.1.0/ViZDoom-1.1.0-Win-Python35-x86_64.zip).

I have extracted contents and copied `vizdoom` folder into `C:\ProgramData\Anaconda3\Lib\site-packages`. Pycharm sees the package (autocompletes on` import vizdoom`) but when I open _basic.py_ then pycharm complains about _unresolved reference DoomGame_ and `from vizdoom import *` is marked as _unused import_.

Well there is only _vizdoom.pyd_ in vizdoom folder (from python files) and I am not exactly sure how python handles pyd files but it looks like _\_\_init\_\_.py_ calls `from .vizdoom import *` so I thought its ok.

Running basic.py:
```
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2017.1.3\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm 2017.1.3\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2017.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Gwynbleidd/ViZDoom-1.1.0-Win-Python35-x86_64/examples/python/basic.py", line 15, in <module>
    from vizdoom import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\vizdoom\__init__.py", line 1, in <module>
    from .vizdoom import __version__ as __version__
ImportError: DLL load failed: The specified module could not be found.
```

I hope its just something stupid on my side,
best regards, Martin.

**Comment by Miffyli** [comment]
Installing prebuilt Windows binaries should be just matter of copying the contents of vizdoom folder to the site-packages, as you have done. However for some reason it is not able to load some of the required DLLs.

Have you tried running it without PyCharm, i.e. via command line? Anaconda could also interfere here, but I do not have experience with Anaconda on Windows.

**Comment by MartinBrazdil** [comment]
Thanks for reassurance. Command line output is the same. Maybe the problem could be in python 3.5 vs 3.6 incompatibility (but I doubt that)? 

I have also tried to build under windows. First there was problem finding Boost 1.65.1 but updating CMake from 3.8rc to 3.9.3 resolved that. Then there was error not finding unistd.h so I have tried supplying VIZ_OS_WIN to preprocessor which switched to Windows.h and resolved error. However there are still 12 errors related to python bindings which might be related to Anaconda. Maybe resolving this would also fix my original problem.

I will update this post or post another if there is something new.

**Comment by Miffyli** [comment]
If I recall correctly you need Python 3.5 to run the built binary. I can vaguely remember installing 3.6 + all the modules, only to find out pre-built VizDoom was not supported on it ^^.

@mwydmuch 
Any chance of updated Windows builds with 3.6 as well, at some point when you have time?

**Comment by MartinBrazdil** [comment]
I have tried binaries with python 3.5 (still Anaconda) and it just works! Thanks for tip :-)

**Comment by mwydmuch** [comment]
Windows builds have been updated!
