### ISSUE TITLE
Invulnerable player by SetActorProperty does not work

### ISSUE THREAD

**Issue by flyers** [mwydmuch/ViZDoom#254]
Hi guys,
I want to make the player invulnerable by modifying the ACS script. As far as I know, this should be achieved by the following scripts:
```
#include "zcommon.acs"

script 1 OPEN
{

}

script 2 ENTER
{
	ClearInventory();
	GiveInventory("RocketLauncher",1);
	GiveInventory("RocketAmmo",10);
	if (ClassifyActor(ActivatorTID()) & ACTOR_PLAYER ) {
		SetActorProperty(ActivatorTID(), APROP_Health , 200);
		SetActorProperty(ActivatorTID(), APROP_Invulnerable, 1);
	}
}

script 3 RESPAWN
{
	ClearInventory();
	GiveInventory("RocketLauncher",1);
	GiveInventory("RocketAmmo",10);
	if (ClassifyActor(ActivatorTID()) & ACTOR_PLAYER ) {
		SetActorProperty(ActivatorTID(), APROP_Health , 200);
		SetActorProperty(ActivatorTID(), APROP_Invulnerable, 1);
	}
}
```
While the player health is successfully changed to 200, the invulnerable property seems to have no effect on the player. The player can still get killed by shooting rocket missile nearby.
Could some body tell me where did I miss? I used the following flags to start a game instance. Does this have any influences? Thanks very much.
```
"-host 1 -deathmatch +sv_spawnfarthest 1 "
"+timelimit 10.0 +sv_forcerespawn 1 +sv_noautoaim 1 +sv_respawnprotect 1 +sv_nocrouch 1 "
"+viz_respawn_delay 2 +viz_nocheat 0 "
```

**Comment by Miffyli** [comment]
Hmm I attempted to use simple console cheats to get a god mode for the player, but seems like you can not even open console when you launch game via Python scripts. Console works when you run Vizdoom binary alone.

I also tried your codes and could not get it working by adjusting the game arguments. I had same problem of not being able to make invulnerable or even semi-invulnerable players before. 

@mwydmuch 
Any suggestions on this?

**Comment by mwydmuch** [comment]
Hi @flyers and @Miffyli,
my solution would be almost the same as yours @Miffyli, with just small correction:
Cheat codes are CCMDs (not CVARs), so they are ignored as startup arguments. Instead `send_game_command` (it sends console command) can be used to apply god mode after start of every episode:

```
game.add_game_args("+sv_cheats 1")
(...)
for i in range(episodes):
    game.send_game_command("iddqd")
    while not game.is_episode_finished():
        (...)
    game.new_episode()
```

**Comment by flyers** [comment]
@mwydmuch Thanks very much! It works.

**Comment by flyers** [comment]
I found one possible bug. The game.send_game_command("iddqd") will not succeed every time it is executed. Namely that after every 10 episodes, there may be one or two episode where the god mode is actually not working.
Any thoughts on this? @mwydmuch 
Thanks.

**Comment by flyers** [comment]
I found another command game.send_game_command("god2") is more robust. I paste it here for reference in case anyone wants to do the same thing.
