### ISSUE TITLE
How to distinguish between living and dead AI players

### ISSUE THREAD

**Issue by guotata1996** [mwydmuch/ViZDoom#257]
According to API, Doomgame.get_state().labels shows everything in view, but I found the label 'DoomPlayer' not only represents a living AI player, but also represents a dead man,or corpse. I think it would be better to distinguish between these two, as sometimes we don't wanna let our client aim at a corpse when training, so such confuse could be a trouble when extracting game variables.

a condition where I got a 'DoomPlayer'　label when aiming at a corpse is here: https://pan.baidu.com/s/1c2rSzok

**Comment by mwydmuch** [comment]
Hi @guotata1996, unfortunately there is no way to distinguish these two at the moment, but it can be easily added by modifying the `src/vizdoom/src/viz_game.cpp` file. It is a good idea to add some additional informations about objects' states or properties.

**Comment by mwydmuch** [comment]
Done!
