### ISSUE TITLE
How can I change the bot for the basic scenario? 

### ISSUE THREAD

**Issue by eyyi** [mwydmuch/ViZDoom#258]
Hi, 
is it possible to configure the bot (aiming, perfection, etc.) for a specific scenario via configuration file (e.g. add bot "Rambo" in basic.cfg)?

**Comment by Miffyli** [comment]
As far I am aware you can only change this via bots.cfg, but you can create any number of bot configurations there.

You can specify which bot you want to add with "addbot" game command (e.g. in cig_bots.py example, you can change `game.send_game_command("addbot")` to `game.send_game_command("addbot Rambo")` and it will spawn a Rambo bot. 

(also FYI: You can change other attributes of bots via ACS scripts, e.g. speed (see #242))

**Comment by eyyi** [comment]
Thank you for your response. 

I have noticed that the command `game.send_game_command("addbot")` has no effect on my ViZDoom environment on my Mac (macOS Sierra).

I have tested it on Ubuntu 16.04 and there it works.

**Comment by Miffyli** [comment]
Make sure that you have bots.cfg in correct folder. On my Windows I usually just put the bots.cfg alongside my script (in same folder) or whatever is the "working directory" while launching the script. 
Additionally you need to call the command after `game.init()`.

**Comment by eyyi** [comment]
I put the bots.cfg in the same directory and it works. 
Thank you!
