### ISSUE TITLE
How to get orientation ?

### ISSUE THREAD

**Issue by jiahengqi** [mwydmuch/ViZDoom#260]
I found POSITION_X _Y _Z in GameVariable, but no orientation. How to get it?

**Comment by mihahauke** [comment]
ANGLE should give you orientation. But I am not sure what the exact output is, probably like "byte angle" described here: https://zdoom.org/wiki/Definitions but I can't check it right now.

**Comment by mwydmuch** [comment]
Values of `ANGLE` GameVariable are in degrees [0; 360)

**Comment by jiahengqi** [comment]
Thanks! But I still don't know how to get it.
and the website just describe the form of angle

like this,
game.get_game_variable(GameVariable.POSITION_X)
but I can't find attribute  like ANGLE, byte angle.  Where is it?

I use Python 3.5 (64-bit)  from Windows Build

**Comment by Miffyli** [comment]
I do not believe these new game variables (VELOCITY?/ANGLE) are available in the current pre-built Windows vizdoom (1.1.0). You would have to build Vizdoom from current source yourself.

Meanwhile you can get the byte angle (as mihahauke linked above) by modifying the ACS script to store `GetActorAngle()` to one of the USER# variables (see #67 for an old example of getting player position).

@mwydmuch 
Any chance of getting new Windows build at some point btw? :>

**Comment by jiahengqi** [comment]
Thanks! I find ANGLE  on my classmates' computer who use ubuntu. I will build myself next

**Comment by mwydmuch** [comment]
@jiahengqi New windows builds are now available :)
