### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by forhonourlx** [mwydmuch/ViZDoom#264]
Traceback (most recent call last):
  File "c51_ddqn.py", line 290, in <module>
    r_t = agent.shape_reward(r_t, misc, prev_misc, t)
  File "c51_ddqn.py", line 123, in shape_reward
    if (misc[2] < prev_misc[2]): # Loss HEALTH
IndexError: index 2 is out of bounds for axis 0 with size 2

Could someone kindly help me?
Thanks.

**Comment by forhonourlx** [comment]
with ViZDoom-1.1.5pre-Win-Python35-x86_64

**Comment by mihahauke** [comment]
Give us more details and some code. And ... are you sure that misc should contain 3 elements whatever it is?

**Comment by forhonourlx** [comment]
Sorry for that. I should post the issue in another repo...Thank you anyway.

**Comment by forhonourlx** [comment]
And the source code is in:
https://github.com/flyyufelix/C51-DDQN-Keras
