### ISSUE TITLE
can't install with python 3

### ISSUE THREAD

**Issue by glample** [mwydmuch/ViZDoom#265]
Hi,

I'm trying to install ViZDoom with python 3, and I removed everything related to python 2 from my computer, but I'm getting this error whenever I want to start one of the examples:

```
Fatal Python error: PyThreadState_Get: no current thread

Abort trap: 6
```

From what I understood these errors occur when several versions of python are involved in the compilation. This is the cmake command I used:

```
cmake -DCMAKE_BUILD_TYPE=Release -DBoost_USE_STATIC_LIBS=ON \
-DSDL2_LIBRARY=/Library/Frameworks/SDL2.framework \
-DSDL2_INCLUDE_DIR=/Library/Frameworks/SDL2.framework/Headers \
-DBUILD_PYTHON=OFF \
-DBUILD_PYTHON3=ON \
-DBUILD_LUA=OFF \
-DNO_FMOD=ON \
-DPYTHON_INCLUDE_DIR=/Users/guismay/anaconda3/include/python3.6m \
-DPYTHON_LIBRARY=/Users/guismay/anaconda3/lib/libpython3.6m.dylib \
-DPYTHON_EXECUTABLE=/Users/guismay/anaconda3/bin/python
```

Any ideas of what could have gone wrong?

Thank you

**Comment by guiambros** [comment]
There are too many dependencies to troubleshoot errors like these. I also had trouble running VizDoom under Python 3 (and even 2), so I created a Docker container with everything you need to run. Now it works perfectly, and I can install/remove libraries without fear of breaking something.

Here's the [Dockerfile](https://gist.github.com/guiambros/1ee62876fb309207b02eb69c8c7b39fa), and this is the [shell script](https://gist.github.com/guiambros/8847ae6d23299a395c3d8a566996a16f) to execute it. Tested under Ubuntu 14.04; YMMV.

**Comment by mwydmuch** [comment]
Probably related to #275, that was fixed.
Also, I added links to your Dockerfile @guiambros to README.md in our docker dir. Thank you!
