### ISSUE TITLE
random vizdoom crash

### ISSUE THREAD

**Issue by glample** [mwydmuch/ViZDoom#270]
Hi,

When I start a bunch of experiments with the ViZDoom library, I sometimes have some experiments that fail randomly at some point in the training. Typically, at the end of an epoch when I evaluate a model, I need to call `game.init()`, and sometimes I get this error:

```
Failed to create /.config/vizdoom/ directory:
Permission denied
```

Then the whole experiment crashes. Any ideas?

**Comment by Miffyli** [comment]
Hmmm I have not experienced this, even during larger experiments. Are you using the very latest build / one from pip? Are you calling `init()` multiple times for the same `DoomGame` instance? I only have one `init()` per one creation of `DoomGame`.

**Comment by glample** [comment]
Mmm unfortunately I don't have a simple code that could be used to replicate the issue. Even the bug is hard to reproduce as it can of appears randomly...

Would it be possible to create the config file in the directory where the code is ran? I have always faced issues when running vizdoom on clusters, because of this init file which is sometimes created in a folder where the job launcher does not have permissions. I was able to fix it in the past by defining manually a new environment variable for $HOME, but I don't really like this solution.

**Comment by mwydmuch** [comment]
Hi @glample,
thank you for reporting/reminding about this problem,
I totally agree that writing some user settings in the home dir is not needed and dumping it to a working dir instead is a much more robust solution. I will change this in the engine.

**Comment by mwydmuch** [comment]
Done
