### ISSUE TITLE
get this error ‘Segmentation fault (core dumped)’ when i run 'game.init()'

### ISSUE THREAD

**Issue by reaIws** [mwydmuch/ViZDoom#271]
when i run game.init() ,i get a error of '**Segmentation fault (core dumped)** '
when i run ./vizdoom i get this error:
**libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast**
**what can i do for this error ,if i have to Install graphics CARDS on my computer？**
`cmbc@u1:~/ipython/ipython2/rl_exmple/ViZDoom/build/lib/vizdoom$ ./vizdoom
ViZDoom 1.1.5 (ZDOOM 2.8.1) - SDL version
Compiled on Dec 25 2017

M_LoadDefaults: Load system defaults.
Gameinfo scan took 0 ms
W_Init: Init WADfiles.
 adding /home/cmbc/ipython/ipython2/rl_exmple/ViZDoom/build/lib/vizdoom/vizdoom.pk3, 583 lumps
 adding ./freedoom2.wad, 3595 lumps
I_Init: Setting up machine state.
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Family 6, Model 60, Stepping 3
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
I_InitSound: Initializing OpenAL
  Opened device Dummy Output
  EFX enabled
V_Init: allocate screen.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
Adding dehacked patch freedoom2.wad:DEHACKED
Patch installed
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading default status bar definition.
ParseSBarInfo: Loading custom status bar definition.
===========================================================================
This is Freedoom, the free content first person shooter.

Freedoom is freely redistributable under the terms of the modified BSD
license. Check out the Freedoom website for more information:

    https://freedoom.github.io/
============================================================================
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
Keyboard layout unknown, please send the following to the SDL mailing list (sdl@libsdl.org):
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Using video driver x11
Resolution: 640 x 480
Starting MIDI playback failed
`

**Comment by mwydmuch** [comment]
Hello @reaIws, 
according to this post: https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update 
it looks like a problem on the drivers side or some linking to a proper library. There are a few other solutions posted on the net, I hope you will find one that will work for you.
