### ISSUE TITLE
'NoneType' object has no attribute 'screen_buffer'

### ISSUE THREAD

**Issue by djbyrne** [mwydmuch/ViZDoom#272]
Hi Guys,

I am trying to retrieve an image of the screen after refreshing the game state but it appears that there is no screen_buffer attribute for game state?

I can do it when the episode is initialised but not after. Any idea why?

`class Environment:

	def __init__(self):
		self.game = DoomGame()
		self.game.load_config("/Users/donalbyrne/ViZDoom/scenarios/defend_the_line.cfg")
		self.game.set_sound_enabled(True)
		self.game.set_screen_resolution(ScreenResolution.RES_640X480)
		self.game.set_window_visible(True)
		self.game.init()

		shoot = [0,0,1]
		left = [1,0,0]
		right = [0,1,0]
		self.actions = [shoot, left, right]

	def run(self, agent):
	
		self.game.new_episode()
		state = self.game.get_state()
		img = state.screen_buffer
		w = processImage(img)
		s = numpy.array([w,w,w,w])

		totalReward = 0
		while True:
			# if render:#render env
			a = agent.act(s)

			r = 0
			# r, done = self.step(a)

			# state = self.game.get_state()
			# #img = state.screen_buffer
			action = [0,0,1]
			self.game.set_action(action)
			skiprate = FRAME_PER_ACTION
			self.game.advance_action(skiprate)

			game_state = self.game.get_state()  # Observe again after we take the action
			done = self.game.is_episode_finished()

			r = self.game.get_last_reward()
			img = game_state.screen_buffer
			s_ = numpy.array([s[3],s[2],s[1], processImage(img)])

			#reward shaping
			r = np.clip(r, -1, 1) 

			if done:
				s_ = None

			agent.observe([s, a, r, s_])
			agent.replay()

			s = s_
			totalReward += r

			if done:
				break
		print("Total reward:", totalReward)`

**Comment by mihahauke** [comment]
When game.is_finished() returns true 'None' is returned instead of a GameState object (as in [doc](https://github.com/mwydmuch/ViZDoom/blob/master/doc/DoomGame.md#getState)). You extract the state regardless of whether the game is finished and the error message looks like you had tried to access None.screen_buffer, is this the case?

**Comment by djbyrne** [comment]
Yeah thats correct. Upon further testing it looks like my episode is terminated and I am still trying to access the screen buffer even though the episode is over. I think I know how to fix this.

Thanks for your help :)

**Comment by jrizcallah** [comment]
Would you mind sharing how to fix it?

**Comment by Miffyli** [comment]
@jrizcallah 

As said above, you need to check if `game.is.finished()` before you try to access any items in the `GameState` (from `get_state()` function). If game is finished, the returned `GameState` will be `None` and there is no `screen_buffer` or other items to read.

If you are trying to wrap ViZDoom into a Gym environment, see [this for an existing implementation](https://github.com/alex-petrenko/sample-factory/blob/master/envs/doom/doom_gym.py).
