### ISSUE TITLE
PLease help me , not able to understand the error !

### ISSUE THREAD

**Issue by rshivansh** [mwydmuch/ViZDoom#274]
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x8

Generating vizdoom-crash.log and killing process 27454, please wait... 29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
Traceback (most recent call last):
  File "env_test.py", line 54, in <module>
    env.game_init()
  File "/new_data/gpu/shivansh/visual-grounding/DeepRL-Grounding/env.py", line 48, in game_init
    game.init()
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.

**Comment by Miffyli** [comment]
Please also include the created vizdoom-crash.log, in case that helps somebody to debug this issue.

Test if one of the example Vizdoom codes work (under `examples/python`). If examples work, then there might be something wrong with the code you try to run (e.g. Does not load freedoom2.wad, does not load the scenario file correctly, etc).

**Comment by rshivansh** [comment]
Thanks , actually i was able to solve the issue that time itself , forgot to close the issue !

**Comment by y12uc231** [comment]
@rshivansh : How did u resolve it? Coz my examples are also not working.

**Comment by rshivansh** [comment]
@y12uc231 Hey! Try adding this on line no. 59 in env.py 
   game.add_game_args("+vid_forcesurface 1")
I hope the game engine opens after that.
