### ISSUE TITLE
Spawning monsters and items according to state info

### ISSUE THREAD

**Issue by SriramS32** [mwydmuch/ViZDoom#276]
We would like to spawn monsters, health, and ammo at specified locations preferably from a text file or python script. What would be the best way to do this?

This is a similar question to #162 - I tried to send the puke command in a python script to call an ACS script that I added on the current map. Regardless of whatever the ACS script is doing (spawning monsters, giving the player a weapon, etc), nothing seems to happen but verbose debug indicates that the respective script is being checked. I was wondering why this was happening (maybe I'm missing a flag or some write protected issue). Is there a different way as well?

**Comment by mwydmuch** [comment]
Hi @SriramS32 ,
`puke` command is the only way right now to execute scripts on demand. If you share your .wad file, I can check what's wrong.

**Comment by SriramS32** [comment]
Thanks, I zipped up the `.cfg` and `.wad` files.
[doom_puke.zip](https://github.com/mwydmuch/ViZDoom/files/1685132/doom_puke.zip)

As for the python file, I pretty much used `spectator.py` and after `game.init()`, I did `game.send_game_command("puke 14")`.

**Comment by Miffyli** [comment]
The script spectator.py starts a new episode during each iteration of episodes, even the first one. You have to call your script *after* new episode starts. Calling `game.send_game_command("puke 14")` after `game.new_episode()` seems to work fine.
