### ISSUE TITLE
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.

### ISSUE THREAD

**Issue by y12uc231** [mwydmuch/ViZDoom#281]
I am getting this error even when I run the examples.

**Comment by mwydmuch** [comment]
Hi @y12uc231,
in case of this exception vizdoom-crash.log file should be created in you working directory. Could you paste its contents here?

**Comment by y12uc231** [comment]
Found the error : "dyld: Library not loaded: /usr/local/opt/jpeg/lib/libjpeg.8.dylib
  Referenced from: /anaconda3/lib/python3.6/site-packages/vizdoom/vizdoom
  Reason: image not found"

Its fixed now.

Thanks.
