### ISSUE TITLE
Issue running VIZdoom on remote server

### ISSUE THREAD

**Issue by soumikdasgupta** [mwydmuch/ViZDoom#282]
When I try to run the basic env test code given in the tutorial section, I am getting this error. What can be the possible reason for this?

AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0x8

Generating vizdoom-crash.log and killing process 8801, please wait... 29	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
Traceback (most recent call last):
  File "vizdoom_first_file.py", line 9, in <module>
    game.init()
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.

**Comment by mwydmuch** [comment]
Hello @soumikdasgupta,
vizdoom-crash.log should be created in working directory. Could you paste its contents here?

**Comment by soumikdasgupta** [comment]
Hi Marek,

Thank you for the reply. I was able to solve the problem by inserting

game.add_game_args("+vid_forcesurface 1")
before game.init()

Kind Regards,

Soumik.

On 12-Feb-2018 2:10 PM, "Marek Wydmuch" <notifications@github.com> wrote:

Hello @soumikdasgupta <https://github.com/soumikdasgupta>,
vizdoom-crash.log should be created in working directory. Could you paste
its contents here?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mwydmuch/ViZDoom/issues/282#issuecomment-364858144>,
or mute
the thread

**Comment by mwydmuch** [comment]
Good to hear that!
However, I have a quick question:
Do you run your code with `game.set_window_visible(True)`? Did you tried to set it to `False`?

**Comment by VladimirSlavic** [comment]
@mwydmuch is right. For anyone having these issues running vizdoom remote, the absolute first thing you should is disable the window and sound.
