### ISSUE TITLE
Linking Lua fails on Mac OS and Linux

### ISSUE THREAD

**Issue by BSVogler** [mwydmuch/ViZDoom#283]
After calling `make` it fails during linking:

> [ 96%] Linking CXX shared library bin/lua/vizdoom.dylib
> Undefined symbols for architecture x86_64:
>   "luabind::detail::(anonymous namespace)::cache::unknown", referenced from:
>       luabind::detail::cast_graph::impl::cast(void*, unsigned long, unsigned long, unsigned long, void const*) const in libluabind.a(inheritance.cpp.o)
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make[2]: *** [CMakeFiles/libvizdoom_lua.dir/build.make:149: bin/lua/vizdoom.dylib] Error 1
> make[1]: *** [CMakeFiles/Makefile2:146: CMakeFiles/libvizdoom_lua.dir/all] Error 2

Lua is installed via brew:
`Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio`

Mac OS 10.13.3 

I will gladly provide any missing information.

**Comment by mwydmuch** [comment]
Hi again @BSVogler and thank you for reporting!
This should be fixed now, however, Lua bindings are for Lua5.1 and LuaJIT (versions used by Torch), Lua5.2 and Lua5.3 may or may not work, CMake should try to find 5.1 first so check you CMake output and use a proper interpreter. Also, I recommend to use Torch and install ViZDoom via luarocks.
