### ISSUE TITLE
get_last_action while replaying lmp

### ISSUE THREAD

**Issue by nsavinov** [mwydmuch/ViZDoom#285]
Hi, I noticed the comment in https://github.com/mwydmuch/ViZDoom/blob/a3367d9dd59b47493a14606e19752e9ade639ba0/examples/python/record_episodes.py#L85

Is it still true? Is there any fundamental problem why it may be hard to implement? Is there any workaround I could use to get the last action?

**Comment by mwydmuch** [comment]
Hi @nsavinov,
this example is a little outdated, right now `get_last_action()` is partially supported for recordings, the states of the following keys can be recovered from the recording:

```
ATTACK
USE
JUMP
CROUCH
TURN180
ALTATTACK
RELOAD
ZOOM
SPEED
STRAFE
MOVE_RIGHT
MOVE_LEFT
MOVE_BACKWARD
MOVE_FORWARD
TURN_RIGHT
TURN_LEFT
LOOK_UP
LOOK_DOWN
MOVE_UP
MOVE_DOWN
LAND
LOOK_UP_DOWN_DELTA
TURN_LEFT_RIGHT_DELTA
MOVE_FORWARD_BACKWARD_DELTA
MOVE_LEFT_RIGHT_DELTA
MOVE_UP_DOWN_DELTA
```

**Comment by nsavinov** [comment]
Thanks!
