### ISSUE TITLE
vizdoom 1.1.5, out of sync

### ISSUE THREAD

**Issue by wzbbbb** [mwydmuch/ViZDoom#288]
I am using two physical machines. With this configurations:
1. 
`game.add_game_args("-host 2 -deathmatch +timelimit 10.0 " "+sv_forcerespawn 1 +sv_noautoaim 1 +sv_respawnprotect 1 +sv_spp
awnfarthest 1 +sv_nocrouch 1 " "+viz_respawn_delay 10 +viz_nocheat 1")`
2. 
`game.add_game_args("-join 192.168.0.19")`

Both machines configured as `mode = ASYNC_PLAYER`

Less then 1 minutes after the game started, both consols always show message like "out of sync with player xxx"
I have tried both wireless and physical cable.
Thanks!

**Comment by mwydmuch** [comment]
Hi @wzbbbb, thanks for reporting! 
It looks like the current master has some problems with synchronous multiplayer. I will investigate it later.
Right now you can try 1.1.4 version that should work or use async mode, where the game is processed at constant speed.
Use `game.set_mode(Mode.ASYNC_PLAYER)` to change mode to async and then `game.set_ticrate(ticrate)` can be used to set processing speed.

**Comment by wzbbbb** [comment]
I am fine with the 1.1.5, too lazy to switch back. :) 
I did not set the ticrate, hope the default rate is used during the match.

**Comment by mwydmuch** [comment]
Yes, default ticrate is just normal game speed, we used it in our competitions.

**Comment by mwydmuch** [comment]
Can't replicate the issue any more with current master, both async and sync multiplayer seems to work correctly. I'm closing this one for now.
