### ISSUE TITLE
A question about rocket launcher

### ISSUE THREAD

**Issue by wzbbbb** [mwydmuch/ViZDoom#289]
Quite often, after the player picks up a rocket launcher, he can not fire right away. Only after like 10 seconds, it can start to shoot. What's the issue? Is "reload" required?
Thanks!

**Comment by mwydmuch** [comment]
10 seconds? Are you sure about this? There is weapon swapping animation on pick up, during which player can't shoot, but it takes only a dozen ticks, about half a second.

**Comment by wzbbbb** [comment]
Yes, I have seen this many times. I think it is in fact longer than 10 seconds. I have seen it both in the rocket launcher stage 01, and other stages on the unknow maps.

**Comment by mwydmuch** [comment]
My quick test doesn't replicate the issue, so as in case of #288, I'll investigate this more deeply later.
The only reason I can think of is the quite particular situation.
Player ran out of ammo, but it keeps the attack button pressed. 
Then it picks up additional ammunition, the attack button needs to be released and press again to start firing again. That how Doom engine works unfortunately.

**Comment by mwydmuch** [comment]
I guess it would be nice if we would change that.

**Comment by wzbbbb** [comment]
Hmm, make sense. I have never tried that. If I am able to try that I will update the ticket.

**Comment by michaelkrax** [comment]
There is a noautofire flag for weapons https://zdoom.org/wiki/Weapon_flags

From a (human) play perspective this is as far as I know mainly to avoid you run backwards over a rocket launcher in a fight while holding down the fire button for a permanent fire weapon (chaingun or plasma rifle) and you kill yourself with splash when auto switch weapons is on and you suddenly switch to rockets.

Both the rocket launcher and the BFG have the flag https://zdoom.org/wiki/Classes:DoomWeapon

**Comment by wzbbbb** [comment]
@michaelkrax @mwydmuch That explains it. Thank you!
