### ISSUE TITLE
Using set_available_game_variables() method

### ISSUE THREAD

**Issue by chandsrahul** [mwydmuch/ViZDoom#292]
In Python what should be the arguments for set_available_game_variables() method?  
For example if I want to set GameVariable.HEALTH  to a custom value using the above method how should I call the function?

**Comment by Miffyli** [comment]
`DoomGame.set_available_game_variables` only defines which existing game variables are available in the `GameState.game_variables`. You can not modify existing game variables with this.

To create/modify game variables you can either:
a) Use the existing ones and modify them as you please in Python (e.g. Normalize health with Health/100), or
b) Define custom GameVariable `USER#` (e.g. `USER1`) by modifying the scenario WAD file and defining it in the ACS code. You can see examples of this by opening scenarios in ViZDoom/scenarios folder in SLADE editor and checking the "SCRIPT" entries. For example: In health_gathering_supreme.wad, the script defines `global int 1;shaping_reward;` at line 4. This variable will be visible to the Python script via `GameVariable.USER1` game variable, and you can see from the script how it is modified (indicates if player picks up poison/health). The variable `global int 0;reward;` is a special case, defining the reward signal you get by default from e.g. `DoomGame.make_action`.

**Comment by chandsrahul** [comment]
Thanks for the reply.
When I change the existing game variable HEALTH in health_gathering scenario using 
**GameVariable.HEALTH =50**  this change does not reflect in the game, that is if I call **state.game_variables**  after  the above line the returned value is 100 and not 50. 

Is there a way to change existing game variables such that it reflects on the game without modifying scenario WAD file?

**Comment by Miffyli** [comment]
GameVariables are only designed to be read-only and you can not modify the state via them (as far I am aware).

Unfortunately to change these values you need to do it via console commands or by modifying the scenario file. You can modify some interesting CVARs (Console VARiable) via `set` command (info here: https://zdoom.org/wiki/CVARs ), and you can also trigger scenario functions via [puke](https://zdoom.org/wiki/CCMDs:Debug) command. Ultimately some things have to modified in the scenario file, but it is much simpler than it sounds. I urge you to give it a try by taking a peek at example scenarios :)
