### ISSUE TITLE
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

### ISSUE THREAD

**Issue by rasoolfa** [mwydmuch/ViZDoom#293]
Hi, 

I have been getting this error whenever run a code that uses ViZDoom:
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"

Does cause any instability in ViZDoom? Or I can just simply ignore it?

Thanks

**Comment by mihahauke** [comment]
If you don't need sound you can ignore it.

**Comment by rasoolfa** [comment]
I don't need sound. Thanks for your comment.

**Comment by LinxiFan** [comment]
I'm also getting this error message, but my code works just fine. I don't need audio either.
Is there anyway to turn this message off?

**Comment by Miffyli** [comment]
As mentioned, the error does not really affect anything and you can ignore it, if you do not need sound. You could try directing stderr and stdout of vizdoom with `add_game_args` (i.e. `game.add_game_args("1> /dev/null 2> /dev/null")`), but I am not sure if this work (not able to test right now).

**Comment by anuragM239** [comment]
is "pulse" over here a signal or what is it?
