### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by XMaster96** [mwydmuch/ViZDoom#295]
System: Win 7 64bit
Python 3.6

I tried to pip install VizDoom, and a got this error back.
```

Collecting vizdoom
  Using cached vizdoom-1.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\JAN\AppData\Local\Temp\pip-build-dpfcisa6\vizdoom\setup.py", line 14, in <module>
        raise RuntimeError("Building pip package on Windows is not currently available ...")
    RuntimeError: Building pip package on Windows is not currently available ...
```

**Comment by mihahauke** [comment]
Just like the error says.... we do not have a windows pip package yet cause honestly working with wondows brings us lots of pain and suffering.... you need to download the binaries from the releases section.

Or if you are brave enough you can compile it yourself but .... it's a bad idea. Pain and suffering... pain and suffering...

**Comment by Miffyli** [comment]
As an extra to mihahaukses comment: Here are some step-by-step instructions how to install Vizdoom on Windows (could be considered dirty)

1) Download pre-built windows package from Github here: https://github.com/mwydmuch/ViZDoom#windows-build
2) Extract it where-ever you like to store your VizDoom stuff
3) Copy contents of "vizdoom" directory to "[python install dir]\Lib\site-packages". E.g "C:\Python35\Lib\site-packages"
4) Open Python and try following:

import vizdoom
game = vizdoom.DoomGame()
game.init()

If this works, then your vizdoom installation should work fine.

**Comment by mwydmuch** [comment]
Hi @XMaster96,
as @mihahauke said and @Miffyli explained in detail, it's a good idea to use already compiled package for windows.
If you would like to build it yourself (what is not that terrible and painful) see `cmake_all.bat` script, which will do most of the work for you. Note: Visual Studio 2015+ is required.

**Comment by michaelkrax** [comment]
Hello XMaster96 I wrote an extensive guide on Window installing and how to use Docker for Window (if you need that, too).

Link: https://www.michaelkrax.com/blog/how-to-run-vizdoom-on-windows-10/

**Comment by XMaster96** [comment]
thanks, for all your help.
I got it running.  :)
