### ISSUE TITLE
mac install error

### ISSUE THREAD

**Issue by wwxFromTju** [mwydmuch/ViZDoom#298]
Hey, when I try to install vizdoom from source in my mac, some err happen:

 89%] Linking CXX executable ../../../bin/vizdoom.app/Contents/MacOS/vizdoom
Undefined symbols for architecture x86_64:
  "_jpeg_CreateDecompress", referenced from:
      FJPEGTexture::MakeTexture() in jpegtexture.cpp.o
      FJPEGTexture::CopyTrueColorPixels(FBitmap*, int, int, int, FCopyInfo*) in jpegtexture.cpp.o
  "_jpeg_destroy_decompress", referenced from:
      FJPEGTexture::MakeTexture() in jpegtexture.cpp.o
      FJPEGTexture::CopyTrueColorPixels(FBitmap*, int, int, int, FCopyInfo*) in jpegtexture.cpp.o
  "_jpeg_finish_decompress", referenced from:
      FJPEGTexture::MakeTexture() in jpegtexture.cpp.o
      FJPEGTexture::CopyTrueColorPixels(FBitmap*, int, int, int, FCopyInfo*) in jpegtexture.cpp.o
  "_jpeg_read_header", referenced from:
      FJPEGTexture::MakeTexture() in jpegtexture.cpp.o
      FJPEGTexture::CopyTrueColorPixels(FBitmap*, int, int, int, FCopyInfo*) in jpegtexture.cpp.o
  "_jpeg_read_scanlines", referenced from:
      FJPEGTexture::MakeTexture() in jpegtexture.cpp.o
      FJPEGTexture::CopyTrueColorPixels(FBitmap*, int, int, int, FCopyInfo*) in jpegtexture.cpp.o
  "_jpeg_resync_to_restart", referenced from:
      FLumpSourceMgr::FLumpSourceMgr(FileReader*, jpeg_decompress_struct*) in jpegtexture.cpp.o
      FLumpSourceMgr::FLumpSourceMgr(FileReader*, jpeg_decompress_struct*) in jpegtexture.cpp.o
      FJPEGTexture::MakeTexture() in jpegtexture.cpp.o
      FJPEGTexture::CopyTrueColorPixels(FBitmap*, int, int, int, FCopyInfo*) in jpegtexture.cpp.o
  "_jpeg_start_decompress", referenced from:
      FJPEGTexture::MakeTexture() in jpegtexture.cpp.o
      FJPEGTexture::CopyTrueColorPixels(FBitmap*, int, int, int, FCopyInfo*) in jpegtexture.cpp.o
  "_jpeg_std_error", referenced from:
      FJPEGTexture::MakeTexture() in jpegtexture.cpp.o
      FJPEGTexture::CopyTrueColorPixels(FBitmap*, int, int, int, FCopyInfo*) in jpegtexture.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/vizdoom.app/Contents/MacOS/vizdoom] Error 1
make[1]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
make: *** [all] Error 2

Thx for your help.

**Comment by mwydmuch** [comment]
Hello @wwxFromTju,
Do you have libjpeg installed in you system (you can install it via brew `brew install libjpeg`)?
Also, this issue looks similar to yours: https://github.com/scantailor/scantailor/issues/103.

**Comment by wwxFromTju** [comment]
@mwydmuch I fix it: 

change cmake(brew) to cmake(system) in cmake_all.sh, than it can work.

But I don't clean know why it can work.
