### ISSUE TITLE
PyOblige installation failed

### ISSUE THREAD

**Issue by wzbbbb** [mwydmuch/ViZDoom#299]
`
pip install git+https://github.com/mwydmuch/PyOblige
Collecting git+https://github.com/mwydmuch/PyOblige
  Cloning https://github.com/mwydmuch/PyOblige to /tmp/pip-_p_rvxui-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-_p_rvxui-build/setup.py", line 44, in <module>
        package_dir={'pyoblige': package_path},
    NameError: name 'package_path' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_p_rvxui-build/
`

Ubuntu 16.04.4 LTS

**Comment by mihahauke** [comment]
Sorry but it was a stub... The file is updated now and should work. 
`sudo pip3 install oblige` shoould work as well.
For future, please post issues with oblige on the oblige repo.

**Comment by wzbbbb** [comment]
@mihahauke I put it here because it is an issue with PyOblige.
`sudo pip3 install oblige` did not work either.

**Comment by mihahauke** [comment]
Well, by oblige I meant this repo: https://github.com/mwydmuch/PyOblige

What is the error you are getting?

**Comment by wzbbbb** [comment]
I will try again, and post in the error tonight.

**Comment by wzbbbb** [comment]
@mihahauke The issue is fixed. Thanks!
