### ISSUE TITLE
labels.py gives AttributeError

### ISSUE THREAD

**Issue by johny-c** [mwydmuch/ViZDoom#300]
Hi,

When trying to run the `labels.py` example, I get:

`AttributeError: 'vizdoom.vizdoom.Label' object has no attribute 'x'`

coming from line 90:

  `draw_bounding_box(screen, l.x, l.y, l.width, l.height, doom_blue_color)`

I'm running on Ubuntu 16.04 and installed vizdoom from pip. 
Access to `object_position_[x,y,z]` attributes works fine.

**Comment by mwydmuch** [comment]
Hello @johny-c,
Label object presented in labels.py contains new fields added in 1.1.5 version, that waits for release. There is a bug in sync-multiplayer appeared in this version, and I've been recently too busy <lazy> to fix it :/. However if you don't need this functionality right now, you can install 1.1.5 via pip using this command: `pip install git+https://github.com/mwydmuch/ViZDoom`.

**Comment by johny-c** [comment]
Hi @mwydmuch , 
I didn't realize these were new fields. Thanks for the reply.
