### ISSUE TITLE
Projection matrix

### ISSUE THREAD

**Issue by edbeeching** [mwydmuch/ViZDoom#303]
Hello,

I am interested in knowing the projection matrix used for the different resolution options in the game.
Would you be able to point me in the right direction?

Many thanks!

**Comment by mihahauke** [comment]
Well .... I am not sure if that is the case and if there is any projection matrix. Doom's engine is not strictly 3D and it doesn't use modern approach to 3D rendering. There were lots  of clever tricks to make the 2.5 even happen.

As for different resolutions I think it's simply upscaled from the base resolution and lower resolutions just use downscaling aaaand some other magic. 

Any thoughts @mwydmuch ?

**Comment by edbeeching** [comment]
Thank you for your reply.

In this paper (4.3 mapping) they mention they get the a matrix from the
VizDoom config file https://arxiv.org/pdf/1612.00380.pdf
But I have not managed to find the file yet, assuming it exists!

Any assistance is much appreciated.

**Comment by Miffyli** [comment]
As far I am aware there is no direct way of getting "projection matrix" for ZDoom (if it even uses one).

However I imagine they something like this:
* Get player (camera) position from GameVariables.
* Get aim angles (pitch/yaw) from GameVariables. Up is always (0,1,0)
* Calculate field-of-view from resolution. This is 90 degrees for 4:3 resolutions, higher for wider-screen resolution: https://zdoom.org/wiki/FOV

With these ingredients you should be able to construct the projection matrix "used" for rendering the image in ViZDoom. You can find information about building this matrix all around web via googling. This seems to cover what you need: https://www.scratchapixel.com/lessons/3d-basic-rendering/perspective-and-orthographic-projection-matrix/building-basic-perspective-projection-matrix (minus rotation)

**Comment by edbeeching** [comment]
@Miffyli 
Thank you for taking the time to write such a detailed reply.

Following your advice I have managed to approximate an inverse perspective projection.

Much appreciated!

**Comment by Miffyli** [comment]
@edbeeching 

Glad to hear at least something grew out of my babbling ^^.

Would you be kind enough to share what you have built? Could be an interesting addition to ViZDoom repository as well (e.g. "You can build the perspective projection matrix with...").

**Comment by hbonnavaud** [comment]
@edbeeching can you give me the matrix please? It could save me some time.
