### ISSUE TITLE
Text levels?

### ISSUE THREAD

**Issue by agiantwhale** [mwydmuch/ViZDoom#308]
Hi,

Are there any plans to add text level feature like in DeepMind Lab? It would simply map generation process for those working on navigation problems.

Thanks,
Jae

**Comment by mwydmuch** [comment]
Hello @agiantwhale,
we don't plan it, if there is a need to prepare maps, nice and easy to use editors are available.
If you want to generate maps automatically, you can use this nice library https://github.com/devinacker/omgifol to generate new or manipulate existing Doom wads from Python.

**Comment by agiantwhale** [comment]
I am taking a jab at it, but it's quite a difficult task. I will update if I submit a PR if I get something usable working.

**Comment by agiantwhale** [comment]
Thank you for the fix!

I am planning to add ACC script functionality to the hacky script. This will be helpful for setting custom rewards for running into walls / respawn on arrival at goal. I will post again once I have it working, and then maybe I can work on cleaning the code up.

**Comment by agiantwhale** [comment]
I've worked on something crude and is currently using it:

https://github.com/agiantwhale/navdoom

**Comment by mwydmuch** [comment]
Awesome work guys!
I linked to it in our README.md and FAQ.md. Would be great to add README.md also to NavDoom.

**Comment by Miffyli** [comment]
Note for anybody looking this in future: Check [MazeExplorer](https://github.com/microsoft/MazeExplorer)
