### ISSUE TITLE
Why i am always getting the 'Health' negative? Does it mean my model is not converging?

### ISSUE THREAD

**Issue by adil25** [mwydmuch/ViZDoom#310]
Hello every one,
                          I am training my model on 'health gathering scenario'. i want to get the average_health so for that i am reading the health but i am always getting the health negative (below zero), why? could it be a reason of not converging the model? i am not sure. In fact in another file i was training the model for the same scenario using DRQN and i was getting the health always positive above 50, but not in the case of A3C. Also, my agent cant die always.  can someone help me where am i wrong. Thanks in advance..........

**Comment by Miffyli** [comment]
Can you share the code you are using to read the health and the version of ViZDoom you are running? 

In some cases you have to (or had to, I think this was updated) to use functions like `vizdoom.doom_fixed__to_double` to convert the value from Doom's fixed point values to floats Python understands.
