### ISSUE TITLE
How can I get the bird-eye view of the map?

### ISSUE THREAD

**Issue by andrewliao11** [mwydmuch/ViZDoom#313]
as shown in the gif in the README.md
![](https://camo.githubusercontent.com/98a1b7f2946bb2f8f38cf61146d2db30634d7a63/687474703a2f2f7777772e63732e7075742e706f7a6e616e2e706c2f6d6b656d706b612f6d6973632f76697a646f6f6d5f676966732f76697a646f6f6d5f636f727269646f722e676966)

How can I get the bird-eye view of the map?

**Comment by Miffyli** [comment]
See [automap.py example](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/automap.py).

**Comment by andrewliao11** [comment]
thanks!
