### ISSUE TITLE
Issue with get_episode_time?

### ISSUE THREAD

**Issue by gian1312** [mwydmuch/ViZDoom#314]
Hi all
Is there an Issue with the get_episode_time function or am I accessing it wrong?
I get following error.
`object has no attribute 'get_episode_time'
Are there any examples with this function and with the uservariable function?
Thank you

`

**Comment by Miffyli** [comment]
```python
import vizdoom
game = vizdoom.DoomGame()
game.init()
print(game.get_episode_time())
```
This works fine for me and returns "1". This works too:
```python
state = game.get_state()
print(state.number)
```
You can examples of the latter in e.g. [basic.py example](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/basic.py)

As for game variables: You can either do what is done in above example, or you can also get them by e.g:

```python
health = game.get_game_variable(vizdoom.GameVariable.HEALTH)
```
