### ISSUE TITLE
Unexpected ViZDoom instance crash

### ISSUE THREAD

**Issue by VladimirSlavic** [mwydmuch/ViZDoom#318]
After about 1679 episodes, also noting this has happened multiple times, i get an unexpected vizdoom crash. Im using the 'defend_the_center.cfg' file via the load_config(). it breaks down when i use the advance_action() function. The skip rate is 4. Has anyone encountered anything similar before or perhaps give me a direction in which to look in.

Traceback (most recent call last):
  File "/home/vladimir/vizdoom_reinf/defend_the_center_main.py", line 19, in <module>
    controller.train()
  File "/home/vladimir/vizdoom_reinf/controllers/RecurrentController.py", line 205, in train
    self.environment.make_action(action.tolist())
  File "/home/vladimir/vizdoom_reinf/environment/Environment.py", line 74, in make_action
    self.game.advance_action(self.skip_rate)
vizdoom.vizdoom.ViZDoomErrorException: Unexpected ViZDoom instance crash.

**Comment by Miffyli** [comment]
This could be a scenario-dependent issue. I have been running same ViZDoom processes for tens of thousands of episodes on same scenario (simpler ones mostly, e.g. basic.wad and simpler_basic.wad), and I have not experienced such crashes. Using ViZDoom 1.1.4 on Ubuntu 16.04 and Python 3.5.

For the time being you could wrap ViZDoom calls into try-excepts and reboot ViZDoom when necessary. 
You may need to recreate ViZDoom instances during long runs as the library seems to be leaking small amounts of memory. I see 20GB increased usage in memory after ~150h of running 32 ViZDoom instances.

**Comment by VladimirSlavic** [comment]
I had realized, although its not such a bad problem. With the model saved it just reruns and continues on. Thank for the feedback though, highly appreciated and easing knowing i hadn't screwed something up.

Cheers mate

**Comment by mwydmuch** [comment]
Hi @VladimirSlavic,
please post vizdoom-crash.log file that should be created in you working directory when crash happened.

and hi @Miffyli,
I will try to look into this memory leak. Thanks for reporting!
