### ISSUE TITLE
cannot build vizdoom with python 3

### ISSUE THREAD

**Issue by glample** [mwydmuch/ViZDoom#324]
Hi, I'm facing an issue when trying to install ViZDoom with Python 3:

```
guismay@devfair0153:~/ViZDoom$ make -j48
[  1%] Downloading freedoom2.wad
[  2%] Built target arithchk
[  2%] Built target lemon
[  2%] Built target updaterevision
[  4%] Built target re2c
[  6%] Built target freedoom2
[  7%] Built target lzma
[  8%] Built target qnan
[ 18%] Built target gme
[ 21%] Built target zipdir
[ 29%] Built target gdtoa
[ 33%] Built target dumb
[ 36%] Built target libvizdoom_static
[ 37%] Built target libvizdoom_shared
[ 37%] Built target libvizdoom_python

[ 37%] Linking CXX executable ../../../bin/vizdoom
CMakeFiles/vizdoom.dir/tempfiles.cpp.o: In function `FTempFileName::FTempFileName(char const*)':
tempfiles.cpp:(.text+0x7): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/private/home/guismay/anaconda3/lib/libharfbuzz.so.0: undefined reference to `FT_Get_Var_Blend_Coordinates'
collect2: error: ld returned 1 exit status
src/vizdoom/src/CMakeFiles/vizdoom.dir/build.make:8921: recipe for target 'bin/vizdoom' failed
make[2]: *** [bin/vizdoom] Error 1
CMakeFiles/Makefile2:937: recipe for target 'src/vizdoom/src/CMakeFiles/vizdoom.dir/all' failed
make[1]: *** [src/vizdoom/src/CMakeFiles/vizdoom.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I spent a lot of time trying to fix it, but without success. I started from a fresh Anaconda installation but it looks like some packages inside have been modified and I cannot install VizDoom anymore :/

Any ideas?

Thank you

**Comment by glample** [comment]
Okay well I found a solution just after asking, so in case someone else has the same problem, the fix was just to run `conda remove harfbuzz` first, and then I was able to install it using the simple way
`pip install git+https://github.com/mwydmuch/ViZDoom` :)

**Comment by MattiasM80** [comment]
We're you able to actually use vizdoom too? I get an exception on game.init() .

**Comment by MathematicalModels** [comment]
> Okay well I found a solution just after asking, so in case someone else has the same problem, the fix was just to run `conda remove harfbuzz` first, and then I was able to install it using the simple way
> `pip install git+https://github.com/mwydmuch/ViZDoom` :)

Thank you so much for the solution, I encountered the same problem.
