### ISSUE TITLE
how to get information indicating the agent hits the wall?

### ISSUE THREAD

**Issue by qyxqyx** [mwydmuch/ViZDoom#330]
If there some flags or information indicating the agent hits the wall？I want to know whether the agent hits the wall，and design reward function for the agent can avoid hitting wall.

**Comment by Miffyli** [comment]
As far I am aware there is no such thing conveniently available when I was implementing similar reward signal.

As a work-around I used mix of depth map to see if there is an object too close (on middle horizontal line) and if character is moving when movement buttons are pressed. It is not perfect and produces some "false-alarms", but it did improve upon just rewarding "move as fast as possible".
