### ISSUE TITLE
player_names truncated to 16 characters

### ISSUE THREAD

**Issue by spMohanty** [mwydmuch/ViZDoom#331]
In the python API, If we get the list of player names by : 
```python
serverState = game.get_server_state()
player_names = serverState.players_names
print(player_names)
```
then the individual `player_names` are truncated to 16 characters. 

I would expect this limit to be higher, maybe 32 or something ?
For example, an agent name like : `SampleRandomAgent` exceeds the limit already.

**Comment by spMohanty** [comment]
Also, in case of multiple agents, the agent names seems to be concatenated : 

```
serverState = game.get_server_state()
player_names = serverState.players_names
print(player_names)
```
```
['ghost', 'SampleRandomAgeMSampleRandomAgeNSampleRandomAgeO', 'SampleRandomAgeNSampleRandomAgeO', 'SampleRandomAgeO', '', '', '', '', '', '', '', '', '', '', '', '']
```

The agent names in the game were : 
* `SampleRandomAgeO`
* `SampleRandomAgeN`
* `SampleRandomAgeM`

**Comment by mwydmuch** [comment]
Thanks @spMohanty, fixed.
