### ISSUE TITLE
Windows python build for 1.1.6?

### ISSUE THREAD

**Issue by jacobcoughenour** [mwydmuch/ViZDoom#343]
Are there any builds of 1.1.6 or later for python3.6 windows out there?

I've been using the 1.1.5pre windows binaries for python3.6 from the releases tab for a while.  I'd like to update to 1.1.6 or later to use some of the new features.

Trying to build it myself, I'm stuck on cmake not finding the boost libs even when I have the path set and everything.

**Comment by Miffyli** [comment]
@mwydmuch 
Could this be done? I haven't had success compiling Windows binaries either :|

@jacobcoughenour  
What are the specific features you'd like to have from 1.1.6? If it is some of the new GameVariables, you can manually read information via scenario's ACS scripts and `USER#` variables.

**Comment by jacobcoughenour** [comment]
@Miffyli 
I'd like to get a bounding box for each object via the labels list in GameState.  1.1.5pre labels only have the position (x,y) but 1.1.6 has width and height.
https://github.com/mwydmuch/ViZDoom/blob/master/doc/Types.md#label

**Comment by Miffyli** [comment]
Ah yes, indeed this would be a handy feature to have.

Meanwhile I used a combination of `np.argmax` and `np.argmin` on `np.where(state.labels_buffer == object.object_id)`. Not probably as fast, but it did the job. I do not have the code with me right for copy/pasting.

**Comment by jacobcoughenour** [comment]
@Miffyli 
I got your temporary solution working. (object.object_id should be object.value)
Thanks!

**Comment by mwydmuch** [comment]
Pretty late, but I've finally rebuild Windows binaries: https://github.com/mwydmuch/ViZDoom/releases/tag/1.1.7.
