### ISSUE TITLE
Cannot run multiplayer game as background process (e.g., with nohup)

### ISSUE THREAD

**Issue by pengsun** [mwydmuch/ViZDoom#344]
Hi, 
It seems that the multiplayer game cannot run as background processes. 
An easy way to reproduce this issue is to run the the `ViZDoom/examples/python/multiple_instances.py` with nohup:
```
nohup python multiple_instances.py &
```

By watching `nohup.out`, we find that the two players seem to wait each other on and on when init the game (the two processes seem not able to see each other?).

**Comment by Miffyli** [comment]
Indeed it does not seem to work, both instances get stuck at `Press 'Q' to abort network game synchronization.` for me (Ubuntu 16.04, Python 3.5, ViZDoom 1.6).

Using `screen` or `tmux` to run multiple instances works as expected though, which I have been using for multi-agent experiments. Not as elegant as `nohup`, but it does the job. I use following to create `screen` which kills itself after code finishes:

`screen -dm python3 multiple_instances.py`

**Comment by pengsun** [comment]
Thanks @Miffyli ! Currently we also use tmux as work-around, just curious why running as background process doesn't work...
