### ISSUE TITLE
How to (re)spawn at random points in a multiplayer game?

### ISSUE THREAD

**Issue by pengsun** [mwydmuch/ViZDoom#345]
Hi, how to (re)spawn at random points in a multiplayer game? E.g., in the map given in `cig.cfg`, how to  let the player (re)spawn on each life? Shall we edit the python code or the ACS script?

**Comment by Miffyli** [comment]
You can add spawnpoints ("Deathmatch Start") in scenario editor (e.g. SLADE), and in `-deathmatch` mode the game will spawn players in one of these spawnpoints at random.

**Comment by pengsun** [comment]
I see, that means `-deathmatch` ensures the random spawning, right?

**Comment by Miffyli** [comment]
`-deathmatch´ starts the game in Deathmatch mode, in which players spawn at random locations (note that some variables like `sv_spawn_furthest 1` affect this though). It does spawn player at random locations, but truth to be told I have not made sure it is uniform / always random. It could be "random enough" for video-game use.
