### ISSUE TITLE
File "deadly_corridor.cfg" does not exist

### ISSUE THREAD

**Issue by lisend** [mwydmuch/ViZDoom#348]
### Issues
def create_environment():
    game = DoomGame()
    
    # Load the correct configuration
    game.load_config("deadly_corridor.cfg")
    
    # Load the correct scenario (in our case deadly_corridor scenario)
    game.set_doom_scenario_path("deadly_corridor.wad")
    
    game.init()

    # Here we create an hot encoded version of our actions (5 possible actions)
    # possible_actions = [[1, 0, 0, 0, 0], [0, 1, 0, 0, 0]...]
    possible_actions = np.identity(7,dtype=int).tolist()
    
    return game, possible_actions

I was trying to set up the environment using this function, but I got an error saying that FileDoesNotExistException: File "deadly_corridor.cfg" does not exist.

When I looked into the scenarios directory, the file is actually in there. I tried to paste all the cig file out from the scenarios directory into the vizdoom directory, but it didn't work neither.

I'm using ViZDoom-1.1.5pre-Win-Python36-x86_64.

Thanks!

**Comment by Miffyli** [comment]
`DoomGame.load_config` and `DoomGame.set_doom_scenario_path` take either absolute or relative paths to the files. I.e. if you call `game.load_config("deadly_corridor.cfg")`, code attempts to read file `deadly_corridor.cfg` in the current working directory, which is the same directory as your Python code. 

Provide full/absolute path to the scenario/config file, or copy the files next to your code. That should do the trick.

**Comment by lisend** [comment]
Thanks, it works for me now
