### ISSUE TITLE
First 8 actions ignored

### ISSUE THREAD

**Issue by ankitkv** [mwydmuch/ViZDoom#350]
Under what circumstances would the first 8 episodes of an episode be ignored by ViZDoom? The game state doesn't change at all in response to forward/turn actions. The game suddenly responds appropriately after those first few tics. Any idea what could be going on?

**Comment by mihahauke** [comment]
Are you sure it's only about the first 8 ticks? Doom has some inertia so the movement is not instant so perhaps it is that?

**Comment by ankitkv** [comment]
Yeah. Although this does not happen with the examples provided with ViZDoom, so it doesn't sound like a general issue. However, I've tried dealing with game configurations and commenting off my ACS code (I have an extremely simple script to move delta amounts forward), and no obvious suspects.

**Comment by ankitkv** [comment]
Huh, interesting. The `delta_buttons.py` example provided with ViZDoom has the same issue. For the first 8 tics, the only action that takes is `LOOK_UP_DOWN_DELTA`. If you set that to 0, nothing moves for the first 8 tics and then things start moving. So is this expected behavior? Why does up down work but not turns or motion?

**Comment by Miffyli** [comment]
Could it be `episode_start_time` affecting the results? When player spawns, there is small delay before player can start to move around where the character rises the weapon. The example scenarios set `episode_start_time` so that it skips this delay and agent can start controlling the player from the first tick.

**Comment by ankitkv** [comment]
Thanks! That definitely solves my problem. It is still weird that some actions work and some don't during those initial tics, but I suppose that's a Doom thing.
