### ISSUE TITLE
Map change causes overlay messages

### ISSUE THREAD

**Issue by ankitkv** [mwydmuch/ViZDoom#352]
I created my own WAD with multiple maps. When I use `game.set_doom_map` to switch to a new map, the subsequent frames include an overlay message as follows:
![test_image](https://user-images.githubusercontent.com/3175634/48377208-2df2b400-e69b-11e8-80b6-468e83f52c1e.png)

How do I get rid of this?

**Comment by Miffyli** [comment]
That looks like some kind of splash message a custom multiplayer level could show. Did you use some existing multiplayer levels and put them together into one WAD? 

I haven't personally had such issues, but I have always used WADs with ViZDoom or ones built from scratch.

**Comment by ankitkv** [comment]
The WAD is generated by NavDoom (https://github.com/agiantwhale/NavDoom). I'm also having trouble replaying recorded episodes. It is randomly off by one or two frames. Is this because this is somehow being treated as a multiplayer level? If so, what makes it a multiplayer level and how do I turn that off?

**Comment by Miffyli** [comment]
Hmm last time I tried out NavDoom it worked fine, albeit I think I didn't check for problems like this. The replays could be off because of the same reason. Map does not decide if it is multiplayer or not, but some Things like "deatmatch_spawn" require multiplayer game to function (`-deathmatch` in game arguments).

@agiantwhale
Do you happen to be around to throw your opinion here?

**Comment by ankitkv** [comment]
Is there a right way to change a map within a WAD? If I close the game and init it for every map, I don't see that screen.

**Comment by Miffyli** [comment]
`DoomGame.set_doom_map` should work fine as long you do it between episodes, but there is nothing wrong with creating new ViZDoom process (other than the overhead from launching the game again).

**Comment by ankitkv** [comment]
I see the same issue with freedom2.wad. As I change maps, I get the splash screen as a part of my screen buffer.

**Comment by Miffyli** [comment]
I was not able to get any additional texts with freedoom2.wad and ViZDoom 1.1.6 (changed map with `set_doom_map` before episode reset, and recorded the first 10 frames).

**Comment by ankitkv** [comment]
Recreating the _vizdoom.ini file fixed the issue for me. Unfortunately, I did that yesterday before seeing that comment and lost the old file, so I'm not sure which config option was responsible.
