### ISSUE TITLE
Windows release of latest source code

### ISSUE THREAD

**Issue by acrushdjn** [mwydmuch/ViZDoom#360]
I tried to use CAMERA_POSITION_X、CAMERA_POSITION_Y in my python code：
`CAMERA_POSITION_X = self.game.get_game_variable(GameVariable.CAMERA_POSITION_X)
        CAMERA_POSITION_Y = self.game.get_game_variable(GameVariable.CAMERA_POSITION_Y)`
but it doesn't work, then I get to know these 2 features were added recently, which are not implemented in the windows release provided, can anyone provide the windows release of latest source code?

Thanks!

**Comment by mwydmuch** [comment]
Hello @acrushdjn,
I've added prebuild Windows binaries for Python 2.7, 3.6 and 3.7 for the latest release: https://github.com/mwydmuch/ViZDoom/releases/tag/1.1.7.

**Comment by acrushdjn** [comment]
@mwydmuch Great! thanks for the work!

**Comment by acrushdjn** [comment]
@mwydmuch Can we have the windows binaries for Python 3.5?

**Comment by mwydmuch** [comment]
Sure, I've added build for Python 3.5 to the release.
