### ISSUE TITLE
How to get position of bot

### ISSUE THREAD

**Issue by acrushdjn** [mwydmuch/ViZDoom#361]
Hi, I used layers to get position of bots, but that's only possible when bots are in my VIEW, is there any method to get position(x, y, z) of bots anytime?

**Comment by acrushdjn** [comment]
Below is my code for gettting position of bots when they are in my VIEW
`for l in labels:
                if l.object_name == "DoomPlayer" and l.object_id != 0:
                    enemy_in_view = 1.0
                    enemy_position_x = l.object_position_x
                    enemy_position_y = l.object_position_y
                    enemy_position_z = l.object_position_z
                    enemy_angle = l.object_angle
                    enemy_pitch = l.object_pitch
                    enemy_roll = l.object_roll
                    enemy_velocity_x = l.object_velocity_x
                    enemy_velocity_y = l.object_velocity_y
                    enemy_velocity_z = l.object_velocity_z`

**Comment by acrushdjn** [comment]
@mwydmuch Great! I really want the function of getting bot's position at anytime

**Comment by mwydmuch** [comment]
@acrushdjn, I will have time to add this and #362 on Thursday :)

**Comment by acrushdjn** [comment]
@mwydmuch Great! thanks

**Comment by mwydmuch** [comment]
I've added the option to include information about objects into GameState. This example shows how to use it: https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/objects_and_map.py.
I still need to think a little about the format of map data and I will also add it to GameState soon.

You can easily install it on Unix using pip:
```
pip uninstall vizdoom
pip install git+https://github.com/mwydmuch/ViZDoom
```
