### ISSUE TITLE
Position of obstacles

### ISSUE THREAD

**Issue by acrushdjn** [mwydmuch/ViZDoom#362]
Hi, is there a way to get the positions(x, y, z) of obstacles? thanks.

**Comment by Miffyli** [comment]
What do you mean specifically with "obstacles"? Do you mean Things you can collide with (e.g. pilars)? 

To best of my knowledge the best way to do this is to modify map's ACS scripts to store information about objects to "USER#" GameVariables, but this could get tricky. Checking what label map has also works, but only for objects in the (roughly) line of sight.

**Comment by acrushdjn** [comment]
@Miffyli obstacles, I mean objects like walls which are blocked, which agents can not go through

**Comment by Miffyli** [comment]
I do not know of other way than reading the map layout and processing the line vertex locations etc, which could quickly get tedious.

**Comment by mwydmuch** [comment]
Hi @acrushdjn, you can use this nice library to access information about the map layout: https://github.com/devinacker/omgifol. 

I can also make basic information about sectors and their vertices and lines available for you via our API.

**Comment by acrushdjn** [comment]
@mwydmuch @Miffyli Thanks, currenly, I can read information about linedef which are blocked, this is useful, is there any other information about obstacles? like sectors or sidedef, I just don't know the meaning of sectors or sidedef

**Comment by Miffyli** [comment]
Sectors contain information about specific areas, mainly what their ceiling and floor look like and act (e.g. lava). Sidedef only specifies texture of a linedef (two sides). 

Sectors may include information about collisions in form of floor height, although I am not sure (too high floor -> can't enter). Sidedefs do not provide any meaningful info on collisions. Main source for info are linedefs.

**Comment by mwydmuch** [comment]
I've added the option to include basic information about sectors and theirs linedefs into GameState. This example shows how to access this information: https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/objects_and_sectors.py. I think I will prepare a better example that draws a map based on this information later.
