### ISSUE TITLE
Modification of SPEED of bots failed

### ISSUE THREAD

**Issue by acrushdjn** [mwydmuch/ViZDoom#366]
Hi,

I tried to modify the speed the bots using code below:
`if (ClassifyActor(ActivatorTID()) & ACTOR_BOT ) {
	SetActorProperty(ActivatorTID(), APROP_Speed , 0.4);
}`
This is the code from previous issues, but is did not work, the speed of bots remains the same, I have added the code in OPEN/ENTER/RESPAWN code block, can anyone help me?
Below is my .wad file, maybe it's the problem of my .wad file?

[deathmatch_shotgun.zip](https://github.com/mwydmuch/ViZDoom/files/2777466/deathmatch_shotgun.zip)

**Comment by Miffyli** [comment]
Are you talking about deathmatch-bots (`DoomGame.send_game_command("addbot")`) or the NPC-bots the code is spawning? If memory serves me well, I was not able to change deathmatch-bot's speed but you can change the speed of regular monsters.  Arnold used both NPCs (`ScriptedMarine`) and bots to train itself, but I do not know if they really used bots at some point.

**Comment by acrushdjn** [comment]
Problem solved after compiling, thanks
