### ISSUE TITLE
Spawn position of agent

### ISSUE THREAD

**Issue by acrushdjn** [mwydmuch/ViZDoom#367]
Can we write ACS scripts to control initial spawn location of agents and bots?

**Comment by acrushdjn** [comment]
I want to make agents and bots spawn in about the same place, any methods to do this?

**Comment by Miffyli** [comment]
In deathmatch mode the underlying ZDoom randomly picks one of the deathmatch start points to spawn players on, and I have not found a way to control this.

In non-deathmatch mode, players spawn on "player start points", and you can spawn rest of the monsters on specific points in map with `SpawnPoint`

**Comment by acrushdjn** [comment]
OK, Thanks.
