### ISSUE TITLE
camera views of multiple locations in map

### ISSUE THREAD

**Issue by haitomatic** [mwydmuch/ViZDoom#369]
Hi, is there any way to sample camera views from multiple locations in the map before playing? Maybe if there is no such feature off the shelf, what I am thinking is walking the player though the map and recording all the views before actual play. Since the maps and textures are generated on the go during training, I cant do this with any doom editor before hand. (background: I am doing sort of visual place recognition by comparing current observation with memory images from the map). 
Thanks!

**Comment by Miffyli** [comment]
After looking into this a while I could not find a working solution. You could e.g. teleport player around the map and set their rotations randomly, but there does not seem to be an obvious way to get valid, random spot on the map where player can teleport to. A [study with similar setup](https://arxiv.org/pdf/1803.00653.pdf) used random agents and human walkthroughs to get images around the map.

**Comment by haitomatic** [comment]
Thanks for the rep. I figured out that it's possible to put security cameras at multiple locations in the maze to take the snapshot of the view at that location. 
I can use send_game_command() to call the acs script to go through each camera. The current view of the player is also change to the view of the camera. Then in python, I can save each view. I also need to get the location of the current camera for which I use the game_variable USER1-3. 
ACS script 2:
`script 2 (void)
{
	if(!cam_id % 5)
		cam_id++;
	xpos = GetActorX(cam_id);
	ypos = GetActorY(cam_id);
	ChangeCamera(cam_id, False, True);
	//Log(s:"Next cam location at ", f:xpos, s:" , ", f:ypos);
	cam_id++;
	//log(s:"cam id is ", d:cam_id);
	//log(s:"cam limit is ", d:cam_limit);
	if(cam_id >= map_thing_start_id + 5 * num_map_starting_points)
	{
		cam_limit = 1;
		//log(s:"reach limit");
	}
	cam_limit = 1;
	//delay(35);
}`
ACS script 3:
`script 3(void)
{
	delay(35);
	log(s:"cam id is ", d:cam_id);
	log(s:"cam limit is ", d:cam_limit);
	log(s:"x is ", f:xpos);
	log(s:"y is ", f:ypos);
	
}`

Python code:
` 
game.send_game_command("puke 2")
time.sleep(1)
gameex.send_game_command("puke 3")
my_list.append(gameex.get_game_variable(vz.GameVariable.USER3))
` 
My global variable in the acs file are:
`global int 1:xpos;
global int 2:ypos;
global int 3:cam_limit;`
Now I run into one problem. The acs script 2 changes the value of these variables . The change is confirmed by acs script 3 but gameex.get_game_variable(vz.GameVariable.USER3) returns 0.0 which is the default value.
Any idea? Thanks

**Comment by Miffyli** [comment]
Quickly testing with dummy scenario, `puke`s and reading `USER#` variables I was not able to reproduce this. Do your other global variables work correctly? (Tested on ViZDoom 1.1.4 and 1.1.6, Python 3.5, Ubuntu 16.04)

Offtopic-ish: If that `gameex` is of type `VizdoomWrapper`, the issue might lie there (although it should be just thin wrapper on top

**Comment by haitomatic** [comment]
Yes, I am using your VizdoomWrapper after adding:
def get_game_variable(self, game_variable):
      return self.doomgame.get_game_variable(game_variable)

and I think there is no problem with that. 
I have no problem seeing the change in global variables when they are modified in script 4 ENTER or script 1 OPEN.
Let's narrow down a little bit:
There is also another problem with the execution of the acs script called by send_game_command:
if I do this:

        for i in range(4):
            gameex.send_game_command("puke 2")
            gameex.send_game_command("puke 3")

I only get:

cam id is 1002
cam limit is 1
x is 111
y is 111
From this result, it seems to me that script 2 and script 3 each only got executed once.
It seems that send_game_command doesn't wait for the script to finish. And the commands seem to overwrite the one before it. 
Is there any way to make sure that the script run by send_game_command exit before the next line in python is run?

**Comment by haitomatic** [comment]
Another test:
I run the following after gameex.new_episode()
        print('dummy int is ', gameex.get_game_variable(vz.GameVariable.USER4))
        gameex.send_game_command("puke 3")
        print('dummy int is ', gameex.get_game_variable(vz.GameVariable.USER4))

and got:
dummy int is  1.0
dummy int is  1.0
script 3 is run

The acs script file is loaded as library by LOADACS
in that file:
global int 4:dummy_int;
script 3(void)
{
	dummy_int = 2;
	log(s:"script 3 is run");
}

script 4 ENTER
{
	dummy_int = 1;
}

**Comment by Miffyli** [comment]
Ah yes, I completely forgot: You may have to do a environment step (i.e. `make_actions` or `advance_action`) before pukes have an effect (the game is frozen meanwhile). I tested creating global variable and a function that modifies it, and `puke`s have no effect unless I have `make_actions` in between.

**Comment by haitomatic** [comment]
Perfect, it works, thanks a lot !
