### ISSUE TITLE
name 'DoomGame' is not defined (Anaconda)

### ISSUE THREAD

**Issue by AbubakarSaad** [mwydmuch/ViZDoom#370]
### Issues

If you encountered an issue, please post the following things:
Issue: I'm trying to get vizdoom working on Anaconda and Windows. The error I get is below: 

Traceback (most recent call last):
  File "vizdoom.py", line 3, in <module>
    from vizdoom import *
  File "C:\Users\src\Documents\Deep_Learning\Vizdoom\vizdoom.py", line 8, in <module>
    game = DoomGame()
NameError: name 'DoomGame' is not defined

Anaconda 3, python=3.7.0 vizdoom=1.1.7

Any help is appreciated. Thanks :)

**Comment by mihahauke** [comment]
That happens when you name your file the same as the library you are importing from. Change the name of the file.

**Comment by AbubakarSaad** [comment]
Ahh, okay. Thank you, didn't know that
