### ISSUE TITLE
Sector Line Usage

### ISSUE THREAD

**Issue by bradyz** [mwydmuch/ViZDoom#372]
I'm wondering about how to use the sector line information correctly.
Here is a minimal example (that doesn't work) that tries to plot the map, which is just a square.

### Code
```python
import vizdoom as vzd
import matplotlib.pyplot as plt

DEFAULT_CONFIG = "/home/bzhou/code/ViZDoom/scenarios/basic.cfg"

game = vzd.DoomGame()
game.load_config(DEFAULT_CONFIG)
game.set_sectors_info_enabled(True)
game.init()

for s in game.get_state().sectors:
    for l in s.lines:
        plt.plot([l.x1, l.x2], [l.y1, l.y2], 'r-')

        print((l.x1, l.y1), (l.x2, l.y2))

game.close()

plt.show()
```

### Output
```
(-448.0, 256.0) (64.0, 256.0)
(64.0, -192.0) (64.0, -192.0)
(64.0, -192.0) (-448.0, -192.0)
(-448.0, 256.0) (-448.0, 256.0)
```

![image](https://user-images.githubusercontent.com/7716849/54081187-4c696480-42b5-11e9-94aa-2f6b9dcb675d.png)

Lines 2 and 4 of the output show that the lines are actually single points.
Let me know if I'm using this incorrectly! Thanks.

**Comment by mwydmuch** [comment]
Hello @bradyz, thank you for reporting the problem, I've fixed the bug, so please pull the latest version. I also added your matplot-based map drawing to our examples, thank you!

**Comment by bradyz** [comment]
That was extremely fast! I'll update and try it out.
