### ISSUE TITLE
No deathmatch starts

### ISSUE THREAD

**Issue by JackieTseng** [mwydmuch/ViZDoom#377]
When I used most of the scenarios provided under `scenarios` folder for multi-player setting, it reported errors as follows,
```
No deathmatch starts
```
Is it caused by the `.wad` files which are not designed for deathmatch?

**Comment by mihahauke** [comment]
Yes indeed. The starting point object is different for two modes.

**Comment by JackieTseng** [comment]
Is there ways to recognize which `.wad` files are designed for deathmatch mode, rather than roading them and checking errors?

**Comment by mihahauke** [comment]
Not that I know of.
