### ISSUE TITLE
Shared Memory Exception Error

### ISSUE THREAD

**Issue by branavg** [mwydmuch/ViZDoom#378]
I have encountered the following issue, and am looking for some help. 
I am getting this error
SharedMemoryException                     Traceback (most recent call last)
<ipython-input-3-e00ebe60a50c> in <module>
----> 1 game, possible_actions = create_environment()

<ipython-input-2-15c520730524> in create_environment()
      8     game.set_doom_scenario_path("basic.wad")
      9 
---> 10     game.init()
     11     left = [1, 0, 0]
     12     right = [0, 1, 0]

SharedMemoryException: Memory size does not match the the expected size. Possible ViZDoom version mismatch.

The Vizdoom version I am using is 1.1.7. The OS is Windows 10. I am using Python in Jupyter Notebook.

Here is the code:

import tensorflow as tf      
import numpy as np           
from vizdoom import *       

import random               
import time                  
from skimage import transform
from collections import deque
import matplotlib.pyplot as plt 

import warnings
warnings.filterwarnings('ignore')

def create_environment():
    game = DoomGame()
    
    game.load_config("basic.cfg")
    
    game.set_doom_scenario_path("basic.wad")
    
    game.init()
    left = [1, 0, 0]
    right = [0, 1, 0]
    shoot = [0, 0, 1]
    possible_actions = [left, right, shoot]
    
    return game, possible_actions
       
def test_environment():
    game = DoomGame()
    game.load_config("basic.cfg")
    game.set_doom_scenario_path("basic.wad")
    
    game.init()
    shoot = [0, 0, 1]
    left = [1, 0, 0]
    right = [0, 1, 0]
    actions = [shoot, left, right]

    episodes = 10
    for i in range(episodes):
        game.new_episode()
        while not game.is_episode_finished():
            state = game.get_state()
            img = state.screen_buffer
            misc = state.game_variables
            action = random.choice(actions)
            print(action)
            reward = game.make_action(action)
            print ("\treward:", reward)
            time.sleep(0.02)
        print ("Result:", game.get_total_reward())
        time.sleep(2)
    game.close()

game, possible_actions = create_environment()

Thanks!

**Comment by Miffyli** [comment]
Do you happen to have multiple version of ZDoom binaries and ViZDoom libraries on your computer (e.g. did you update your ViZDoom at some point?). ViZDoom 1.1.7 works fine on my computer (Win10, Python 3.6)

**Comment by branavg** [comment]
I downloaded Vizdoom 1.15 first, then installed Vizdoom 1.1.7. So yeah I have multiple versions of Vizdoom libraries on my computer.

**Comment by branavg** [comment]
Yeah but I am using Vizdoom 1.1.7 with Python 3.6 in Jupyter Notebook through Anaconda.

**Comment by Miffyli** [comment]
Make sure you did not accidentally mix ZDoom binaries and ViZDoom python binaries (e.g. do you extra `vizdoom` directory or the `vizdoom.pyd` file next to script you are running).

There has been some issues with using ViZdoom with Conda in the past, so that could be also causing the issue.
