### ISSUE TITLE
Colab Installation Failure

### ISSUE THREAD

**Issue by AmrMKayid** [mwydmuch/ViZDoom#379]
I am trying to install and use VizDoom in Colab but I tried many times to install it via pip and building and it didn't work out too! 

These are the errors I have encountered
<img width="1672" alt="Screen Shot 2019-04-25 at 5 28 34 PM" src="https://user-images.githubusercontent.com/18689888/56748524-4e618700-6780-11e9-832f-7c5d28fc89a3.png">

**Comment by Miffyli** [comment]
Error says it couldn't find SDL2 even though you did seem to install it above that line. I'd hazard a guess this is because of Colab, and it is hard to debug without further information.
