### ISSUE TITLE
addbot command don't work on MacOS

### ISSUE THREAD

**Issue by JackieTseng** [mwydmuch/ViZDoom#381]
ViZDoom cannot add bots on Mac. The code can still run though without any bots and players, which shown as all `False` in `server_state.players_in_game`. However, the same script runs well with built-in bots on Linux server. Does anyone meet this issue? How to fix it?

**Comment by Miffyli** [comment]
Make sure you have `bots.cfg` file in same directory as the script you try to run (this file is required to define the available bots). You can also try placing it next to vizdoom binary file. 

If memory serves me well, I think I had same issues back in early versions of ViZDoom where I only managed to fix it by dropping `bots.cfg` next to vizdoom binary (on Windows).

**Comment by JackieTseng** [comment]
THX. It works now.
P.S. It's confusing that my Linux machine works fine without `bots.cfg` while the Mac cannot.
