### ISSUE TITLE
cann't get the reward I set in the script

### ISSUE THREAD

**Issue by GHMLL** [mwydmuch/ViZDoom#382]
Here is my code for cig.wad, I just copt the script 4 from basic.wad using slade, and add this ACS_Execute(4, 1, 0, 0, 0), but there is no change with the total reward, I don't know why 
#include "zcommon.acs"

global int 0:reward;

script 1 OPEN
{
	reward = 0;
}

script 2 ENTER
{
	ClearInventory();
	GiveInventory("RocketLauncher",1);
	GiveInventory("RocketAmmo",10);
	ACS_Execute(4, 1, 0, 0, 0);
}

script 3 RESPAWN
{
	reward=1000;
	ClearInventory();
	GiveInventory("RocketLauncher",1);
	GiveInventory("RocketAmmo",10);
	ACS_Execute(4, 1, 0, 0, 0);
}

script 4 (void)
{
    int bullets = CheckInventory("Clip");
    while(true)
    {        
		reward=100;
        int t_bullets = CheckInventory("Clip");
        if(t_bullets < bullets)
        {
            reward = reward - 5.0;
        }
        bullets = t_bullets;
    
        delay(1);
    }
}

**Comment by Miffyli** [comment]
Looks like you are trying to penalize shooting (give less reward when shooting). I recommend doing this in Python/script side with `DoomGame.get_game_variable(vizdoom.GameVariable.AMMO)` (track the changes to this value). Debugging the code in Python side is much easier.

But on the ACS code itself: I do not see bigger problems with the code. Did you compile the ACS script? The [documentation for `ACS_Execute`](https://zdoom.org/wiki/ACS_Execute) says the second argument is map number where code is, zero being the current map. Try your code with `ACS_Execute(4,0,0,0,0)`.
