### ISSUE TITLE
Open door only if agent is holding an item

### ISSUE THREAD

**Issue by joshim5** [mwydmuch/ViZDoom#384]
I can detect if an agent has picked up a custom item (see #229), but I would like to place doors that only open if the agent has picked up the item. You can think of the items as keys -- the agent needs to hold a key in order to open the door.

How can this be done?

**Comment by Miffyli** [comment]
You can use Doom's own locked doors and corresponding keys, but you have to modify the scenario file to achieve this. The single-player levels in `freedoom2.wad` contain these kind of doors, and you can find more info on the ZDoom wiki ([doors](https://zdoom.org/wiki/Generic_Door) and [keys](https://zdoom.org/wiki/Key_types)).

**Comment by joshim5** [comment]
Is there a way to procedurally generate placement of the doors? I can do this for keys by writing an ACS script. Is there a way to place doors in this way?

**Comment by Miffyli** [comment]
Modifying the map layout (lines, sectors, etc) seems to require outside-ACS modifications to the scenario file, namely modifying the WAD file before loading it up in Doom.

For possible guidance, see [PyOblige](https://github.com/mwydmuch/PyOblige) (generating single-player levels) and [NavDoom](https://github.com/agiantwhale/navdoom) for simple maze generation. The latter modifies WADs from Python.
