### ISSUE TITLE
List of all objects in Vizdoom

### ISSUE THREAD

**Issue by joshim5** [mwydmuch/ViZDoom#386]
Where can I find a list of all objects present in Vizdoom? For example, I know of ShortBlueTorch, BlueCard, YellowSkull, and a few others.

In other words, I am looking for all strings that I can use in the "Spawn" function in ACS code.

**Comment by Miffyli** [comment]
[Here you can find all items in the original Doom game](https://zdoom.org/wiki/Category:Doom_actors). Note that you can create/add new items in the scenario file.

**Comment by joshim5** [comment]
It seems that I can't spawn all of these. For example, this works perfectly
`while(Spawn("BlueTorch", random(1.0,wall_size-1.0), random(1.0,wall_size-1.0), 0.0)==0);`
but this does not:
`while(Spawn("Mummy", random(1.0,wall_size-1.0), random(1.0,wall_size-1.0), 0.0)==0);`

Is it possible that I need to include something besides `#include "zcommon.acs"`?

**Comment by Miffyli** [comment]
Let me clarify a little: Only the items under title `Pages in category "Doom actors"` are available in ZDoom (Ultimate Doom) by default. If you check [Mummy's page](https://zdoom.org/wiki/Classes:Mummy), it tells you it is for Heretic (same engine, different game).

**Comment by joshim5** [comment]
Is there a way to generate a graphic for each item so I can see how they look?

**Comment by Miffyli** [comment]
You can see the sprites with SLADE, but generally anything that can extract all the sprites should do the trick.

**Comment by joshim5** [comment]
Is it possible to make any of the objects movable? I want the agent to be able to push items around.

**Comment by sjtuytc** [comment]
yeah you can control via python API
