### ISSUE TITLE
Cannot spawn object with TID

### ISSUE THREAD

**Issue by joshim5** [mwydmuch/ViZDoom#387]
When I call `game.send_game_command("pukename spawn_object_by_id_and_location 0 50 400")` the object appears as I would expect. However, when I try spawn an object with a tid using `game.send_game_command("pukename spawn_object_by_id_and_location_and_tid 0 50 400 0")`, nothing appears.

Below is a snippet of the ACS I am using:

```
script "spawn_object_by_id_and_location" (int id, int x, int y)
{
	int object_id = id;
	while(Spawn(objects[object_id], x, y, 0.0, 0)==0);
}

script "spawn_object_by_id_and_location_and_tid" (int id, int x, int y, int tid)
{
	int object_id = id;
	int tid_id = tid;
	while(Spawn(objects[object_id], x, y, 0.0, tid_id)==0);
}
```

**Comment by Miffyli** [comment]
I was able to spawn things with both scripts and both puke commands when testing with deathmatch scenario spawning teleport fogs around.

The main issue was with x/y coordinates: `Spawn` expects fixed-point numbers, but numbers you give in are integers. Try shifting your x/y coordinates by 16 bits to left before feeding them to `Spawn`, i.e: 
```Spawn(objects[object_id], x << 16, y << 16, 0.0, tid_id```
