### ISSUE TITLE
How toHow to measure the performance of different algorithms by running 2 or more agents with different algorithm?

### ISSUE THREAD

**Issue by infinitycr** [mwydmuch/ViZDoom#389]
Can I use different agents to play against the same map? For example, use the DQN algorithm to train an agent, use the A2C algorithm to train another agent, and then let the agents play against each other in a map, to measure who is stronger?

**Comment by Miffyli** [comment]
You can do this via multiplayer play in ViZDoom. See examples on [how the host/first player starts their ViZDoom](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/cig_multiplayer_host.py), and then [how other players join that game](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/cig_multiplayer.py). 

Do note that the game runs notably slower in multiplayer mode, and IIRC it slows down quite a bit if you add more players. 

You can also use bots as one evaluation opponent. You may have to adjust their difficulty by modifying the `bots.cfg` to avoid having too good bots that always kill your agent.

**Comment by infinitycr** [comment]
Thank you for your prompt reply. I will try your suggestion!
