### ISSUE TITLE
Human vs AI match

### ISSUE THREAD

**Issue by alex-petrenko** [mwydmuch/ViZDoom#392]
I want to make it very easy to play a game against AI opponents. Currently, I can host a multiplayer game with VizDoom and then use a separate Python script in Spectator mode to play against agents. But this implies that anyone who wants to try playing against AI should install VizDoom with all its dependencies.

AFAIK VizDoom is based on ZDoom v2.8.1, so I downloaded this version and tried to connect to my VizDoom server with AI bots:

`zdoom -file /home/apetrenk/all/projects/doom/vizdoomgym/vizdoomgym/envs/scenarios/cig.wad +map map01 -join 127.0.0.1`

It connects at first, but then the client (ZDoom) game immediately crashes:

```
Total players: 2                        

Found Host (node 1, player 1)           
Found Player (node 0, player 2)         


Arbitrator selected peer to peer networking mode.
player 2 of 2 (2 nodes)
Use changemap instead. Map is for single-player only.
Using video driver x11
Resolution: 1280 x 720


map01 - Hydroelectric Plant

Starting MIDI playback failed


*** Fatal Error ***
Address not mapped to object (signal 11)
Address: 0xc

Generating zdoom-crash.log and killing process 32696, please wait... 30 ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
sh: 1: gxmessage: not found
Killed
```

I used the exact same freedoom2.wad for both versions, but I suspect they are still not on the same map. How do I make sure ZDoom also loads cig.wad and joins the same match?
Full crash log attached.

In general, is this a valid idea to use Zdoom 2.8.1 for human play?
My goal is to host a server on the internet where ppl can join and play against my agents with the easiest setup possible and from any OS.

[zdoom-crash.log](https://github.com/mwydmuch/ViZDoom/files/3316447/zdoom-crash.log)

**Comment by Miffyli** [comment]
I do not know about using ZDoom, but I used [PyInstaller](https://pythonhosted.org/PyInstaller/index.html) to create a similar "click-and-play" package for anyone to play ViZDoom for my data-collection. This binary did work on at least 20 different machines without errors. I did the binary only for Windows, but it should be very similar setup for Linux/Mac too.

Here is my `.spec` file for creating the binary. Note that you have to manually add some of the ViZDoom binaries to make it work correctly:

```
# -*- mode: python -*-

block_cipher = None

def add_binaries():
    binaries = [
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\fmodex64.dll", "vizdoom"),
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\libmpg123-0.dll", "vizdoom"),
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\libsndfile-1.dll", "vizdoom"),
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\vizdoom.exe", "vizdoom"),
    ]
    return binaries

def add_resources():
    resources = [
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\freedoom2.wad", "vizdoom"),
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\vizdoom.pk3", "vizdoom"),
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\__init__.py", "vizdoom"),
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\scenarios", "vizdoom/scenarios"),
        (r"C:\Users\Anssi\AppData\Local\Programs\Python\Python37\Lib\site-packages\vizdoom\bots.cfg", "."),
        (r"scenarios", "scenarios"),
    ]
    return resources

a = Analysis(['play_vizdoom.py'],
             pathex=['C:\\Users\\Anssi\\Desktop\\play_vizdoom'],
             binaries=add_binaries(),
             datas=add_resources(),
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='play_vizdoom',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True
)
```

**Comment by alex-petrenko** [comment]
Thank you, this is very helpful! I guess this is one of the ways to do it!

I still think this might be possible with just ZDoom, maybe I am just missing some configuration options. It looks like ZDoom might not recognize cig.wad as a valid scenario, otherwise, why would it say
`Map is for single-player only`?

But the installer is a good option too if the ZDoom solution does not work out.

**Comment by Miffyli** [comment]
In ViZDoom you have to add flag `-deathmatch` to launch parameters when you are using multiplayer maps, otherwise it will throw an error. However that error message is bit different (something about "no player starts"), but it could help with this ZDoom error.

**Comment by alex-petrenko** [comment]
I think you need -deathmatch on the server, not on the client. I tried and it didn't help :)
Thank you though, I think I might be able to use the vizdoom installer approach.

Both Vizdoom and Zdoom are able to start the scenario separately (e.g. -host 1), and it's the same map that plays and looks exactly the same. But whenever I try to connect one to the other, the client always crashes. Might be some binary incompatibility on the level of protocol.
