### ISSUE TITLE
fatal error: arith.h: No such file or directory

### ISSUE THREAD

**Issue by marisancans** [mwydmuch/ViZDoom#394]
Hello, I would like to build vizdoom from source and use c++ bindings.
I have installed all dependencies listed in guide. Im using ubuntu 18.04.

I get this error when using make command:
`[ 62%] Building CXX object src/vizdoom/src/CMakeFiles/vizdoom.dir/zstrformat.cpp.o
In file included from /home/maris/src/ViZDoom/src/vizdoom/src/zstrformat.cpp:93:
/home/maris/src/ViZDoom/src/vizdoom/src/../gdtoa/gdtoa.h:67:10: fatal error: arith.h: No such file or directory
 #include "arith.h"
          ^~~~~~~~~
compilation terminated.
`

From what I understand arith.h is generated by arithchk.c, so this might fail, but im not sure how to test it.
Im using gcc-8 and g++-8

**Comment by marisancans** [comment]
It looks like I found a workaround, if anyone stumbles upon this:
1.) $ cd ViZDoom/src/vizdoom/gdtoa
2.) $ gcc -o runme arithchk.c -Wall -Wextra
3.) $ ./runme
4.) I got output of things that has to go in header, in my case I got:
#define IEEE_8087
#define Arith_Kind_ASL 1
#define Long int
#define Intcast (int)(long)
#define Double_Align
#define X64_bit_pointers
5.) Copy the define lines you got and paste them in arith.h file
6.) profit

**Comment by Miffyli** [comment]
Building current master branch works out for me (Ubuntu 16.04, gcc 5.4.0), so perhaps it has something to do with the newer versions of gcc? 

```
./cmake_clean.sh
cmake -DCMAKE_BUILD_TYPE=Release
make
```

Edit: Ninj'd

**Comment by marisancans** [comment]
> Building current master branch works out for me (Ubuntu 16.04, gcc 5.4.0), so perhaps it has something to do with the newer versions of gcc?
> 
> ```
> ./cmake_clean.sh
> cmake -DCMAKE_BUILD_TYPE=Release
> make
> ```
> 
> Edit: Ninj'd

That might be the issue, gcc 6.0 also failed.
After trying commands you posted im confused as to where the installed files are. Even if i add -DCMAKE_INSTALL_PREFIX, I still cannot find them. How do I include them in project with CMakeList.txt? This is really messy and needs more documentation.

**Comment by Miffyli** [comment]
What do you mean by "installed files"? Do you mean the compilation results? These are stored under `bin` directory. After this you try out the (C++ examples)[https://github.com/mwydmuch/ViZDoom/tree/master/examples/c++] to learn how to use the separately compiled ViZDoom from your C++ code.
