### ISSUE TITLE
Latest Windows Build

### ISSUE THREAD

**Issue by kh217** [mwydmuch/ViZDoom#396]
Hi guys, is someone able and willing to provide the latest build of VizDoom for Windows? The 1.1.7 release was quite some time ago and I would like to use some features of the upcomming version 1.1.8 which are already implemented.

**Comment by TolgaDaSilva** [comment]
Latest release would be really helpful

**Comment by mwydmuch** [comment]
I will build pre-1.1.8 version for Windows by the end of this week.

**Comment by kh217** [comment]
Hi. Hopefully, I'm not annoying, just wanted to know how it's going with the build :)

**Comment by TolgaDaSilva** [comment]
I think they're on vacation enjoying the sun right now.

**Comment by Miffyli** [comment]
Indeed it has been a slow month with all vacations/holidays and blazingly hot days ^^. 

@mwydmuch Can you take a look at this? I may also try to compile Windows ViZDoom binaries eventually, even if it will take a day full of headache to get it right.

**Comment by Miffyli** [comment]
1.1.8pre builds for Windows are now available on [(find them on the main page](https://github.com/mwydmuch/ViZDoom#windows-build)). Thanks, Marek!
