### ISSUE TITLE
How to get distance to a object in view?

### ISSUE THREAD

**Issue by TolgaDaSilva** [mwydmuch/ViZDoom#397]
Hey, I'm trying to get the distance to an object in view.
I know I have access to the depth buffer, but I don't know exactly what to do with it. 
I only get values from 0 to 255. It's clear that the highest value is the greatest distance.

Is there any way to know if an object is in view?
If so, then I could calculate the distance using the coordinates.

**Comment by Miffyli** [comment]
[Check out how to use labels buffer](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/labels.py). `labels_buffer` only* includes visible objects, so you can check what is visible there and find the corresponding info from there. 

(*) Sometimes maps have weird lines/linedefs, which causes objects to be visible through walls. It is good idea to double-check manually that for your scenario the `labels_buffer` only includes truly visible objects.

**Comment by TolgaDaSilva** [comment]
Oh, my bad. I didn't even think about the label buffer. 
So I don't need the depth buffer to calculate the distance?
I thought it would be much easier because it contains depth information.

**Comment by Miffyli** [comment]
You could use combination of label and depth buffer to get the distance too, yes, but as you pointed out the value is something else than engine's distance units. I imagine it will be easier to go through objects in labels buffer, pick the ones of interest and calculate the standard Euclidian distance between their position and player's position (available in GameVariables).

**Comment by TolgaDaSilva** [comment]
Many thanks for the fast and competent help.
