### ISSUE TITLE
WIndows 10 (1903) Docker not working

### ISSUE THREAD

**Issue by WindowsXPSux** [mwydmuch/ViZDoom#407]
Hello, this is probably the dumbest question but here goes.

I'm following the install instructions for Vizdoom at https://www.michaelkrax.com/blog/how-to-run-vizdoom-on-windows-10/

I get almost to the end but I'm unable to run the command 

docker run -it –rm –network=”host” –name cig2017_host cig2017_host -li 1

I get docker.exe: invalid reference format.

not sure where to go or where to look, so I'm here.

Would it be better to just use a different OS??

any help is greatly appreciated

**Comment by Miffyli** [comment]
Last time I checked, Docker was tad wonky on Windows, altho this was years ago so it might have very well changed thus far. 

But in any case: Unless you have a specific reason to use Docker to run ViZDoom, I recommend installing on a regular Python installation or a conda environment by [following these instructions](https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md#windows_bin) . This way you do not have to hassle around booting and creating your docker images to try out scripts.

**Comment by WindowsXPSux** [comment]
If I don't need it cool lol only reason I installed Docker was because its in the list, here's what it says:

How to run the ViZDoom inside Docker for Windows

To be able to participate in a (potential) future ViZDoom competition you will most likely need to supply your AI bot build-able via a Dockerfile as you needed for ViZDoom 2017. You can find the sample submission, some past submissions of actual bots and the Linux guide here: https://github.com/mihahauke/vizdoom_cig2017

In a nutshell the way the competition works is that you run a “host” Docker Container which hosts an instance of ViZDoom as a spectator and you have another Docker container with another instance of ViZDoom for each participating AI. All instances of ViZDoom create a network game on port 5029 via UDP and the match autostarts when the pre-configured amount of players joined. Using the submission template you can create your own little competition among one or multiple instances of your own AI, a (fairly random) test AI and some of the AI’s submitted to previous competitions (although i only managed to get “clyde” to work in Docker for Windows).

**Comment by Miffyli** [comment]
Yes the competition used Docker images, but outside that (and outside sharing/deploying the system somewhere conveniently) it might not make much sense to use it. I recommend going the default way shown on the main github page.

**Comment by WindowsXPSux** [comment]
Okay I'll do that although I was really interested in getting them to play each other lol
