### ISSUE TITLE
vizdoom.vizdoom.MessageQueueException: Failed to create message queues: boost::interprocess::intermodule_singleton initialization failed

### ISSUE THREAD

**Issue by Shono1** [mwydmuch/ViZDoom#413]
###**Issue**###

When I try to initialize the game, it throws the error:

vizdoom.vizdoom.MessageQueueException: Failed to create message queues: boost::interprocess::intermodule_singleton initialization failed

I am using Python 3.6.3 on a windows 10 machine. 

I am using the precompiled binaries of Vizdoom 1.1.7.

The code I am running:

```
from vizdoom import *
# import tensorflow as tf
import numpy as np

import random
import time
from skimage import transform

from collections import deque
import matplotlib.pyplot as plt

import warnings

warnings.filterwarnings('ignore')


def create_environment():

    game = DoomGame()

    # Load the correct configuration
    game.load_config("basic.cfg")

    # Load the correct scenario (in our case basic scenario)
    game.set_doom_scenario_path("basic.wad")

    game.init()

    # Here our possible actions
    left = [1, 0, 0]
    right = [0, 1, 0]
    shoot = [0, 0, 1]
    possible_actions = [left, right, shoot]

    return game, possible_actions

create_environment()
```

This throws the error when line 26 (game.init()) is run.

**Comment by Miffyli** [comment]
I ran your code with Python 3.6.8, ViZDoom 1.1.8pre (one on the main page) and Windows 10, and everything seems to run correctly. Here is a list of packages and their versions I have installed:

```
numpy==1.17.2
scikit-image==0.16.1
matplotlib==3.0.3
```

**Comment by Fankbai** [comment]
just reboot your pc, that can work for you.

**Comment by mwydmuch** [comment]
Old, closing.
