### ISSUE TITLE
Question: Deadly Corridor reward for killing daemon

### ISSUE THREAD

**Issue by rohankindred** [mwydmuch/ViZDoom#422]
I'm trying to give my agent a reward for killing a daemon, but haven't been able to see the desired behavior (I think because I don't fully understand how ACS works). 

I referenced the [SetThingSpecial](https://zdoom.org/wiki/SetThingSpecial) wiki to infer that, in order to increase the reward when a thing is killed, I should call `SetThingSpecial` on the TID of the monster being created. My Script 5 should then increment the reward by 10 on a kill. 

However, I do not see this reflected in the reward coming from:

`reward = DoomGame.make_action(action)`

Instead, I still just see the dX of the agent even when a monster is killed. I would expect dX+10 when a monster is killed. 

If you could point out where I've gone wrong in defining the reward for a kill, I would greatly appreciate it! (PS. Yes, I'm saving and compiling the .wad correctly and have tested that modifying the reward for Basic works as expected).  

Here is the .wad file:

```
#include "zcommon.acs"

int monsters = 10;
int start_id = 6;
global int 0:reward;
global int 1:shaping_reward;
int armour_x = 1312.0;
int armour_reward = 0.0;
int armour_tid = 22;
/* Skill level 5 suggested*/
script 1 OPEN
{
    for(int i =start_id;i< start_id+monsters;i++)
    {
        SetActorProperty(i, APROP_Speed, 0);
        SetActorProperty(i, APROP_Health, 1);        
	SetThingSpecial(i, ACS_ExecuteAlways, 5);
    }
    SetThingSpecial(armour_tid, ACS_ExecuteAlways, 4);


    
}

script 2 ENTER
{
    reward = 0.0;
    shaping_reward = 0.0;
    SetActorProperty(0, APROP_DamageFactor, 2.0);
    ClearInventory();
    GiveInventory("Pistol", 1);
    SetWeapon("Pistol");
    GiveInventory("ClipBox", 6);
    while(1)
    {
        delay(1);
        reward = GetActorX(0)+armour_reward+shaping_reward; 
    }
    
}


script 4(void)
{
    armour_reward = 1000.0;
    Exit_Normal(0);
}

script 5 (int id)
{
    shaping_reward = shaping_reward + 10.0;

}

**Comment by Miffyli** [comment]
Hey, sorry for the delayed answer!

You are on the right track. I recommend taking a look at how [deatchmatch example](https://github.com/mwydmuch/ViZDoom/blob/master/scenarios/deathmatch.wad) implements this. Looks like your `script 5` is expecting an argument but you are not providing one in the `SetThingSpecial(i, ACS_ExecuteAlways, 5);` line. Replacing `script 5` with following should do the trick (haven't tested it though):

```
script 5 (void)
{
    shaping_reward = shaping_reward + 10.0;
}
```

**Comment by rohankindred** [comment]
Whoops, yeah you're right. I forgot to remove the argument before posting here... I had originally:

```
script 5 (int id)
{
    shaping_reward = shaping_reward + 10.0; 
    Thing_Remove(id)
}

Because I wanted to remove the daemon after shooting it (though this didn't do what I wanted either). What I have seems to work :) Thanks for your help!
