### ISSUE TITLE
Best practice in gathering frames for video conversion

### ISSUE THREAD

**Issue by EXJUSTICE** [mwydmuch/ViZDoom#425]
I'm writing up a Colaboratory notebook on Vizdoom, and have noticed that existing notebooks all skipped in-situ visualization due to the lack of gym-compatibility.

Isn't it possible to simply collect frames from gameplay of the agent into a list, and convert into an mp4 for display?

Secondly, how does one collect frames of normal gameplay?

**Comment by Miffyli** [comment]
There is no premade solution for this, but yes, you could store all the `screen_buffers` into a list and convert them into a video later for showing or feed directly to a OpenCV VideoWriter ([one example here](https://www.learnopencv.com/read-write-and-display-a-video-using-opencv-cpp-python/)). If you create a gym-compatible API (the one out there is quite out-dated), you can also use [Gym's Monitor wrapper](https://github.com/openai/gym/blob/master/gym/wrappers/monitor.py) that automatically creates videos of episodes during training.

If by "normal" gameplay you mean recording human gameplay, you can follow [this example](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/spectator.py).

**Comment by EXJUSTICE** [comment]
Hi Miffyli, thank you for the rapid and thorough reply. I may create a Gym API in the future, but as of now your solution is adequate.

I found a buffer example in the repo [here](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/buffers.py#L99) 

As I understand, the screen buffers are just individual frames then? Would you call a new screen buffer after every action, or after a arbitrary wait (as is done in the repo)

**Comment by Miffyli** [comment]
Yes, what is called `screen_buffer` in the example you linked contains information of single frames (RGB, depth and/or labels). The interface works mostly like in gym: You ask for a state, decide an action, execute the action and repeat (so yes, you call new screen buffer after every action).

**Comment by EXJUSTICE** [comment]
Thank you very much for your assistance!
