### ISSUE TITLE
Question: Why not expose PLAYER_XXX variables?

### ISSUE THREAD

**Issue by mhe500** [mwydmuch/ViZDoom#427]
Hello.

I notice that ViZDoom tracks some metrics from both the total (across all players) as well as current player (i.e., VIZ_PLAYER) perspective. For example ITEMCOUNT refers to MAP_ITEMCOUNT:

https://github.com/mwydmuch/ViZDoom/blob/1f822313ce932e02bbf9c36c9b18d0716c37e1b3/src/lib/ViZDoomController.cpp#L964

However there also is PLAYER_ITEMCOUNT:

https://github.com/mwydmuch/ViZDoom/blob/1f822313ce932e02bbf9c36c9b18d0716c37e1b3/src/vizdoom/src/viz_game.h#L156

which refers to items picked up by the console player.

Question: is there a reason that PLAYER_ITEMCOUNT and other player-specific variables are not exposed through the DoomGame API?

Thanks!

**Comment by Miffyli** [comment]
My first instinct says it is because ViZDoom was first designed to do single-player environments, and tracking values from whole map is easier (more robust?). Can you try if indeed PLAYER_ITEMCOUNT works as you'd expect it to work? Some of the variables have been quirky and their names have not always reflected their functionality.

@mihahauke @mwydmuch 
Any comments on this?

**Comment by mhe500** [comment]
Thanks @Miffyli. I'll try just substituting it for MAP_ITEMCOUNT and see what happens and report back. Inside the zDoom code it does appear to be incremented for the "self" VIZ_PLAYER, but we'll have to see if it actually is working.

Thanks.
mhe

**Comment by mhe500** [comment]
Hi @Miffyli.

FWIW, I tried changing the mapping in DoomController::getGameVariable to per-player members in state (see below) and it appears to work fine. I'm not suggesting a redefinition of KILLCOUNT or ITEMCOUNT, but point this out in case anyone else has a need to customize for their use case.

```c++
    double DoomController::getGameVariable(GameVariable var){

        switch (var) {
            case KILLCOUNT :
                // MHE Change from MAP_KILLCOUNT to PLAYER_KILLCOUNT
                return this->gameState->PLAYER_KILLCOUNT;
            case ITEMCOUNT :
                // MHE: Change from MAP_ITEMCOUNT to PLAYER_ITEMCOUNT
                return this->gameState->PLAYER_ITEMCOUNT;
```
Thanks.
mhe
