### ISSUE TITLE
How to make the player spawn at random locations?

### ISSUE THREAD

**Issue by HadiSDev** [mwydmuch/ViZDoom#428]
### Issues

* description of an issue,
_I am new to VizDoom so please excuse my noobness, but how do I make the player spawn at random locations instead of just the middle of the room if we take the basic scenario as an example. Thanks in advance._
* ViZDoom version you are using,
**1.7**
* information about your OS platform, distribution and environment (GCC, Python, Java, Lua versions etc.),
**Ubuntu 18.4 Python 3.6**

**Comment by Miffyli** [comment]
You need to modify scenario files (.wad) to achieve this. [I have detailed instructions written here](https://github.com/mwydmuch/ViZDoom/issues/319).

For random spawn locations you can take a look at `health_gathering_supreme.wad` (open it and see how random spawning is done there). The technique used there is to place Things (markers) on the map where player can spawn, and then in the ACS script you randomly pick one of those markers and move the player there (See `health_gathering_supreme.wad` SCRIPT entry at the bottom). If "+deathmatch" game argument is provided, player will be spawned to one of the PlayerSpawn markers randomly.
