### ISSUE TITLE
Disable the status bar

### ISSUE THREAD

**Issue by wangguanzhi** [mwydmuch/ViZDoom#431]
Hi,

Is it possible to disable (hide) the status bar at the bottom of the screen? 

That is, I want to generate 
![scenario_epoch001_frame000480_rgb](https://user-images.githubusercontent.com/25460983/74997333-b1f12b00-540a-11ea-8104-11d0048dcd15.jpg)

instead of
![scenario_epoch001_frame000480_rgb](https://user-images.githubusercontent.com/25460983/74997120-3b542d80-540a-11ea-8bbc-fa6b966579a4.jpg)

Thank you!

**Comment by mwydmuch** [comment]
Hi @wangguanzhi, DoomGame object has a method for this:
```
game.set_render_hud(False)
```
