### ISSUE TITLE
Accurate Semantic Segmentation

### ISSUE THREAD

**Issue by wangguanzhi** [mwydmuch/ViZDoom#432]
Hi,

I was trying to generate semantic segmentation for an image. For this example,

<img width="786" alt="Screen Shot 2020-02-21 at 10 47 03 AM" src="https://user-images.githubusercontent.com/25460983/75062456-ae57b580-5497-11ea-9dd0-d86ebda85acc.png">

I get the label for ChaingunGuy from the label buffer. However, I found the segmentation is not perfectly accurate (there are many white dots and unclear boundaries). So I was thinking whether it would be possible to generate a set of polygons to enclose the object? Any suggestions?

Thank you!

**Comment by Miffyli** [comment]
Hmm could you share the software version information, Python used, code used and other information needed to replicate this? Last time I played around labels buffer it was working as expected:

![image](https://user-images.githubusercontent.com/1633800/75063188-053baa00-54ed-11ea-851b-ce1c1a2c849f.png)

**Comment by wangguanzhi** [comment]
Hi, @Miffyli. Thank you for your reply!

Basically, I saved the label buffer as an image and load it back. I just realized I should save the label buffer in PNG format (lossless) instead of JPEG format (lossy). PNG works perfectly for me!

Thank you very much for your help!
