### ISSUE TITLE
Quckstart guide issue with running basic.py file

### ISSUE THREAD

**Issue by Pavel-Durov** [mwydmuch/ViZDoom#433]
I followed the [Quckstart guide](https://github.com/mwydmuch/ViZDoom/blob/master/doc/Quickstart.md) and I had an issue with running [basic.py](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/basic.py) file.
Error:
```
(vizdoom) 2038 kimchi-box λ  (~/git-repos/side-projects/doom/ViZDoom dac6904 master U:1⚡)
 $ python3 ./examples/python/basic.py
Traceback (most recent call last):
  File "./examples/python/basic.py", line 52, in <module>
    game.set_objects_info_enabled(True)
AttributeError: 'vizdoom.vizdoom.DoomGame' object has no attribute 'set_objects_info_enabled'
```

+ if I commentout lines: 52, 54,55,133,134 doom process is launching

+ running other files like [shapping.py](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/shaping.py) is fine, although the relative file path to `.cfg` files is a bit confusing I had to navigate into `examples/python` directory in order to run it.

launching python example from the project root directory produces this error:

```
 $ python3 ./examples/python/shaping.py 
Traceback (most recent call last):
  File "./examples/python/shaping.py", line 43, in <module>
    game.load_config(args.config)
vizdoom.vizdoom.FileDoesNotExistException: File "../../scenarios/health_gathering.cfg" does not exist.
```
Probably its better to add a note on  [Quckstart guide](https://github.com/mwydmuch/ViZDoom/blob/master/doc/Quickstart.md) that you should be in an appropriate directory when running examples :)

ViZDoom version:
```
 $ pip3 show vizdoom
Name: vizdoom
Version: 1.1.7
Summary: Reinforcement learning platform based on Doom
Home-page: http://vizdoom.cs.put.edu.pl/
Author: Marek Wydmuch, Michał Kempka, Wojciech Jaśkowski, Grzegorz Runc, Jakub Toczek
Author-email: vizdoom@googlegroups.com
License: UNKNOWN
Location: /usr/local/lib/python3.6/dist-packages
Requires: numpy
```

**Comment by Miffyli** [comment]
Thanks for reporting this! I updated the Quickstart guide with this information.

Regarding the first error: That happens because these examples are made for the ViZDoom version here in `master`, which has some additional features like segmentation, which do not exist in 1.1.7. You would have to build the vizdoom from the source to have these functions.
