### ISSUE TITLE
http://vizdoom.cs.put.edu.pl/ website is down 

### ISSUE THREAD

**Issue by hadjilucasL** [mwydmuch/ViZDoom#435]
![image](https://user-images.githubusercontent.com/295876/76107837-65dce380-5fd1-11ea-8b97-069371ce2c1f.png)

**Comment by mwydmuch** [comment]
Thank you @hadjilucasL for reporting. It's a problem with our university server, I hope it will be fixed soon.

**Comment by mwydmuch** [comment]
Fixed
