### ISSUE TITLE
Vizdoom headless possible?

### ISSUE THREAD

**Issue by HadiSDev** [mwydmuch/ViZDoom#436]
### Questions, features suggestions and requests
Hi,

Is it possible to run vizdoom headless, meaning we don't show any GUI? This would make it easier to run on servers.

**Comment by Miffyli** [comment]
This is the default mode of ViZDoom, just set `game.set_window_visible(False)`. This will not create any windows.

**Comment by mwydmuch** [comment]
Hi @HadiSDev, of course it has headles mode, just use: `game.set_window_visible(False)`.

**Comment by HadiSDev** [comment]
Thank you so much. :D 💯
