### ISSUE TITLE
python: ids for objects in `state.objects`.

### ISSUE THREAD

**Issue by e2crawfo** [mwydmuch/ViZDoom#442]
I'm trying to get a list of all objects in the environment at every time step (not just ones that are currently visible, so I gather that I have to use `state.objects` rather than `state.labels`). I noticed that the objects stored in `state.objects` don't have an `id` attribute, though the docs seem to indicate that they should (https://github.com/mwydmuch/ViZDoom/blob/master/doc/Types.md#-object). Going through the code I've noticed couple places that indicate that the object id used to be available, but isn't anymore, e.g.: 

https://github.com/mwydmuch/ViZDoom/blob/321aa8b269b56d1c2f1e4c2de5a8cc5bd57ae024/src/lib_python/ViZDoomPythonModule.cpp#L400

Could you explain why that was taken out, and whether it would be reasonably easy for me to make changes such that the object ids are accessible again?

**Comment by Miffyli** [comment]
Talking from pure memory here, so I might be wholly wrong:
IIRC, even if you take all of the objects in the map (not just the visible ones), those IDs changed from time to time, and you could not reliably use them to track specific objects. I remember having issues with this a while back.

@mwydmuch Any clarification for this?

**Comment by e2crawfo** [comment]
Ah OK, that makes sense. I found this comment which supports what you're saying:
https://github.com/mwydmuch/ViZDoom/blob/321aa8b269b56d1c2f1e4c2de5a8cc5bd57ae024/include/ViZDoomTypes.h#L70

I guess instead I'll track based on name, position and velocity, which ought to be good enough for the cases I'm interested in. Thanks.

**Comment by mwydmuch** [comment]
Hello @e2crawfo, to be honest, I don't remember why id is not exposed here. It's possible that I stopped developing this feature for a few days and simply forgot to finish it... give me one day I will add/finish it for you!

**Comment by mwydmuch** [comment]
@Miffyli I think, I had an issue implementing unique object id. I think that in Doom engine objects (actors) don't have their own unique ids. So currently unique ids are assigned based on their memory addresses, I suspect that it's not 100% reliable approach. Also, monsters and their dead bodies after it was killed are two different objects for the engine, so the body gets a new id.
It was a while since last time I was looking at this code. Maybe I will find a better solution this time.

**Comment by e2crawfo** [comment]
@mwydmuch Great, thanks for looking into this.

**Comment by mwydmuch** [comment]
Hi @e2crawfo, it's done, now you can install the newest version from the repo to use these ids:
```
pip uninstall vizdoom
pip install git+https://github.com/mwydmuch/ViZDoom
```

@Miffyli the ids should be consistent from now.
