### ISSUE TITLE
Trouble installing via pip.

### ISSUE THREAD

**Issue by e2crawfo** [mwydmuch/ViZDoom#443]
Thanks for your help with the object_id issue.

Now I'm trying to install from the github repo via pip on ubuntu 18.04, but I'm having some issues.

I'm trying to install into a virtual env (though I get the same results if I try to install globally). I installed dependencies by running `sudo sh scripts/linux_check_dependencies.sh`.
My pip version is 20.0.2. Here is a file showing the output of running `pip install -vvv .` inside the ViZDoom repo: [install_output.txt](https://github.com/mwydmuch/ViZDoom/files/4525291/install_output.txt)

It exits without error, but if I later do `python -c "import vizdoom` then I get a standard ImportError.
One line from the installation output that struck me as potentially relevant was:
`warning: install_lib: 'build/lib.linux-x86_64-3.6' does not exist -- no Python modules to install`
It seems like maybe it is building the library inside the directories created by pip in `/tmp`, but then other parts of the code are expecting those files to be in a local directory named `build` instead?

After installation, if I do
```
cdvirtualenv
cd lib/python3.6/site-packages/
```
then the only files there related to vizdoom are the following:
$ tree vizdoom*                
vizdoom-1.1.8.dist-info
├── INSTALLER
├── METADATA
├── RECORD
├── top_level.txt
└── WHEEL

Finally, I *did* have success using the method listed here (manually compiling in a local build directory and then copying over the pip package):
https://github.com/mwydmuch/ViZDoom/blob/master/doc/Building.md#-linux-1

**Comment by Miffyli** [comment]
I can confirm this happens with virtual env (miniconda, pip version 19.1.1, python 3.7). However if I install with system python (pip 9.0.1, python 3.6, Ubuntu 18.04), everything works fine.

**Comment by mwydmuch** [comment]
Hi @e2crawfo, sorry for the inconvenience, recent changes to setup.py messed up the installation for a different version. I reverted most of these changes to make it work again. It should work know for base as well as venv python. For venv for on Ubuntu 16.04 it may be necessary to `pip install cython` first.

@Miffyli, thanks for checking different variants, please let me know if it works for you now, then we will close this issue.

**Comment by Miffyli** [comment]
@mwydmuch Thanks for the prompt fix! Installing and running `master` now works on 18.04, system-wide python 3.6.

**Comment by e2crawfo** [comment]
Yeah, the changes work for me! Thanks.

**Comment by mwydmuch** [comment]
Great, @e2crawfo, @Miffyli thank you for confirming, closing!
