### ISSUE TITLE
Question on the vizdoom "landmarks"

### ISSUE THREAD

**Issue by pengzhi1998** [mwydmuch/ViZDoom#446]
Hi, I'm using [NavDoom](https://github.com/agiantwhale/NavDoom) to generate the vizdoom world, but there are several meaningless "landmarks" such as the stand columns shown in the image below. I'm wondering if there is a way to remove them? Can I use the `ZThing` class to change it?
Looking forward to your reply!
![ded399e9fc46e766bbeb230ba358572](https://user-images.githubusercontent.com/38170947/80286562-b74a5900-875e-11ea-8c96-505db2f0f585.jpg)

**Comment by Miffyli** [comment]
This is an issue for NavDoom, so you better ask there. I think those things are supposed to be there, generated by the NavDoom's code.

I recommend checking out [MazeExplorer](https://github.com/microsoft/MazeExplorer), which is bit more advanced version of NavDoom.

**Comment by mwydmuch** [comment]
Hi @pengzhi1998, if you want to remove green columns in NavDoom, remove this part from its script (lines 59 - 70): https://github.com/agiantwhale/NavDoom/blob/3fdbef83b644007d85522a97e7dadbb7260a9042/content/static_goal_train.acs#L59

**Comment by mwydmuch** [comment]
Oh, it's simpler to replace the content of `static_goal_train.acs` script with the content of `static_goal.acs`

**Comment by pengzhi1998** [comment]
Thank you so much for your help! @Miffyli @mwydmuch 
But @mwydmuch is there a way to set the game to do the missions like navigation and location but not just playing doom games? Which script code do I need to change?

**Comment by Miffyli** [comment]
1) You do not need to change WAD file (the ACS code) for this. You can use GameVariables (e.g. `GameVariable.POSITION_X`) to read agent's current location, and give the reward based on that.
2) I suggest you read more on the `scripts` on the [ACS wiki](https://zdoom.org/wiki/ACS), where you pointed to. I think you can do these scenarios in numerous ways, and it is up to the developer to decide how they want to do it. When you encounter functions that are not defined in that file, make sure to check all the included scripts (with `#include`), as well as make sure the Python code is not generating new scripts in the file during runtime.

**Comment by pengzhi1998** [comment]
Thank you so much!!!
