### ISSUE TITLE
Find monster's position relative to Player

### ISSUE THREAD

**Issue by SanchitTaliyan** [mwydmuch/ViZDoom#448]
[###](url) Questions, features suggestions and requests

If you have a question, features suggestions or requests, do not hesitate to ask.
However, you can check **[FAQ](doc/FAQ.md)** section and already existing issues with "question" tag ([is:issue label:question](https://github.com/mwydmuch/ViZDoom/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion)) first.

### Issues

If you encountered an issue, please post the following things:
* description of an issue,
* ViZDoom version you are using,
* information about your OS platform, distribution and environment (GCC, Python, Java, Lua versions etc.),
* if you have a problem with installation/building, post pip, CMake and Make output etc.,
* if you encountered a crash, post `vizdoom-crash.log` that should be created in your working directory,
* if you encountered a crash or bug, provide information about scenarios you are using and configuration of the ViZDoom environment,
* any additional information, configuration, code or data that might be helpful.

Thanks!

**Comment by SanchitTaliyan** [comment]
I am trying to find monster position relative to player in ACS script. Below is the code in which I have created a reward function, in which I am accessing player position and monster position. 
<img width="735" alt="Screenshot 2020-05-08 at 6 58 21 PM" src="https://user-images.githubusercontent.com/34193530/81410228-04b2c700-915e-11ea-9191-10a5c59bb4b9.png">

Here monster TID is 2 and Player TID is 0. The problem is GetActorX for Player is always returning zero as if Player's origin is on its head and for Monster I think it is returning position relative to Global Map Position.
I am using DoomBuilder 2 for map editing and script writing. I have also tried slade3 on both mac and windows but while compiling in slade3, I am getting the error:
<img width="496" alt="Screenshot 2020-05-08 at 6 43 16 PM" src="https://user-images.githubusercontent.com/34193530/81410578-991d2980-915e-11ea-851e-d4d775acb087.png">

I have downloaded acc compiler from official zdoom site. I have tried everything to find player position relative to Global Map position.

Thanks!

**Comment by Miffyli** [comment]
I think this would be easier with the label/automap buffers, [see an example using them here](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/buffers.py). That way you do not have to modify ACS files, and you can get all the info in Python.

Slade3 and ACC should work. Try using ACC from [this github repo](https://github.com/rheit/acc), in case the thing on ZDoom website differs.

**Comment by SanchitTaliyan** [comment]
Thanks for the reply. I calculated monster's position using labels and player position using game variable and finally calculated reward:
<img width="1135" alt="Screenshot 2020-05-11 at 11 41 44 AM" src="https://user-images.githubusercontent.com/34193530/81529422-71a3a800-937c-11ea-8a33-2dfda4241ea0.png">


But the problem is when monster is out of frame state.labels returns NULL as no object is found in the frame. Is there any way I can find monster's position during whole episode?
Also, Does ob.object_position_x returns position relative to player or relative to Global Map position?
Below is the screen shot of my frame:
<img width="642" alt="Screenshot 2020-05-11 at 11 40 19 AM" src="https://user-images.githubusercontent.com/34193530/81529316-3f924600-937c-11ea-9d4d-4d1106c109cf.png">

**Comment by mwydmuch** [comment]
Hi @SanchitTaliyan, instead of using labels buffer that list only visible objects, you can use a list of all objects like in this example: https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/objects_and_sectors.py.

And answering your second question: positions in labels buffer as well as in objects list are relative to map origin.

**Comment by SanchitTaliyan** [comment]
@mwydmuch Thank You! It worked well.
