### ISSUE TITLE
Question about the top down map

### ISSUE THREAD

**Issue by pengzhi1998** [mwydmuch/ViZDoom#449]
Hi, I have a question on the top-down maps.
When I set the automap buffer to be "true":
```
game.set_automap_buffer_enabled(True)
game.set_automap_mode(vzd.AutomapMode.OBJECTS_WITH_SIZE)
```
However, it can only show a part of the map but not the whole environment. And the walls in the environment cannot be displayed fully (some walls disappear on the map). A screenshot is shown below. Do you know how to fix this?
![FN0REY7X9PUWP9H@MD$AK}6](https://user-images.githubusercontent.com/38170947/82736718-61b59c00-9d5e-11ea-92d6-c6fcdea1ac25.png)

Thanks!

**Comment by Miffyli** [comment]
`automap` buffer (the image you included) only include the nearby objects, regardless of the setting. Try the [objects/sectors info](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/objects_and_sectors.py), which should include all the objects and sectors, regardless of where they are.

**Comment by pengzhi1998** [comment]
Thank you so much. It helps a lot!
