### ISSUE TITLE
Screenbuffer returns Nonetype?

### ISSUE THREAD

**Issue by EXJUSTICE** [mwydmuch/ViZDoom#453]
I'm trying to setup a basic Q-learning agent for vizdoom 1.1.7 using the Screenbuffer as a visual source.
My approach worked  before for OpenAI gym enviroments, but now I observe the error
\---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-45-36f0a6b68c82> in <module>()
     57             reward = game.make_action(action)
     58             #Append current intra-episodic reward to a counter
---> 59             next_obs = game.get_state().screen_buffer
     60             next_obs, stacked_frames = stack_frames(stacked_frames, next_obs, False)
     61             exp_buffer.append([obs, action, next_obs, reward, done])

AttributeError: 'NoneType' object has no attribute 'screen_buffer'

For reference I have provided the intra-episodic loop below. As we are still within the game episode, I don't understand how this error could be possible? Any advice is appreciated.
 ```
while not game.is_episode_finished():
            obs = game.get_state().screen_buffer
            obs,stacked_frames= stack_frames(stacked_frames,obs,False)
            step+=1
      
            # feed the game screen and get the Q values for each action,  FEED THE NETWORK BY CALLING THE OUTPUT LAYER
            
            actions = mainQ_outputs.eval(feed_dict={X:[obs], in_training_mode:False})

            # get the action
            action = np.argmax(actions, axis=-1)
            #increment the number of actions
            actions_counter[str(action)] += 1 

            #Recall possible actions  = [left, right, shoot], need to feed it to epsilon_greedy
            # Recall epsilon_greedy takes the predicted action, and compares
            # Against a set probability
            action = epsilon_greedy(action, global_step,possible_actions)
            
            
            # now perform the action and move to the next state, next_obs, receive reward
            reward = game.make_action(action)
            #Append current intra-episodic reward to a counter
            next_obs = game.get_state().screen_buffer
            next_obs, stacked_frames = stack_frames(stacked_frames, next_obs, False)
            exp_buffer.append([obs, action, next_obs, reward, done])
            obs = next_obs
            episodic_reward +=reward
            
            global_step += 1
```

**Comment by mwydmuch** [comment]
Hi @EXJUSTICE, if an episode is in finished state, `get_state ()` returns None. In your loop you call `make_action` which may end the current episode and then again call` get_state ()`.

**Comment by EXJUSTICE** [comment]
Hi Marek

Thank you, that makes sense.

Then how would you recommend i fetch the so-called "next_state"?

Most OpenAI gyms allow you to return it during the env.step() but we do not have that luxury here.

Should I put another check of some kind after make_action()?

________________________________

**Comment by Miffyli** [comment]
Also, depending on how episode was terminated, the `screen_buffer` can be None. I personally check for `game.is_episode_finished()`, and if this is True, I return the last observation. Not the best/cleanest solution.

**Comment by EXJUSTICE** [comment]
Hi Anssi,

Thanks

Would it be possible to get a reference script of that section as a gist from you?
Just to make sure I don't break something else

Btw, suomesta?

________________________________

**Comment by Miffyli** [comment]
You can take a look at [ViZDoomGym's version](https://github.com/shakenes/vizdoomgym/blob/master/vizdoomgym/envs/vizdoomenv.py), where they return zeros. My version is more or less the same, with `step` and `reset` functions as below:

```python
    def step(self, action):
        action = self.action_handler(action)
        reward = self.doomgame.make_action(action, self.frame_skip)
        terminal = self.doomgame.is_episode_finished()
        observation = None
        if terminal:
            # No observation available,
            # give the previous observation
            observation = self.last_observation
        else:
            state = self.doomgame.get_state()
            observation = self._preprocess_state(state)
        # Keep track of the last_observation
        # in case we hit end of the episode
        # (no state available, give last_observation instead)
        self.last_observation = observation
        return observation, reward, terminal, {}

    def reset(self):
        self.doomgame.new_episode()
        state = self.doomgame.get_state()
        observation = self._preprocess_state(state)
        self.last_observation = observation
        return observation
```

**Comment by EXJUSTICE** [comment]
> You can take a look at [ViZDoomGym's version](https://github.com/shakenes/vizdoomgym/blob/master/vizdoomgym/envs/vizdoomenv.py), where they return zeros. My version is more or less the same, with `step` and `reset` functions as below:
> 
> ```python
>     def step(self, action):
>         action = self.action_handler(action)
>         reward = self.doomgame.make_action(action, self.frame_skip)
>         terminal = self.doomgame.is_episode_finished()
>         observation = None
>         if terminal:
>             # No observation available,
>             # give the previous observation
>             observation = self.last_observation
>         else:
>             state = self.doomgame.get_state()
>             observation = self._preprocess_state(state)
>         # Keep track of the last_observation
>         # in case we hit end of the episode
>         # (no state available, give last_observation instead)
>         self.last_observation = observation
>         return observation, reward, terminal, {}
> 
>     def reset(self):
>         self.doomgame.new_episode()
>         state = self.doomgame.get_state()
>         observation = self._preprocess_state(state)
>         self.last_observation = observation
>         return observation
> ```
> 
> And yeap I am from Finland :)

Yes kiitokset avusta. Willl handle it from here!
