### ISSUE TITLE
Error during evaluation of learning_python.py

### ISSUE THREAD

**Issue by EXJUSTICE** [mwydmuch/ViZDoom#454]
I'm trying to setup a colaboratory version of the python training script.
Vizdoom version is

Training and testing does work, however I've tried to make some modifications to the evaluation section found in the main method. I've tried to setup an image array where I could store screenshots, in order to join it into a video. I've had some previous success with a tensorflow based approach, but with the script below all I'm seeing is a black screen. Is there a native method to take ingame screenshots? Or even better, a wrapper to display video?

```
# Reinitialize the game with window visible
game =initialize()
game.set_window_visible(False)

game.init()

img_array = []
for _ in range(episodes_to_watch):
    game.new_episode()
    while not game.is_episode_finished():
        
          image = game.get_state().screen_buffer
          
          state = preprocess(image)
          state = state.reshape([1, 1, resolution[0], resolution[1]])
          best_action_index = get_best_action(state)

          # Instead of make_action(a, frame_repeat) in order to make the animation smooth
          game.make_action(actions[best_action_index], frame_repeat)
          if not game.is_episode_finished():
            image=game.get_state().screen_buffer
            img_array.append(image)

            
    # Sleep between episodes
    sleep(1.0)
    score = game.get_total_reward()
    print("Total score: ", score)
    
```

Also, while the first run of this section works, running it a second time without resetting the whole runtime gives me a stranger error

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-24-f199cc4b335e> in <module>()
     14           state = preprocess(image)
     15           state = state.reshape([1, 1, resolution[0], resolution[1]])
---> 16           best_action_index = get_best_action(state)
     17 
     18           # Instead of make_action(a, frame_repeat) in order to make the animation smooth

3 frames
<ipython-input-12-74f538caacce> in forward(self, x)
     10         x = F.relu(self.conv1(x))
     11         x = F.relu(self.conv2(x))
---> 12         x = x.view(-1, 192)
     13         x = F.relu(self.fc1(x))
     14         return self.fc2(x)

RuntimeError: shape '[-1, 192]' is invalid for input of size 66360
```
The input size shouldn't have changed at all, so I am confused as to why this would happen. Any advice is appreciated!

Thank you

**Comment by Miffyli** [comment]
Hmm I am not sure what will happen if you call `get_state()` twice in a row, as you are doing now. I would change the script to something like

```python
while not game.is_episode_finished():
        
          image = game.get_state().screen_buffer
          img_array.append(image)
          state = preprocess(image)
          state = state.reshape([1, 1, resolution[0], resolution[1]])
          best_action_index = get_best_action(state)

          game.make_action(actions[best_action_index], frame_repeat)
```
This should work without a hitch. For storing videos, [cv2.VideoWriter](https://stackoverflow.com/questions/46183681/opencv2-python-cv2-videowriter) does a sufficient job. If you want even smoother/higher-quality recordings (and with different settings), you should store [a replay of the game](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/record_episodes.py) and play it back later along with some recording.

**Comment by EXJUSTICE** [comment]
Thank you Anssi. What is the role of the frame_repeat parameter?

**Comment by Miffyli** [comment]
It defines how many frames game will be executed with given actions, e.g. 1 means we only proceed by one frame, 4 means we proceed by four frames. This stems from the original [DQN paper](https://daiwk.github.io/assets/dqn.pdf) where authors use frame-skip to ease the learning, and it also make simulation faster by reducing amount of data transferred between ViZDoom and Python.

**Comment by EXJUSTICE** [comment]
Thank you, yes that's what I suspected. I had previously implemented that manually.
Finally, I remain slightly confused about when to use make_action vs advance_action

In the original script  it was written

```
# Instead of make_action(a, frame_repeat) in order to make the animation smooth
            game.set_action(actions[best_action_index])
            for _ in range(frame_repeat):
                game.advance_action()
                sleep(0.03)

How does this make the animation smoother?
```

**Comment by Miffyli** [comment]
There are quite well covered in [docs](https://github.com/mwydmuch/ViZDoom/blob/master/doc/DoomGame.md). `make_action` covers setting the action, executing it and obtaining the reward. `advance_action` only advances the currently set action. If you want smoother animations, you can use the manual version like you have defined, where you read the state after each `advance_action` and store it.

**Comment by EXJUSTICE** [comment]
Kiitän!

**Comment by EXJUSTICE** [comment]
Hi Anssi

I've trained the model for 20 epochs successfully

However when attempting to run the script to capture some frames of gameplay
```

game =initialize()
game.set_window_visible(False)

game.init()


img_array = []
for _ in range(5):
    game.new_episode()
    while not game.is_episode_finished():
        
          image = game.get_state().screen_buffer
          img_array.append(image)
          state = preprocess(image)
          state = state.reshape([1, 1, resolution[0], resolution[1]])
          best_action_index = get_best_action(state)

          # Instead of make_action(a, frame_repeat) in order to make the animation smooth
          game.make_action(actions[best_action_index], frame_repeat)
          

            
    # Sleep between episodes
    sleep(1.0)
    score = game.get_total_reward()
    print("Total score: ", score)
```

The length of the img_array is still 0, hence all videos are empty. I am trying to capture frames during training instead, but any assistance would be appreciated, as I don't see if I've missed anything!

**Comment by Miffyli** [comment]
I do not see why `img_array` would be empty after that code. My best guess is that `is_episode_finished()` returns True even though new episode was just restarted (may need a `get_state()` before you can check reliably for `is_episode_finished`?). But if the code works other than that, then I am not sure why it happens.

> Not sure if its due to the GRAYINT8 encoding.
This could very well be. The video writer might be expecting arrays of shape `[3, H, W]`, and here you have only one channel. Try repeating the channel three times.

**Comment by EXJUSTICE** [comment]
Thank you for your help. I do have the notebook ready otherwise, but I do not know if the repo needs it? I believe there was an issue stating that it should be easier to use.

Apart from the visualization issue, the notebook works fine. Please let me know if I should fork and do a PR

**Comment by Miffyli** [comment]
Thanks for the offer, but I think the examples are as good as the examples get. Using them in a notebook is just matter of copy/paste (which you can not do the other way around from a .ipynb file) :). The other issue was bit of a joke.

**Comment by EXJUSTICE** [comment]
Selvä, kiitos taas!
