### ISSUE TITLE
How to set the green landmarks in NavDoom?

### ISSUE THREAD

**Issue by fanyuzeng** [mwydmuch/ViZDoom#455]
Hi, I'm using [NavDoom](https://github.com/agiantwhale/NavDoom) to generate the vizdoom world, and there are lots of "green landmarks" as shown in the image below. I regards the green landmarks as obstacle for navigation agents training. However, the number of "green landmarks" are too many, and I want to reduce their number. How to set the number of the green landmarks?
<img width="977" alt="02" src="https://user-images.githubusercontent.com/19756145/83498719-d9b65b80-a4ee-11ea-8f5e-46992ef532ec.png">
<img width="998" alt="01" src="https://user-images.githubusercontent.com/19756145/83498723-db801f00-a4ee-11ea-8c00-fae9b9918982.png">

I look forward to your reply!

**Comment by mwydmuch** [comment]
Hi @fanyuzeng, this file controls green column spawning: https://github.com/agiantwhale/NavDoom/blob/master/content/static_goal_train.acs

You can modify line 5 (`#define REWARD_CHANCE 0.5`) to change the spawning frequency.
Or modify the part that starts at line 59 for some custom spawning behavior.

**Comment by fanyuzeng** [comment]
@mwydmuch This issue confuses me for a long time, thank you so much, it works now! I set "#define REWARD_CHANCE 0.05" and the number of the green landmarks is reduced.
