### ISSUE TITLE
My way home - how to set init room position

### ISSUE THREAD

**Issue by aklein1995** [mwydmuch/ViZDoom#462]
Hi,

I am trying to replicate the results of https://arxiv.org/pdf/1705.05363.pdf. There are 3 different settings: dense, sparse and very sparse. The difference between them is that the agent would be randomly initialized in any of the 17 rooms, or either in the room 13 or 17 (as explained in the paper).

I have already read all the doc and I do not find anything related to it, except the players position:
_POSITION_X - Position of the player, not available if viz_nocheat is enabled.
POSITION_Y
POSITION_Z_

However, this is only used to get the position, not to set it.

Any idea or advice?

Thank you in advance

**Comment by Miffyli** [comment]
You find the scenarios they used [in the paper repo](https://github.com/pathak22/noreward-rl).

**Comment by Miffyli** [comment]
Ah yes, you indeed need to modify the .wad files for that. `my_way_home.wad` works by having "map spots" with fixed TIDs (Thing ID) across the map on the spots where player _may_ spawn, and then ACS code in `SCRIPTS` entry will pick one of these spots at random and move player there (script 2). Simply remove all but one of these map spots (and fix range of TIDs in `SCRIPTS`), and that should spawn player in same position always. Remember to compile the `SCRIPTS` code after you make changes.

**Comment by aklein1995** [comment]
Thank you so much about your answer!

_I am using for the next description the _my_way_home.wad_ that could be found on this repo._

As far as I understand from script 2, we would get any of the map locations with ID 10 to 16. 
![image](https://user-images.githubusercontent.com/25618603/85702005-454eab80-b6de-11ea-8f05-d87962100860.png)

When I open the MAP I see that the IDs of the map locations go from 10 to 26 (instead of from 0 to 16). Taking that into account, the agent would be initialised only in 7 possible locations with that configuration file, right?
![image](https://user-images.githubusercontent.com/25618603/85701897-28b27380-b6de-11ea-9540-f09afab1ca81.png)

Moreover, looking into the MAP itself, I see that it is a thing of type Player 1 Start at the same position of map spot with ID 0. This Player Start thing affects in anything to our .wad configuration? Or we only care about the map spots IDs?
![image](https://user-images.githubusercontent.com/25618603/85702729-fce3bd80-b6de-11ea-87ff-b15f550b2b11.png)

**Comment by Miffyli** [comment]
> When I open the MAP I see that the IDs of the map locations go from 10 to 26 (instead of from 0 to 16). Taking that into account, the agent would be initialised only in 7 possible locations with that configuration file, right?

Note the range of random starts from `map_point_start_id` and ends to `map_point_start_id + map_points - 1`, i.e. it will go over all points. In the paper repo they might have set this to a lower amount in the "sparse" experiments (or completely removed the points).

> Moreover, looking into the MAP itself, I see that it is a thing of type Player 1 Start at the same position of map spot with ID 0. This Player Start thing affects in anything to our .wad configuration? Or we only care about the map spots IDs?

Player spawns originally to that point, as per game logic, but the above script immediately teleports player to the random spot on map.

**Comment by mwydmuch** [comment]
Hi @aklein1995, look again on the first line of the `script 2`, random range is from `map_point_start_id = 10` to `map_point_start_id + map_points - 1 = 26`. 

Player 1 start is required by map compiler and should be a valid place, but it doesn't affect a thing, cause player is teleported by `script 2` immediately (keyword `ENTER` after script id means that this script fires immediately for each new player actor that spawns in the map).

**Comment by aklein1995** [comment]
Very clear answers! Thank you both of you for your time!
