### ISSUE TITLE
How can I set the amount of ammo the agent starts with from a python script?

### ISSUE THREAD

**Issue by wichersn** [mwydmuch/ViZDoom#464]
I want to set the amount of ammo the agent starts with from the python script. Note I only need to do this at once and won't need to change it after.

**Comment by Miffyli** [comment]
You can give ammo via console commands with [`send_game_command`](https://github.com/mwydmuch/ViZDoom/blob/master/doc/DoomGame.md#-sendgamecommand) (e.g. `game.send_game_command("give clip")`), but I do not know if you can set it to a fixed amount. You can modify scenario ACS code in SLADE to set player's ammo to something specific, e.g.

```
script 2 ENTER
{
	ClearInventory();	
	GiveInventory("ChainGun",1);
	GiveInventory("Clip",1000);
}
```

**Comment by wichersn** [comment]
Thanks, here's what I ended up doing. I created a new ammo pack type in DECORATE.txt, so that I would only give 1 ammo per give command:

```
ACTOR CellPack_Single : Cell
{
  Inventory.Amount 1
  States
  {
  Spawn:
    CELP A -1
    Stop
  }
}
```

Then I could give a precise amount in the python code:

```
for _ in range(self.start_ammo):
     self._game.send_game_command("give CellPack_Single")
```
