### ISSUE TITLE
Labels Buffer?

### ISSUE THREAD

**Issue by ForbiddenEra** [mwydmuch/ViZDoom#469]
So, I was thinking that the labels buffer would encode different objects as different greyscale values..?

I know we can pull data out about each label in the buffer and such but if we were to just feed the visual data to a net for learning labelling, wouldn't we want each item type to be uniquely identifiable?

Right now it's more like shading the objects based on distance, kind of similar to the depth buffer.. unless I'm missing something..?

Apologies if there's a better place to discuss - if so, direct me there, thanks!

**Comment by Miffyli** [comment]
Take a look at [buffers](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/buffers.py) example and the [script that creates the gif on the front page](https://github.com/mwydmuch/ViZDoom/blob/master/scripts/create_buffers_gif.py). I understand the second part of that gif is what you want? You can achieve that with the labels buffer as shown in the example.

**Comment by ForbiddenEra** [comment]
Thanks I was actually just looking at the labels example which also colors it.. just kind of thought that the default would've been that.
