### ISSUE TITLE
Adding synthetic screens (random openings of menu/console/cutscene) to the gameplay

### ISSUE THREAD

**Issue by bahadirbasaran** [mwydmuch/ViZDoom#473]
Hello!

I'd like to use ViZDoom and the pre-trained agent "Arnold" together for my research. For my purpose, my first goal is to enrich the game screens by adding synthetic screens during the gameplay (random openings of the menu, console and some short cutscenes).

To summarize, I want to make the pre-trained agent "Arnold" play the game and during the gameplay, sometimes (randomly) the menu, the console and a pre-defined cutscene will be seen by the agent. 
For example, in random intervals:
- pause the game -> open the menu
- pause the game -> open the console
- pause the game -> play a cutscene

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for random x seconds -> resume the game and the agent continues to play where it left.

I had a look at the tutorial, ACS scripting and etc. for this purpose but I couldn't find what I want. 

Any suggestion would help me a lot. Thanks!

**Comment by Miffyli** [comment]
I think this could be done by using [`send_game_command`](https://github.com/mwydmuch/ViZDoom/blob/master/doc/DoomGame.md#-sendgamecommand) together with some console aliases and [different controls](https://zdoom.org/wiki/Customize_controls). At the very least `game.send_game_command("toggleconsole")` seems to work and opens the console in the game. I think there is a similar command for menu at least, but do not know about cutscenes (there are not too many "cutscenes" in Doom, apart from the text things). I am not sure what happens to agent controls when menu/console is open.

**Comment by mwydmuch** [comment]
Hi @bahadirbasaran, as @Miffyli explained, it's possible via `send_game_command`, but I'm also not sure about the impact. Some may block the input form agent to the game's actor others may leave a possibility to control the actor. Have you considered just to input this on your controller side? You can easily modify frames from the ViZDoom environment by pasting some elements or replacing them entirely with different images and then feed the agent with them.

**Comment by bahadirbasaran** [comment]
Thank you for such quick and useful replies @Miffyli @mwydmuch !

> I think there is a similar command for menu at least, but do not know about cutscenes (there are not too many "cutscenes" in Doom, apart from the text things). I am not sure what happens to agent controls when menu/console is open.

"send_game_command" with "toggleconsole" string is working and the use of different strings such "menu_options" seems a valid idea. In regard to "cutscene", I can embed a short video clip as a cutscene, if I can find a way to do. Imagine the first 10 seconds of [this video](https://www.youtube.com/watch?v=u4S5ECp7iYE&ab_channel=PointZero) or [this one](https://www.youtube.com/watch?v=T5UF6ashzkw&ab_channel=howaboutbecause) (let's say ripped into 640x480). My intention is to make the agent label frames in the cutscene/menu/console etc. and when it is over, to make the agent continue its game where it left.

> Hi @bahadirbasaran, as @Miffyli explained, it's possible via `send_game_command`, but I'm also not sure about the impact. Some may block the input form agent to the game's actor others may leave a possibility to control the actor. 

I couldn't understand your hesitation well. Do you mean that usage of this command may harm the behavior of the agent?

> Have you considered just to input this on your controller side? You can easily modify frames from the ViZDoom environment by pasting some elements or replacing them entirely with different images and then feed the agent with them.

Actually, that is my exact purpose in this step and the only way I could find (thanks to both of you) is the use of "send_game_command". How can I achieve this in your alternative solution? I would love to hear that because I haven't found any alternative in https://zdoom.org/wiki yet.

**Comment by mwydmuch** [comment]
> I couldn't understand your hesitation well. Do you mean that usage of this command may harm the behavior of the agent?
Yeah, potentially it can impact how the actor is controlled, for example, toggling the menu can interrupt the forward movement of the actor. Just a warning, maybe it doesn't happen.

> Actually, that is my exact purpose in this step and the only way I could find (thanks to both of you) is the use of "send_game_command". How can I achieve this in your alternative solution? I would love to hear that because I haven't found any alternative in https://zdoom.org/wiki yet.

My proposal is to leave the game engine alone and just modify its output. `DoomGame.get_state()` returns a state that includes a screen picture (`screen_buffer` field) as a NumPy array. You can just modify this array before passing it to the agent to decide on the next action. So you can add a picture of a menu to it or a console or even replace it entirely with the frames from a movie.

**Comment by bahadirbasaran** [comment]
> Yeah, potentially it can impact how the actor is controlled, for example, toggling the menu can interrupt the forward movement of the actor. Just a warning, maybe it doesn't happen.

I got it. You might have a point.

> My proposal is to leave the game engine alone and just modify its output. `DoomGame.get_state()` returns a state that includes a screen picture (`screen_buffer` field) as a NumPy array. You can just modify this array before passing it to the agent to decide on the next action. So you can add a picture of a menu to it or a console or even replace it entirely with the frames from a movie.

Sounds like a good idea! However, in this way, shouldn't I pause the game before feeding the agent with my synthetic screen buffer? Otherwise the agent is going to see a different screen while it is being attacked or etc. . Hence if I pause the game first, feed the agent with my screen for x seconds and then resume the game to feed the agent back with real screen buffer, isn't this manipulating the game engine like in the former case?

**Comment by Miffyli** [comment]
> Sounds like a good idea! However, in this way, shouldn't I pause the game before feeding the agent with my synthetic screen buffer? Otherwise the agent is going to see a different screen while it is being attacked or etc. . Hence if I pause the game first, feed the agent with my screen for x seconds and then resume the game to feed the agent back with real screen buffer, isn't this manipulating the game engine like in the former case?

This only happens if you are using the ASYNC modes (the game runs at constant speed, does not wait for Python commands). Otherwise ViZDoom patiently waits for Python for more commands. You can pause the game (i.e. not do `make_action`), feed in some menu/console/cutscene images to your agent and then return back to game when you are done with those.

**Comment by bahadirbasaran** [comment]
Thank you for your help! I will try these ideas and update this issue based on the outcome.

**Comment by bahadirbasaran** [comment]
Hello again! I have a question
