### ISSUE TITLE
How to save Screen Buffer properly for dataset generation purposes?

### ISSUE THREAD

**Issue by bahadirbasaran** [mwydmuch/ViZDoom#476]
Hello!
I would like to use my agent for dataset generation purposes and I have a question related to the Screen Buffer. 
I am saving the screen buffer into a file after each action. However, if I save it directly, it skips some rows&columns (because of the huge shape (3, 225, 400) ):  [https://pasteboard.co/JEiXWZz.png](url)

One option would be looping on the buffer and writing the elements iteratively, but I guess there would be a more optimal solution. Is there any better way to save the screen buffer after each action? I'd like to generate a dataset and then I am planning to use it for analysis purposes.  This dataset will be a product of maybe hundreds of games, so I need a better way to store this data, in terms of both efficiency and space.

I appreciate any help, thanks.

**Comment by Miffyli** [comment]
Hey. The code is not actually skipping any of the rows or columns, it is just the numpy printing that cuts out the parts to avoid printing all the numbers. 

However if you still have trouble with huge size of the data, you could try [recording the episodes instead](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/record_episodes.py), or alternatively compress the images with JPG encoding (using e.g. PIL).

**Comment by mwydmuch** [comment]
Hi @bahadirbasaran,
instead of printing it to the file, you should probably save them in the binary format using `numpy.save` or `pickle`.

**Comment by bahadirbasaran** [comment]
> Hey. The code is not actually skipping any of the rows or columns, it is just the numpy printing that cuts out the parts to avoid printing all the numbers.
> However if you still have trouble with huge size of the data, you could try [recording the episodes instead](https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/record_episodes.py), or alternatively compress the images with JPG encoding (using e.g. PIL).

So you say, it is actually recording the screen buffer properly but I visualize it on the file like it's being cropped, in terms of lack of space. I guess neither the episode recording nor JPG encoding approaches are valid for my case because I need to generate a dataset of <frame-label> pairs.
Thank you!

>instead of printing it to the file, you should probably save them in the binary format using numpy.save or pickle.

Thank you @mwydmuch ! Frankly, I have also considered these approaches for a moment but then I decided to give a chance in this way, in terms of readability. I guess you are right. This makes more sense.

I think it is better to use the "numpy.save" instead of "pickle", considering it was written in C. ıt might be faster and better in terms of space.
