### ISSUE TITLE
ViZDoomController.cpp  ‘placeholders’ is not a namespace-name

### ISSUE THREAD

**Issue by Brodong** [mwydmuch/ViZDoom#477]
I got some errors when using  "pip install vizdoom" command:
```
In file included from /tmp/pip-install-1ogpxwj2/vizdoom_b671d4ec416b4ab9b5ddf6995dfbd165/src/lib/ViZDoomController.cpp:23:0:
    /tmp/pip-install-1ogpxwj2/vizdoom_b671d4ec416b4ab9b5ddf6995dfbd165/src/lib/ViZDoomController.h:44:34: error: ‘placeholders’ is not a namespace-name
         namespace bpl       = boost::placeholders;
                                      ^
    /tmp/pip-install-1ogpxwj2/vizdoom_b671d4ec416b4ab9b5ddf6995dfbd165/src/lib/ViZDoomController.h:44:46: error: expected namespace-name before ‘;’ token
         namespace bpl       = boost::placeholders;

/tmp/pip-install-1ogpxwj2/vizdoom_b671d4ec416b4ab9b5ddf6995dfbd165/src/lib/ViZDoomController.cpp: In member function ‘void vizdoom::DoomController::handleSignals()’:
    /tmp/pip-install-1ogpxwj2/vizdoom_b671d4ec416b4ab9b5ddf6995dfbd165/src/lib/ViZDoomController.cpp:1096:74: error: ‘bpl’ has not been declared
             signals.async_wait(b::bind(signalHandler, b::ref(signals), this, bpl::_1, bpl::_2));
```

My Cmake version is:
cmake -version
cmake version 3.19.1

My OS is ubuntu16.0, and Python is 3.5.

I have meet all the requirements.

**Comment by mwydmuch** [comment]
Hi @Brodong, you probably have any old version of the boost library installed in your system. The newest version 1.1.8 of ViZDoom requires at least boost version 1.67. If you can't upgrade your boost version, try installing ViZDoom 1.1.7, this version is compatible with older boosts, but not with new ones.

**Comment by Brodong** [comment]
> Hi @Brodong, you probably have an old version of the boost library installed in your system. The newest version 1.1.8 of ViZDoom requires at least boost version 1.67. If you can't upgrade your boost version, try installing ViZDoom 1.1.7, this version is compatible with older boosts, but not with new ones.

**Comment by Brodong** [comment]
> Hi @Brodong, you probably have an old version of the boost library installed in your system. The newest version 1.1.8 of ViZDoom requires at least boost version 1.67. If you can't upgrade your boost version, try installing ViZDoom 1.1.7, this version is compatible with older boosts, but not with new ones.

Yes, I successfully installed it. :+1: 
Thank you very much!!!
I have been tossing for 2 days, and then I solved it in a few minutes with your help! 
Thanks again!

**Comment by mwydmuch** [comment]
Glad to hear that! Do not hesitate to ask a question here in case of any problems :)

**Comment by Brodong** [comment]
**I have a suggestion...**

This is the dependency I saw on the readme:
Linux
CMake 2.8+
Make
GCC 4.9+
Boost libraries 1.54+
Python 2.7+ or Python 3+ with Numpy for Python binding (optional)
JDK for Java binding (JAVA_HOME must be set) (optional)
Torch7 for Lua binding (optional)

And my Boost version is "boost1.58"，So I always thought I had met the requirements.
However,  the newest version 1.1.8 of ViZDoom requires at least boost version 1.67...

So, I think you may need **update the readme**...

**Comment by mwydmuch** [comment]
Thank you for point this out, I will update the docs.
