### ISSUE TITLE
Cmake not finding Cmakelist.txt but its there....

### ISSUE THREAD

**Issue by WindowsXPSux** [mwydmuch/ViZDoom#483]
I'm currently following the steps for linux, everything seems fine untill I get to the "cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON=ON -DBUILD_JAVA=ON -DBUILD_LUA=ON -DBUILD_JULIA=ON"  command when I run it I get the following error " CMake Error: The source directory "/home/windows/.local/lib/python3.8/site-packages/vizdoom" does not appear to contain CMakeLists.txt."

using Ubuntu terminal in windows 10, had this working fine on my old HDD but it failed and am trying to get it setup again

Here's a copy of the last few commands I tried, it shows the txt file in the list, why wont cmake find\use it?

**windows@Sager:~**/.local/lib/python3.8/site-packages/vizdoom/build$ **ls**
CMakeLists.txt

**windows@Sager:~**/.local/lib/python3.8/site-packages/vizdoom/build$ **cd ..**

**windows@Sager:~**/.local/lib/python3.8/site-packages/vizdoom$ **ls**
CMakeLists.txt     MANIFEST.in  __init__.py  bots.cfg  cmake_all.bat  cmake_clean.sh  doc     examples       include     pyproject.toml  scripts   src      vizdoom.pk3
ISSUE_TEMPLATE.md  README.md    __pycache__  build     cmake_all.sh   cmake_modules   docker  freedoom2.wad  mkdocs.yml  scenarios       setup.py  vizdoom  vizdoom.so

**windows@Sager:~**/.local/lib/python3.8/site-packages/vizdoom$ **cd build**

**windows@Sager:~**/.local/lib/python3.8/site-packages/vizdoom/build$ **cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON3=ON -DBUILD_JAVA=ON -DBUILD_LUA=ON -DBUILD_JULIA=ON**

CMake Error: The source directory "/home/windows/.local/lib/python3.8/site-packages/vizdoom" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Any help would be greatly appreciated also any questions feel free to ask and I'll answer them that best I can

**Comment by Miffyli** [comment]
@mwydmuch Would you have insight on this as you are more familiar with compiling steps?

**Comment by mwydmuch** [comment]
Hi @WindowsXPSux, I'm a bit confused by the way you are trying to build ViZDoom on WSL (I assume). Why not just use `pip install vizdoom`?

**Comment by WindowsXPSux** [comment]
I like to learn the hard way before the easy way lol I said screw it and installed it on in windows instead. I appreciate the quick response to my issue though

**Comment by mwydmuch** [comment]
We released a new version with better support for the native Windows version and WSL. Closing.
