### ISSUE TITLE
[WARNING] Audio buffers were full of silence

### ISSUE THREAD

**Issue by Neddd** [mwydmuch/ViZDoom#489]
### Questions, features suggestions and requests

If you have a question, features suggestions or requests, do not hesitate to ask.
However, you can check **[FAQ](doc/FAQ.md)** section and already existing issues with "question" tag ([is:issue label:question](https://github.com/mwydmuch/ViZDoom/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquestion)) first.

### Issues

If you encountered an issue, please post the following things:
description of an issue,
* [WARNING] Audio buffers were full of silence

ViZDoom version you are using,
* 1.1.9

information about your OS platform, distribution and environment (GCC, Python, Java, Lua versions etc.),
* Win10 19042
* python 3.7.12 x64
* boost 1.65.1 x64
* fluidsynth2.2.3 x64 OR the version included in ViZDoomWinDepBin
* openal-soft 1.21.1 x64 OR the version included in ViZDoomWinDepBin

if you encountered a crash or bug, provide information about scenarios you are using and configuration of the ViZDoom environment,
* At the moment I'm just trying to run the python audio_buffer example
* Trying all these options and still getting the empty buffers problem.

Tried game.add_game_args('+snd_efx 0')
 
Anything else I can try?

Thanks!

**Comment by Miffyli** [comment]
Hey. How did you install ViZDoom, exactly? Did you build it yourself or where did you take the binary? Or did you run it under linux subsystem? None of these have been tried out before tbh.

Check this comment for possible things you could try, but I am not sure if they apply to Windows: https://github.com/mwydmuch/ViZDoom/pull/486#issuecomment-895128340

**Comment by Neddd** [comment]
> Hey. How did you install ViZDoom, exactly? Did you build it yourself or where did you take the binary? Or did you run it under linux subsystem? None of these have been tried out before tbh.
> 
> Check this comment for possible things you could try, but I am not sure if they apply to Windows: [#486 (comment)](https://github.com/mwydmuch/ViZDoom/pull/486#issuecomment-895128340)

I configured the build myself with cmake 3.12.3 specifically cmake-gui
Then built in VS 2017 x64 and x86 (these variations x86/x86, x86/x64, x64/x86, x64/x64)

Are there any flags that can tell if it has found an acceptable openal32.dll?

I've also built the same multiple versions of openal myself and built with them and the binary on their site and the one in the dependencies repo

**Comment by Miffyli** [comment]
Hmm unfortunately my extent of skills ends here (I am not too familiar with the building process). @mwydmuch anything you could pitch in? 

I think audio did work on ViZDoom in the past on pre-built binaries (hearing them from the stereo). Can you test if this still works or if it works with the previous prebuilt binaries? I.e., not audio buffers, but enabling sound and hearing it over speakers.

**Comment by mwydmuch** [comment]
Hi @Neddd, it seems that the latest changes broke CMakeLists on Windows, resulting in OpenAL not being correctly included. ViZDoom can be built without all sound stuff, so the warring is only visible in cmake output, and during ViZDoom start, there is `Sound init failed. Using nosound.` message. I will fix it today. Thank you for reporting this.

**Comment by mwydmuch** [comment]
I updated `cmake_all.bat` this now generates the correct project that uses OpenAL-Soft, which was also added to https://github.com/mwydmuch/ViZDoomWinDepBin repo. Right now OpenAL is linked dynamically, so after building you should copy `ViZDoomWinDepBin/openal-soft/bin/Win64/OpenAL.dll` to the same dir as your vizdoom.exe. Then audio_buffer will work as expected.

**Comment by Neddd** [comment]
Hi mwydmuch,
Cheers, I'll try it out. But I did notice that BUILDPYTHON was the only flag that worked, so I was using that.
Which Boost, cmake and fluidsynth versions do you recommend?
Thanks

**Comment by mwydmuch** [comment]
We now provide new pre-build releases for Windows 10/11 64-bit that can be installed `pip install vizdoom`.
Audio buffer now works out of the box with this release on Windows too, so I'm closing this one.
