### ISSUE TITLE
[question] get map coordinates

### ISSUE THREAD

**Issue by libphy** [mwydmuch/ViZDoom#492]
I'm wondering if there is a way to get coordinates of walls and objects from the game state. Is there such command? I'm using python, and I wanted to visualize the top view of maps.

**Comment by mwydmuch** [comment]
Hi @libphy, yes, there is, please see this example: https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/objects_and_sectors.py

**Comment by libphy** [comment]
Thank you!
