### ISSUE TITLE
ERROR: can't build docker image

### ISSUE THREAD

**Issue by marcopremigit** [mwydmuch/ViZDoom#493]
Hello everyone and thanks for your work!
I'm trying to build the docker image (I'm on Ubuntu 20.04), but during building I'm getting this error:

```
Cloning into '/home/vizdoom/vizdoom'...
Removing intermediate container 587ffc87ade8
 ---> e057150acb44
Step 12/16 : RUN pip3 install Cython
 ---> Running in f42800cab794
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 57
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
The command '/bin/sh -c pip3 install Cython' returned a non-zero code: 1
```
I tried both with  tensorflow and python3 image.

**Comment by Miffyli** [comment]
Seems like you are using Python 3.5, which I am not sure if it is supported. I would try installing a newer Python (e.g. 3.8 or even 3.10) and trying with that :).

**Comment by marcopremigit** [comment]
> Seems like you are using Python 3.5, which I am not sure if it is supported. I would try installing a newer Python (e.g. 3.8 or even 3.10) and trying with that :).

I'm using Python 3.9.5.

**Comment by Miffyli** [comment]
Hmm this here seems to indicate that it is using a different Python version:

`"/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py"

And that would make sense since format strings (`f"like {this}"`) are not supported by Python 3.6.

**Comment by marcopremigit** [comment]
Following your suggestion, I've modified the Dockerfile to use python 3.9 and the problem was solved.
Now I've the same problem as #491 , but I will post in that issue page. Thank you!
