### ISSUE TITLE
Position of the bots

### ISSUE THREAD

**Issue by bulaciox** [mwydmuch/ViZDoom#494]
I'm doing a class work consisting in a GOAP planner for VizDoom and to do it I need to find the position of the bots to be able to take actions against them, I've read a post which says that "objects_and_map.py" shows how to get information from the objects but I don't understand it.Could someone give me an example of how to get the position of the bots?

**Comment by Miffyli** [comment]
This is the part you are looking for:

https://github.com/mwydmuch/ViZDoom/blob/f73e8a2c2bafc0646118c1515ff6000f10b22e7c/examples/python/objects_and_sectors.py#L61-L74

You would have to print out what are the names of the objects, find the name you are interested (i.e. replace `o.name == "DoomPlayer"` with another string you look for) and plot them out / store the coordinates for your further processing.

**Comment by mwydmuch** [comment]
Hi @bulaciox, as Miffyli said. After enabling objects information (`game.set_objects_info_enabled(True)`), you can access `state.objects` that is a list containing the basic information about objects, including: the unique identifier of the object instance (`id`), the name of the object class (`name`) and position-related information (x, y, z coordinates, rotation, and velocity). All players taking part in multiplayer games and bots that replace them have `DoomPlayer` class. So you want to track all objects with `name == 'DoomPlayer'`. Please note that if `+viz_nocheat` flag is enabled as in our multiplayer examples, this information is not passed to the state even if `game.set_objects_info_enabled is set to True`.

**Comment by mwydmuch** [comment]
Here is a modified `cig_multiplayer_bots.py` example that prints positions of all players - bots, including the player.
https://gist.github.com/mwydmuch/b3b243242b071ba209c5467549a16ded
