### ISSUE TITLE
Ubuntu SegFault basic.py

### ISSUE THREAD

**Issue by pawni** [mwydmuch/ViZDoom#51]
Hi there,

I just built ViZDoom according to the instructions but can't get the basic example to run.

[vizdoom-crash.txt](https://github.com/Marqt/ViZDoom/files/245967/vizdoom-crash.txt)

Any ideas which might be going wrong? CMake and make worked without problems. However, I also tried to build ZDoom directly but had problems with fmodex being built but I installed the library and ViZDoom finds it without problems.

**Comment by wjaskowski** [comment]
Does bin/vizdoom alone work for you?

**Comment by pawni** [comment]
No it doesn't:

```
../../bin/vizdoom -iwad ../../scenarios/freedoom2.wad
ViZDoom 1.0.0 (ZDOOM 2.8.1) - SDL version
Compiled on May  2 2016

M_LoadDefaults: Load system defaults.
Gameinfo scan took 0 ms
W_Init: Init WADfiles.
 adding /home/nick/c9workspace/ViZDoom/bin/vizdoom.pk3, 583 lumps
 adding ../../scenarios/freedoom2.wad, 3329 lumps
I_Init: Setting up machine state.
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Family 6, Model 94, Stepping 3
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
I_InitSound: Initializing FMOD
FMOD Sound System, copyright \ufffd Firelight Technologies Pty, Ltd., 1994-2009.
Loaded FMOD version 4.26.36
OSS could not be initialized. Trying ALSA.
V_Init: allocate screen.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
Adding dehacked patch freedoom2.wad:DEHACKED
Patch installed
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading default status bar definition.
ParseSBarInfo: Loading custom status bar definition.
===========================================================================
This is Freedoom, the free content first person shooter.

Freedoom is freely redistributable under the terms of the modified BSD
license. Check out the Freedoom website for more information:

    https://freedoom.github.io/
============================================================================
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)


*** Fatal Error ***
Segmentation fault (signal 11)
Address: (nil)

Generating vizdoom-crash.log and killing process 4336, please wait... 40	../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
Killed
```
I also get the same error with zdoom (which finally compiled etc)

**Comment by wjaskowski** [comment]
Could you try to execute bin/vizdoom with "-nomusic"?

**Comment by pawni** [comment]
I still get a SegFault with -nomusic . Is there anything else which could cause that?

**Comment by wjaskowski** [comment]
This seems like a ZDoom issue since you say that you have the same problem
on "pure" ZDoom. Would you mind if I ask you to post this on
http://forum.zdoom.org/? You can also check whether the precompiled version
works on your machine: http://zdoom.org/Download.

Could you also provide me your full cmake log?

**Comment by pawni** [comment]
I will post on the zdoom forum as the precompiled package also gives a SegFault.

However, I also attached the full cmake log:
[cmake.txt](https://github.com/Marqt/ViZDoom/files/247755/cmake.txt)

**Comment by wjaskowski** [comment]
One thing you can check is to remove FMOD (vizdoom works without it)

**Comment by wjaskowski** [comment]
@pawni Have you resolved this problem?

**Comment by pawni** [comment]
I did not have the chance to look into it again yet and I probably won't be able to check it within the next month. I will have a look after that.
