### ISSUE TITLE
Deprecation warning of old cmake policy CMP0026

### ISSUE THREAD

**Issue by Vigilans** [mwydmuch/ViZDoom#510]
### Issues

Newer version of cmake (cmake version 3.23.2) will produce a deprecation warning of OLD cmake_policy that cannot be turned off:

https://github.com/mwydmuch/ViZDoom/blob/ee8c6b10a09397981e38f1ba6c1bb9ef7eb204ab/cmake_modules/CreateLaunchers.cmake#L47-L49

Will produce message like:
![image](https://user-images.githubusercontent.com/20227484/174097088-c596561c-fb89-43b3-aacf-dc6aa6e01512.png)

These lines of code were first introduced 7 years ago (https://github.com/mwydmuch/ViZDoom/commit/929d2de510402bf1524531262f22fe8c6bb52d83). After test removing it, configure and build, no error has occured. So this policy setting may be considered to be removed or like to tame the deprecation warning.

**Comment by mwydmuch** [comment]
Hello @Vigilans, thank you for this remark, functions defined in this file are used only by MSVC Windows build, so unless you tested it on Windows, then they are not necessarily safe to remove. I added the condition that silence this warning when using other environments.

**Comment by Vigilans** [comment]
Thanks for your reply and commit! I've tested it in my project and the warning is properly fixed now.
