### ISSUE TITLE
Global reward for all agents in multiplayer

### ISSUE THREAD

**Issue by McFredward** [mwydmuch/ViZDoom#512]
I'm trying to implement a custom Multiplayer-Deathmatch Scenario with a custom ACS-Script.
I want to punish shots, health decrease and death and reward killing other players.

<details>
<summary><b>Therefore, I've coded this ACS-Script</b></summary>

    #include "zcommon.acs"
    global int 0:reward;
    
    script 1 OPEN
    {
        reward = 0;
	    Thing_ChangeTID(0, 1000 + PlayerNumber());
    }
     
    script 2 ENTER
    {
        TakeInventory("Fist",1);
	    SetThingSpecial( 1000 + PlayerNumber(), ACS_ExecuteAlways, 3);
	    
        int bullets = CheckInventory("Clip");
        int health = GetActorProperty(1000 + PlayerNumber(),APROP_Health);
	    int frags = PlayerFrags();
        while(true)
        {        
            int t_bullets = CheckInventory("Clip");
            if(t_bullets < bullets)
            {
                reward = reward - 5.0;
            }
            bullets = t_bullets;
		    
            int t_health = GetActorProperty(1000 + PlayerNumber(),APROP_Health);
            if(t_health < health)
            {
	            reward = reward - 20.0;
            }
            health = t_health;
            
            int t_frags = PlayerFrags();
            if(t_frags > frags)
            {
	            reward = reward + 200.0;
            }
            frags = t_frags;
        
            delay(1);
        }
    }
    
    script 3 (void)
    {
	    reward = reward - 100.0;
	    Exit_Normal(0);
    }
</details>

At first I thought that this is executed for each player indivually, so every player have a unique reward, but it seems that **the reward is global for the map** all players are in. So for example if one agent is shooting, all agents get a punishment of `-5` and not only the one who shot. 
Is there a way to change the reward for specific players only?

**Comment by Miffyli** [comment]
I am not 100% sure how to fix this on ACS side, but you could do this on the Python side by reading the GAME_VARIABLEs and constructing reward function based on the variables from there. You could also check other multiplayer-related repositories which work on these things, such as [sample-factory](https://github.com/alex-petrenko/sample-factory) to see if they some guidance to offer :)

**Comment by mwydmuch** [comment]
Hi @McFredward, unfortunately, some of the ACS functions aren't well designed for the multiplayer, so you need to be extra careful when writing the scripts. It's a good idea to use functions that allow you to specify the actor id. In this case I would replace `CheckInventory("Clip");` with `CheckActorInventory(1000 + PlayerNumber(), "Clip");` function.

**Comment by mwydmuch** [comment]
Also, please note, that ID is assigned to an actor (object present in the game world) when the player dies in multiplayer his body (actor) stays on the map as a corpse, and a new actor is assigned to the player after respawning. Your script assigns a new id to actors only once at the beginning of the map (OPEN script). To be honest I'm not even sure if this is valid since OPEN happens before players are spawned, this might be the part of the issue). 

To make you script better you would like to apply these changes:
```
script 1 OPEN // Runs once at the start of the map
{
    reward = 0;
}

script 2 ENTER // Runs once whey player enters the game
{
    Thing_ChangeTID(0, 1000 + PlayerNumber());
    [...]
}

[...]

script 4 RESPAWN // Runs each time player respawns
{
    Thing_ChangeTID(0, 1000 + PlayerNumber());
}

script 5 DEATH // This is important! We want to remove the id from the corpse
{
    Thing_ChangeTID(0, 0);
}
```

**Comment by McFredward** [comment]
Thanks for your response! I've tried your recommendations but this couldn't fix the issue that all changes to the reward with the ACS-script are globally changed for all players within the map. 

As recommended by @Miffyli , I now shifted the reward-calculation to the python script and left the ACS-script more or less empty. With the help of the Game Variables I was able to determine a reward for each player indivually :).

**Comment by mwydmuch** [comment]
This made me think that it might be a good idea to add a function that allows you to select which global variable is interpreted as a reward (now it's always 0). This would allow solving this exact problem in a more elegant way. What do you think @Miffyli?

**Comment by Miffyli** [comment]
Could potentially be useful to situations like this, and I like the fact it would contain the environment definitions in the scenario file so you do not have to remember to update the Python side :D. But I do not see a big hurry for it.
